/**
 * Rocket League SDK
 * Auto-generated by Stev Peifer
 *
 * Usage:
 *   import { Structs, Classes, Enums, Offsets } from "rlsdk";
 *   Structs.TAGame.FCarStateData
 *   Classes.TAGame.UCar_TA
 *   Enums.TAGame.EBoostType
 *   Offsets.TAGame.CarComponent_Boost_TA.CurrentBoostAmount
 *
 * Or import types from a single path:
 *   import { Classes, Structs } from "rlsdk/types";
 *   Classes.TAGame.UCar_TA
 *   Structs.Core.FVector
 *
 * Or import directly from subdirectories:
 *   import { TAGame } from "rlsdk/classes";
 *   TAGame.UCar_TA
 */

// Core types (FName, FScriptDelegate)
export * from './types';

// Structs namespace
export * as Structs from './structs';

// Classes namespace
export * as Classes from './classes';

// Enums namespace
export * as Enums from './enums';

// Offsets namespace
export * as Offsets from './offsets';

// Parameters namespace
export * as Parameters from './parameters';

// Note: Constants are available via separate imports:
// import { ... } from 'rlsdk/constants'
// import { ... } from 'rlsdk/constants/TAGame'