/**
 * SDK Offsets
 * Auto-generated by Stev Peifer
 *
 * These offsets are hardcoded from the SDK generation process.
 * They may need to be updated when the game is patched.
 */

/** GNames offset from module base */
export const GNames = 0x23ed570n;

/** GObjects offset from module base */
export const GObjects = 0x23ed5b8n;
