/**
 * AkAudio Package - Structs
 * Auto-generated by Stev Peifer
 */

/**
 * ScriptStruct AkAudio.AkSoundSource.ActiveSound
 * Size: 0x0010
 */
export type FActiveSound = {
  PlayId: number;  // 0x0008 (0x0004) [int32]
  StopId: number;  // 0x000c (0x0004) [int32]
};

/**
 * ScriptStruct AkAudio.AkEnvironments.AkActorEnvironment
 * Size: 0x0018
 */
export type FAkActorEnvironment = {
};

/**
 * ScriptStruct AkAudio.AkEnvironments.AkEnvironment
 * Size: 0x0020
 */
export type FAkEnvironment = {
  Id: string;  // 0x0000 (0x0010) [FString]
  Priority: number;  // 0x0010 (0x0004) [int32]
  WetValue: number;  // 0x0014 (0x0004) [float]
  DryValue: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct AkAudio.InterpTrackAkEvent.AkEventTrackKey
 * Size: 0x0010
 */
export type FAkEventTrackKey = {
  Time: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct AkAudio.AkParamGroup.AkParamSet
 * Size: 0x00A0
 */
export type FAkParamSet = {
};

/**
 * ScriptStruct AkAudio.AkRevPhysicsSimulation.AkRevSimFrame
 * Size: 0x0010
 */
export type FAkRevSimFrame = {
  RPM: number;  // 0x0000 (0x0004) [float]
  Gear: number;  // 0x0004 (0x0004) [int32]
  RevGear: number;  // 0x0008 (0x0004) [int32]
  Velocity: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct AkAudio.AkRevPhysicsSimulation.AkRevSimPhysicsControls
 * Size: 0x0020
 */
export type FAkRevSimPhysicsControls = {
  Weight: number;  // 0x0000 (0x0004) [float]
  EngineTorque: number;  // 0x0004 (0x0004) [float]
  BreakingHorsePower: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct AkAudio.AkRevPhysicsSimulation.AkRevSimUpdateParams
 * Size: 0x0048
 */
export type FAkRevSimUpdateParams = {
  Throttle: number;  // 0x0000 (0x0004) [float]
  Brake: number;  // 0x0004 (0x0004) [float]
  EngineFrictionScale: number;  // 0x0008 (0x0004) [float]
  GroundFrictionScale: number;  // 0x000c (0x0004) [float]
  ClutchedGearRatio: number;  // 0x0010 (0x0004) [float]
  bEnableUpShifting: boolean;  // 0x0014 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct AkAudio.AkMusicAnalysis.MusicAnalysisInfo
 * Size: 0x001C
 */
export type FMusicAnalysisInfo = {
  LowEnergy: number;  // 0x0000 (0x0004) [float]
  HighEnergy: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct AkAudio.SeqAct_AkPlayMusicWithCues.MusicSyncEvent
 * Size: 0x0011
 */
export type FMusicSyncEvent = {
  CueName: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct AkAudio.AkSoundBanksInfo.SoundBankInfo
 * Size: 0x0030
 */
export type FSoundBankInfo = {
  ShortName: string;  // 0x0000 (0x0010) [FString]
  RelativePath: string;  // 0x0010 (0x0010) [FString]
  Language: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct AkAudio.AkEnvironments.uint
 * Size: 0x0004
 */
export type Fuint = {
  dummyint: number;  // 0x0000 (0x0004) [int32]
};
