/**
 * Core Package - Structs
 * Auto-generated by Stev Peifer
 */

// Built-in types

/**
 * FName - Unreal Engine name reference
 */
export type FName = {
  Index: number;  // 0x0000 (0x0004)
  Number: number;  // 0x0004 (0x0004)
};

/**
 * FScriptDelegate - Script delegate for dynamic function binding
 */
export type FScriptDelegate = {
  Object: bigint;  // 0x0000 (0x0008) - UObject pointer
  FunctionName: FName;  // 0x0008 (0x0008)
  _padding: bigint;  // 0x0010 (0x0008)
};

/**
 * ScriptStruct Core.Object.Array_Mirror
 * Size: 0x0010
 */
export type FArray_Mirror = {
  ArrayNum: number;  // 0x0008 (0x0004) [int32]
  ArrayMax: number;  // 0x000c (0x0004) [int32]
};

/**
 * ScriptStruct Core.DelegateTracker.AsyncDelegateInfo
 * Size: 0x0020
 */
export type FAsyncDelegateInfo = {
  CallbackId: number;  // 0x0000 (0x0004) [int32]
  AsyncDelegate: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct Core.Object.BitArray_Mirror
 * Size: 0x0020
 */
export type FBitArray_Mirror = {
  InlineData: number;  // 0x0008 (0x0010) [int32]
  NumBits: number;  // 0x0018 (0x0004) [int32]
  MaxBits: number;  // 0x001c (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.BoneAtom
 * Size: 0x0020
 */
export type FBoneAtom = {
  Scale: number;  // 0x001c (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.Box
 * Size: 0x0019
 */
export type FBox = {
};

/**
 * ScriptStruct Core.Object.BoxSphereBounds
 * Size: 0x001C
 */
export type FBoxSphereBounds = {
  SphereRadius: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct Core.Breadcrumbs.BreadcrumbEntry
 * Size: 0x0020
 */
export type FBreadcrumbEntry = {
  Category: string;  // 0x0000 (0x0010) [FString]
  Value: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct Core.Object.Color
 * Size: 0x0004
 */
export type FColor = {
};

/**
 * ScriptStruct Core.Object.Cylinder
 * Size: 0x0008
 */
export type FCylinder = {
  Radius: number;  // 0x0000 (0x0004) [float]
  Height: number;  // 0x0004 (0x0004) [float]
};

/**
 * ScriptStruct Core.Default__ScriptStruct
 * Size: 0x0000
 */
export type FDefault__ScriptStruct = {
};

/**
 * ScriptStruct Core.Object.Double
 * Size: 0x0008
 */
export type FDouble = {
  A: number;  // 0x0000 (0x0004) [int32]
  B: number;  // 0x0004 (0x0004) [int32]
};

/**
 * ScriptStruct Core._Types_Core.EncryptedKeyIndex
 * Size: 0x0004
 */
export type FEncryptedKeyIndex = {
  Index: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.FColorVertexBuffer_Mirror
 * Size: 0x001C
 */
export type FFColorVertexBuffer_Mirror = {
  Data: number;  // 0x0010 (0x0004) [int32]
  Stride: number;  // 0x0014 (0x0004) [int32]
  NumVertices: number;  // 0x0018 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.Guid
 * Size: 0x0010
 */
export type FGuid = {
  A: number;  // 0x0000 (0x0004) [int32]
  B: number;  // 0x0004 (0x0004) [int32]
  C: number;  // 0x0008 (0x0004) [int32]
  D: number;  // 0x000c (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.HatPointer
 * Size: 0x0008
 */
export type FHatPointer = {
  Dummy: bigint;  // 0x0000 (0x0008) [uint64]
};

/**
 * ScriptStruct Core.Object.IndirectArray_Mirror
 * Size: 0x0010
 */
export type FIndirectArray_Mirror = {
  ArrayNum: number;  // 0x0008 (0x0004) [int32]
  ArrayMax: number;  // 0x000c (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.InlinePointerArray_Mirror
 * Size: 0x0018
 */
export type FInlinePointerArray_Mirror = {
};

/**
 * ScriptStruct Core.ObjectProvider.InterfacePropertyInjection
 * Size: 0x0010
 */
export type FInterfacePropertyInjection = {
};

/**
 * ScriptStruct Core.Object.InterpCurveFloat
 * Size: 0x0011
 */
export type FInterpCurveFloat = {
};

/**
 * ScriptStruct Core.Object.InterpCurveLinearColor
 * Size: 0x0011
 */
export type FInterpCurveLinearColor = {
};

/**
 * ScriptStruct Core.Object.InterpCurvePointFloat
 * Size: 0x0019
 */
export type FInterpCurvePointFloat = {
  InVal: number;  // 0x0000 (0x0004) [float]
  OutVal: number;  // 0x0004 (0x0004) [float]
  ArriveTangent: number;  // 0x0008 (0x0004) [float]
  LeaveTangent: number;  // 0x000c (0x0004) [float]
  ArriveWeight: number;  // 0x0010 (0x0004) [float]
  LeaveWeight: number;  // 0x0014 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.InterpCurvePointLinearColor
 * Size: 0x0055
 */
export type FInterpCurvePointLinearColor = {
  InVal: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.InterpCurvePointQuat
 * Size: 0x0061
 */
export type FInterpCurvePointQuat = {
  InVal: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.InterpCurvePointTwoVectors
 * Size: 0x007D
 */
export type FInterpCurvePointTwoVectors = {
  InVal: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.InterpCurvePointVector
 * Size: 0x0041
 */
export type FInterpCurvePointVector = {
  InVal: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.InterpCurvePointVector2D
 * Size: 0x002D
 */
export type FInterpCurvePointVector2D = {
  InVal: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.InterpCurveQuat
 * Size: 0x0011
 */
export type FInterpCurveQuat = {
};

/**
 * ScriptStruct Core.Object.InterpCurveTwoVectors
 * Size: 0x0011
 */
export type FInterpCurveTwoVectors = {
};

/**
 * ScriptStruct Core.Object.InterpCurveVector
 * Size: 0x0011
 */
export type FInterpCurveVector = {
};

/**
 * ScriptStruct Core.Object.InterpCurveVector2D
 * Size: 0x0011
 */
export type FInterpCurveVector2D = {
};

/**
 * ScriptStruct Core.Object.IntPoint
 * Size: 0x0008
 */
export type FIntPoint = {
  X: number;  // 0x0000 (0x0004) [int32]
  Y: number;  // 0x0004 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.IpAddr
 * Size: 0x0014
 */
export type FIpAddr = {
  AddrA: number;  // 0x0000 (0x0004) [int32]
  AddrB: number;  // 0x0004 (0x0004) [int32]
  AddrC: number;  // 0x0008 (0x0004) [int32]
  AddrD: number;  // 0x000c (0x0004) [int32]
  Port: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.LinearColor
 * Size: 0x0010
 */
export type FLinearColor = {
  R: number;  // 0x0000 (0x0004) [float]
  G: number;  // 0x0004 (0x0004) [float]
  B: number;  // 0x0008 (0x0004) [float]
  A: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.Map_Mirror
 * Size: 0x0050
 */
export type FMap_Mirror = {
};

/**
 * ScriptStruct Core.DistributionFloat.MatineeRawDistributionFloat
 * Size: 0x0030
 * Extends: FRawDistributionFloat
 */
export type FMatineeRawDistributionFloat = FRawDistributionFloat & {
  MatineeValue: number;  // 0x0028 (0x0004) [float]
  bInMatinee: boolean;  // 0x002c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct Core.Object.Matrix
 * Size: 0x0040
 */
export type FMatrix = {
};

/**
 * ScriptStruct Core.Object.MultiMap_Mirror
 * Size: 0x0050
 */
export type FMultiMap_Mirror = {
};

/**
 * ScriptStruct Core.ObjectProvider.ObjectPropertyInjection
 * Size: 0x0010
 */
export type FObjectPropertyInjection = {
};

/**
 * ScriptStruct Core.ObjectProvider.ObjectProviderPendingCallback
 * Size: 0x0020
 */
export type FObjectProviderPendingCallback = {
  Callback: FScriptDelegate;  // 0x0000 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct Core.ObjectProvider.ObjectProviderSubscription
 * Size: 0x0024
 */
export type FObjectProviderSubscription = {
  Callback: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
  bFireOnce: boolean;  // 0x0020 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct Core.Object.OctreeElementId
 * Size: 0x000C
 */
export type FOctreeElementId = {
  ElementIndex: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.PackedNormal
 * Size: 0x0004
 */
export type FPackedNormal = {
};

/**
 * ScriptStruct Core.Object.Plane
 * Size: 0x0010
 * Extends: FVector
 */
export type FPlane = FVector & {
  W: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.Pointer
 * Size: 0x0008
 */
export type FPointer = {
  Dummy: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct Core._Types_Core.ProductHashID
 * Size: 0x0004
 */
export type FProductHashID = {
  Id: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct Core._Types_Core.ProductInstanceID
 * Size: 0x0010
 */
export type FProductInstanceID = {
  UpperBits: bigint;  // 0x0000 (0x0008) [uint64]
  LowerBits: bigint;  // 0x0008 (0x0008) [uint64]
};

/**
 * ScriptStruct Core.Object.Quat
 * Size: 0x0010
 */
export type FQuat = {
  X: number;  // 0x0000 (0x0004) [float]
  Y: number;  // 0x0004 (0x0004) [float]
  Z: number;  // 0x0008 (0x0004) [float]
  W: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.RawDistribution
 * Size: 0x0020
 */
export type FRawDistribution = {
  LookupTableTimeScale: number;  // 0x0018 (0x0004) [float]
  LookupTableStartTime: number;  // 0x001c (0x0004) [float]
};

/**
 * ScriptStruct Core.DistributionFloat.RawDistributionFloat
 * Size: 0x0028
 * Extends: FRawDistribution
 */
export type FRawDistributionFloat = FRawDistribution & {
  Distribution: unknown;  // 0x0020 (0x0008) [unknown]
};

/**
 * ScriptStruct Core.DistributionVector.RawDistributionVector
 * Size: 0x0028
 * Extends: FRawDistribution
 */
export type FRawDistributionVector = FRawDistribution & {
  Distribution: unknown;  // 0x0020 (0x0008) [unknown]
};

/**
 * ScriptStruct Core.Object.RenderCommandFence
 * Size: 0x0004
 */
export type FRenderCommandFence = {
  NumPendingFences: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.RenderCommandFence_Mirror
 * Size: 0x0004
 */
export type FRenderCommandFence_Mirror = {
  NumPendingFences: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.Rotator
 * Size: 0x000C
 */
export type FRotator = {
  Pitch: number;  // 0x0000 (0x0004) [int32]
  Yaw: number;  // 0x0004 (0x0004) [int32]
  Roll: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct Core.RotatorConversions.RotatorDegrees
 * Size: 0x000C
 */
export type FRotatorDegrees = {
  Pitch: number;  // 0x0000 (0x0004) [float]
  Yaw: number;  // 0x0004 (0x0004) [float]
  Roll: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct Core.RotatorConversions.RotatorRadians
 * Size: 0x000C
 */
export type FRotatorRadians = {
  Pitch: number;  // 0x0000 (0x0004) [float]
  Yaw: number;  // 0x0004 (0x0004) [float]
  Roll: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct Core._Types_Core.SceNpId
 * Size: 0x0028
 */
export type FSceNpId = {
  Opt: bigint;  // 0x0018 (0x0008) [uint64]
  Reserved: bigint;  // 0x0020 (0x0008) [uint64]
};

/**
 * ScriptStruct Core._Types_Core.SceNpOnlineId
 * Size: 0x0014
 */
export type FSceNpOnlineId = {
  Data: bigint;  // 0x0000 (0x0010) [uint64]
};

/**
 * ScriptStruct Core.AutomationTest.ScriptWarning
 * Size: 0x0034
 */
export type FScriptWarning = {
  Node: string;  // 0x0000 (0x0010) [FString]
  Message: string;  // 0x0010 (0x0010) [FString]
  StackTrace: string;  // 0x0020 (0x0010) [FString]
  ScriptPosition: number;  // 0x0030 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.Set_Mirror
 * Size: 0x004C
 */
export type FSet_Mirror = {
  InlineHash: number;  // 0x0038 (0x0004) [int32]
  HashSize: number;  // 0x0048 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.SHVector
 * Size: 0x0030
 */
export type FSHVector = {
  V: number;  // 0x0000 (0x0024) [float]
  Padding: number;  // 0x0024 (0x000c) [float]
};

/**
 * ScriptStruct Core.Object.SHVectorRGB
 * Size: 0x0090
 */
export type FSHVectorRGB = {
};

/**
 * ScriptStruct Core.Object.SparseArray_Mirror
 * Size: 0x0038
 */
export type FSparseArray_Mirror = {
  FirstFreeIndex: number;  // 0x0030 (0x0004) [int32]
  NumFreeIndices: number;  // 0x0034 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.TAlphaBlend
 * Size: 0x0015
 */
export type FTAlphaBlend = {
  AlphaIn: number;  // 0x0000 (0x0004) [float]
  AlphaOut: number;  // 0x0004 (0x0004) [float]
  AlphaTarget: number;  // 0x0008 (0x0004) [float]
  BlendTime: number;  // 0x000c (0x0004) [float]
  BlendTimeToGo: number;  // 0x0010 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.ThreadSafeCounter
 * Size: 0x0004
 */
export type FThreadSafeCounter = {
  Value: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.TPOV
 * Size: 0x001C
 */
export type FTPOV = {
  FOV: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.TwoVectors
 * Size: 0x0018
 */
export type FTwoVectors = {
};

/**
 * ScriptStruct Core._Types_Core.UniqueNetId
 * Size: 0x0042
 */
export type FUniqueNetId = {
  Uid: bigint;  // 0x0000 (0x0008) [uint64]
  EpicAccountId: string;  // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct Core.Object.UntypedBulkData_Mirror
 * Size: 0x0054
 */
export type FUntypedBulkData_Mirror = {
  BulkDataFlags: number;  // 0x0008 (0x0004) [int32]
  ElementCount: number;  // 0x000c (0x0004) [int32]
  BulkDataOffsetInFile: bigint;  // 0x0010 (0x0008) [uint64]
  BulkDataSizeOnDisk: number;  // 0x0018 (0x0004) [int32]
  SavedBulkDataFlags: number;  // 0x001c (0x0004) [int32]
  SavedElementCount: number;  // 0x0020 (0x0004) [int32]
  SavedBulkDataOffsetInFile: bigint;  // 0x0028 (0x0008) [uint64]
  SavedBulkDataSizeOnDisk: number;  // 0x0030 (0x0004) [int32]
  LockStatus: number;  // 0x0040 (0x0004) [int32]
  bShouldFreeOnEmpty: number;  // 0x0050 (0x0004) [int32]
};

/**
 * ScriptStruct Core.Object.Vector
 * Size: 0x000C
 */
export type FVector = {
  X: number;  // 0x0000 (0x0004) [float]
  Y: number;  // 0x0004 (0x0004) [float]
  Z: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.Vector2D
 * Size: 0x0008
 */
export type FVector2D = {
  X: number;  // 0x0000 (0x0004) [float]
  Y: number;  // 0x0004 (0x0004) [float]
};

/**
 * ScriptStruct Core.Object.Vector4
 * Size: 0x0010
 */
export type FVector4 = {
  X: number;  // 0x0000 (0x0004) [float]
  Y: number;  // 0x0004 (0x0004) [float]
  Z: number;  // 0x0008 (0x0004) [float]
  W: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct Core._Types_Core.VoiceAudioDevice
 * Size: 0x0024
 */
export type FVoiceAudioDevice = {
  Id: string;  // 0x0000 (0x0010) [FString]
  Name: string;  // 0x0010 (0x0010) [FString]
  bDefault: boolean;  // 0x0020 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct Core._Types_Core.VoiceRoomMemberStatus
 * Size: 0x0004
 */
export type FVoiceRoomMemberStatus = {
  bLocal: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  bSpeaking: boolean;  // 0x0000 (0x0004) [bool : 0x2]
  bSelfMuted: boolean;  // 0x0000 (0x0004) [bool : 0x4]
  bLocalMuted: boolean;  // 0x0000 (0x0004) [bool : 0x8]
  bAdminMuted: boolean;  // 0x0000 (0x0004) [bool : 0x10]
  bBlocked: boolean;  // 0x0000 (0x0004) [bool : 0x20]
};
