/**
 * IpDrv Package - Structs
 * Auto-generated by Stev Peifer
 */

import type { FName, FScriptDelegate } from './Core';
import type { FEmsFile, FTitleFile } from './Engine';

/**
 * ScriptStruct IpDrv.McpIdMappingManager.AddMappingRequest
 * Size: 0x0038
 */
export type FAddMappingRequest = {
  McpId: string;  // 0x0000 (0x0010) [FString]
  ExternalId: string;  // 0x0010 (0x0010) [FString]
  ExternalType: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.AdHocDelegates.AdHocAccessPointInfo
 * Size: 0x0038
 */
export type FAdHocAccessPointInfo = {
  Ipv4Addr: string;  // 0x0000 (0x0010) [FString]
  Username: string;  // 0x0010 (0x0010) [FString]
  AdvertiseData: string;  // 0x0020 (0x0010) [FString]
  ScanResultIndex: number;  // 0x0030 (0x0004) [int32]
  NetworkNodeIndex: number;  // 0x0034 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.AdHocDelegates.AdHocStationInfo
 * Size: 0x0010
 */
export type FAdHocStationInfo = {
  Username: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.OnlineAuthInterfaceImpl.AuthCodeRequest
 * Size: 0x0064
 */
export type FAuthCodeRequest = {
  Callback: FScriptDelegate;  // 0x0048 (0x0018) [FScriptDelegate]
  RequestID: number;  // 0x0060 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.AvatarDownloadMap.AvatarKey
 * Size: 0x0049
 */
export type FAvatarKey = {
};

/**
 * ScriptStruct IpDrv.MeshBeaconClient.ClientBandwidthTestData
 * Size: 0x0014
 */
export type FClientBandwidthTestData = {
  NumBytesToSendTotal: number;  // 0x0004 (0x0004) [int32]
  NumBytesSentTotal: number;  // 0x0008 (0x0004) [int32]
  NumBytesSentLast: number;  // 0x000c (0x0004) [int32]
  ElapsedTestTime: number;  // 0x0010 (0x0004) [float]
};

/**
 * ScriptStruct IpDrv.PartyBeaconHost.ClientBeaconConnection
 * Size: 0x0058
 */
export type FClientBeaconConnection = {
  ElapsedHeartbeatTime: number;  // 0x0048 (0x0004) [float]
};

/**
 * ScriptStruct IpDrv.MeshBeaconHost.ClientConnectionBandwidthTestData
 * Size: 0x002C
 */
export type FClientConnectionBandwidthTestData = {
  BytesTotalNeeded: number;  // 0x0004 (0x0004) [int32]
  BytesReceived: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.MeshBeaconClient.ClientConnectionRequest
 * Size: 0x006C
 */
export type FClientConnectionRequest = {
  bCanHostVs: boolean;  // 0x004c (0x0004) [bool : 0x1]
  GoodHostRatio: number;  // 0x0050 (0x0004) [float]
  MinutesSinceLastTest: number;  // 0x0068 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.MeshBeaconHost.ClientMeshBeaconConnection
 * Size: 0x00B4
 */
export type FClientMeshBeaconConnection = {
  ElapsedHeartbeatTime: number;  // 0x0048 (0x0004) [float]
  bConnectionAccepted: boolean;  // 0x0058 (0x0004) [bool : 0x1]
  bCanHostVs: boolean;  // 0x0094 (0x0004) [bool : 0x1]
  GoodHostRatio: number;  // 0x0098 (0x0004) [float]
  MinutesSinceLastTest: number;  // 0x00b0 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.OnlinePlaylistManager.ConfiguredGameSetting
 * Size: 0x0030
 */
export type FConfiguredGameSetting = {
  GameSettingId: number;  // 0x0000 (0x0004) [int32]
  GameSettingsClassName: string;  // 0x0008 (0x0010) [FString]
  URL: string;  // 0x0018 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.MeshBeacon.ConnectionBandwidthStats
 * Size: 0x000C
 */
export type FConnectionBandwidthStats = {
  UpstreamRate: number;  // 0x0000 (0x0004) [int32]
  DownstreamRate: number;  // 0x0004 (0x0004) [int32]
  RoundtripLatency: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.ImageDecoder.DecodeImageRequest
 * Size: 0x0030
 */
export type FDecodeImageRequest = {
  RequestURL: string;  // 0x0000 (0x0010) [FString]
  OnFinishedCallback: FScriptDelegate;  // 0x0010 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct IpDrv.ImageDecoder.DecodeImageTask
 * Size: 0x0040
 */
export type FDecodeImageTask = {
  RequestURL: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.OnlineEventsInterfaceMcp.EventUploadConfig
 * Size: 0x0020
 */
export type FEventUploadConfig = {
  UploadUrl: string;  // 0x0008 (0x0010) [FString]
  Timeout: number;  // 0x0018 (0x0004) [float]
  bUseCompression: boolean;  // 0x001c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct IpDrv.OnlineTitleFileDownloadBase.FileNameToURLMapping
 * Size: 0x0010
 */
export type FFileNameToURLMapping = {
  Filename: FName;  // 0x0000 (0x0008) [FName]
  UrlMapping: FName;  // 0x0008 (0x0008) [FName]
};

/**
 * ScriptStruct IpDrv.McpUserInventoryManager.InventoryItemRequestState
 * Size: 0x0038
 * Extends: FSaveSlotRequestState
 */
export type FInventoryItemRequestState = FSaveSlotRequestState & {
  ItemID: string;  // 0x0028 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpManagedValueManagerBase.ManagedValue
 * Size: 0x000C
 */
export type FManagedValue = {
  ValueId: FName;  // 0x0000 (0x0008) [FName]
  Value: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpManagedValueManagerBase.ManagedValueSaveSlot
 * Size: 0x0030
 */
export type FManagedValueSaveSlot = {
  OwningMcpId: string;  // 0x0000 (0x0010) [FString]
  SaveSlot: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpClashMobManager.McpChallengeRequest
 * Size: 0x0018
 */
export type FMcpChallengeRequest = {
  UniqueChallengeId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpClashMobManager.McpChallengeUserRequest
 * Size: 0x0050
 */
export type FMcpChallengeUserRequest = {
  UniqueUserId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpClashMobBase.McpClashMobChallengeEvent
 * Size: 0x00E0
 */
export type FMcpClashMobChallengeEvent = {
  unique_challenge_id: string;  // 0x0000 (0x0010) [FString]
  visible_date: string;  // 0x0010 (0x0010) [FString]
  start_date: string;  // 0x0020 (0x0010) [FString]
  end_date: string;  // 0x0030 (0x0010) [FString]
  completed_date: string;  // 0x0040 (0x0010) [FString]
  purge_date: string;  // 0x0050 (0x0010) [FString]
  challenge_type: string;  // 0x0060 (0x0010) [FString]
  num_attempts: number;  // 0x0070 (0x0004) [int32]
  num_successful_attempts: number;  // 0x0074 (0x0004) [int32]
  goal_value: number;  // 0x0078 (0x0004) [int32]
  goal_start_value: number;  // 0x007c (0x0004) [int32]
  goal_current_value: number;  // 0x0080 (0x0004) [int32]
  has_started: boolean;  // 0x0084 (0x0004) [bool : 0x1]
  is_visible: boolean;  // 0x0084 (0x0004) [bool : 0x2]
  has_completed: boolean;  // 0x0084 (0x0004) [bool : 0x4]
  was_successful: boolean;  // 0x0084 (0x0004) [bool : 0x8]
  facebook_likes: number;  // 0x0098 (0x0004) [int32]
  facebook_comments: number;  // 0x009c (0x0004) [int32]
  facebook_like_scaler: number;  // 0x00a0 (0x0004) [float]
  facebook_comment_scaler: number;  // 0x00a4 (0x0004) [float]
  facebook_like_goal_progress: number;  // 0x00a8 (0x0004) [int32]
  facebook_comment_goal_progress: number;  // 0x00ac (0x0004) [int32]
  facebook_id: string;  // 0x00b0 (0x0010) [FString]
  twitter_retweets: number;  // 0x00c0 (0x0004) [int32]
  twitter_retweets_scaler: number;  // 0x00c4 (0x0004) [float]
  twitter_goal_progress: number;  // 0x00c8 (0x0004) [int32]
  twitter_id: string;  // 0x00d0 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpClashMobBase.McpClashMobChallengeFile
 * Size: 0x0059
 */
export type FMcpClashMobChallengeFile = {
  should_keep_post_challenge: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  title_id: string;  // 0x0008 (0x0010) [FString]
  file_name: string;  // 0x0018 (0x0010) [FString]
  dl_name: string;  // 0x0028 (0x0010) [FString]
  hash_code: string;  // 0x0038 (0x0010) [FString]
  Type: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpClashMobBase.McpClashMobChallengeUserStatus
 * Size: 0x008C
 */
export type FMcpClashMobChallengeUserStatus = {
  unique_challenge_id: string;  // 0x0000 (0x0010) [FString]
  unique_user_id: string;  // 0x0010 (0x0010) [FString]
  num_attempts: number;  // 0x0020 (0x0004) [int32]
  num_successful_attempts: number;  // 0x0024 (0x0004) [int32]
  goal_progress: number;  // 0x0028 (0x0004) [int32]
  did_complete: boolean;  // 0x002c (0x0004) [bool : 0x1]
  last_update_time: string;  // 0x0030 (0x0010) [FString]
  user_award_given: number;  // 0x0040 (0x0004) [int32]
  accept_time: string;  // 0x0048 (0x0010) [FString]
  did_preregister: boolean;  // 0x0058 (0x0004) [bool : 0x1]
  facebook_like_time: string;  // 0x0060 (0x0010) [FString]
  enrolled_via_facebook: boolean;  // 0x0070 (0x0004) [bool : 0x1]
  liked_via_facebook: boolean;  // 0x0070 (0x0004) [bool : 0x2]
  commented_via_facebook: boolean;  // 0x0070 (0x0004) [bool : 0x4]
  twitter_retweet_time: string;  // 0x0078 (0x0010) [FString]
  enrolled_via_twitter: boolean;  // 0x0088 (0x0004) [bool : 0x1]
  retweeted: boolean;  // 0x0088 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct IpDrv.McpClashMobBase.McpClashMobPushNotification
 * Size: 0x0044
 */
export type FMcpClashMobPushNotification = {
  badge_type: string;  // 0x0010 (0x0010) [FString]
  Sound: string;  // 0x0020 (0x0010) [FString]
  Message: string;  // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpClashMobBase.McpClashMobPushNotificationParams
 * Size: 0x0004
 */
export type FMcpClashMobPushNotificationParams = {
  bah: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpMessageManager.McpCompressMessageRequest
 * Size: 0x0038
 */
export type FMcpCompressMessageRequest = {
  OutCompressedSize: number;  // 0x0020 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpGroupsBase.McpGroup
 * Size: 0x0048
 */
export type FMcpGroup = {
  OwnerId: string;  // 0x0000 (0x0010) [FString]
  GroupId: string;  // 0x0010 (0x0010) [FString]
  GroupName: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpGroupsBase.McpGroupList
 * Size: 0x0020
 */
export type FMcpGroupList = {
  RequesterId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpGroupsBase.McpGroupMember
 * Size: 0x0011
 */
export type FMcpGroupMember = {
  MemberId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpIdMappingBase.McpIdMapping
 * Size: 0x0030
 */
export type FMcpIdMapping = {
  McpId: string;  // 0x0000 (0x0010) [FString]
  ExternalId: string;  // 0x0010 (0x0010) [FString]
  ExternalType: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpUserInventoryBase.McpInventoryItem
 * Size: 0x0050
 */
export type FMcpInventoryItem = {
  InstanceItemId: string;  // 0x0000 (0x0010) [FString]
  GlobalItemId: string;  // 0x0010 (0x0010) [FString]
  Quantity: number;  // 0x0020 (0x0004) [int32]
  QuantityIAP: number;  // 0x0024 (0x0004) [int32]
  Scalar: number;  // 0x0028 (0x0004) [float]
  LastUpdateTime: string;  // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpUserInventoryBase.McpInventoryItemAttribute
 * Size: 0x0014
 */
export type FMcpInventoryItemAttribute = {
  AttributeId: string;  // 0x0000 (0x0010) [FString]
  Value: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpUserInventoryBase.McpInventoryItemContainer
 * Size: 0x0014
 */
export type FMcpInventoryItemContainer = {
  GlobalItemId: string;  // 0x0000 (0x0010) [FString]
  Quantity: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpUserInventoryBase.McpInventorySaveSlot
 * Size: 0x0030
 */
export type FMcpInventorySaveSlot = {
  OwningMcpId: string;  // 0x0000 (0x0010) [FString]
  SaveSlotId: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpMessageBase.McpMessage
 * Size: 0x0061
 */
export type FMcpMessage = {
  MessageId: string;  // 0x0000 (0x0010) [FString]
  ToUniqueUserId: string;  // 0x0010 (0x0010) [FString]
  FromUniqueUserId: string;  // 0x0020 (0x0010) [FString]
  FromFriendlyName: string;  // 0x0030 (0x0010) [FString]
  MessageType: string;  // 0x0040 (0x0010) [FString]
  ValidUntil: string;  // 0x0050 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpMessageBase.McpMessageContents
 * Size: 0x0020
 */
export type FMcpMessageContents = {
  MessageId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpMessageBase.McpMessageList
 * Size: 0x0020
 */
export type FMcpMessageList = {
  ToUniqueUserId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpMessageManager.McpUncompressMessageRequest
 * Size: 0x0040
 */
export type FMcpUncompressMessageRequest = {
  MessageId: string;  // 0x0000 (0x0010) [FString]
  OutUncompressedSize: number;  // 0x0030 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpUserCloudFileDownload.McpUserCloudFileInfo
 * Size: 0x0068
 * Extends: FEmsFile
 */
export type FMcpUserCloudFileInfo = FEmsFile & {
  CreationDate: string;  // 0x0038 (0x0010) [FString]
  LastUpdateDate: string;  // 0x0048 (0x0010) [FString]
  CompressionType: string;  // 0x0058 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpUserCloudFileDownload.McpUserCloudFilesEntry
 * Size: 0x0038
 */
export type FMcpUserCloudFilesEntry = {
  UserId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpUserManagerBase.McpUserStatus
 * Size: 0x0068
 */
export type FMcpUserStatus = {
  McpId: string;  // 0x0000 (0x0010) [FString]
  SecretKey: string;  // 0x0010 (0x0010) [FString]
  Ticket: string;  // 0x0020 (0x0010) [FString]
  UDID: string;  // 0x0030 (0x0010) [FString]
  RegisteredDate: string;  // 0x0040 (0x0010) [FString]
  LastActiveDate: string;  // 0x0050 (0x0010) [FString]
  DaysInactive: number;  // 0x0060 (0x0004) [int32]
  bIsBanned: boolean;  // 0x0064 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct IpDrv.OnlineNewsInterfaceMcp.NewsCacheEntry
 * Size: 0x0038
 */
export type FNewsCacheEntry = {
  NewsUrl: string;  // 0x0000 (0x0010) [FString]
  NewsItem: string;  // 0x0018 (0x0010) [FString]
  Timeout: number;  // 0x0028 (0x0004) [float]
  bIsUnicode: boolean;  // 0x002c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct IpDrv.OnlineImageDownloaderWeb.OnlineImageDownload
 * Size: 0x0040
 */
export type FOnlineImageDownload = {
  URL: string;  // 0x0000 (0x0010) [FString]
  DecodedCallbacks: FScriptDelegate;  // 0x0028 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct IpDrv.PartyBeacon.PartyReservation
 * Size: 0x0060
 */
export type FPartyReservation = {
  TeamNum: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.MeshBeacon.PlayerMember
 * Size: 0x0050
 */
export type FPlayerMember = {
  TeamNum: number;  // 0x0000 (0x0004) [int32]
  Skill: number;  // 0x0004 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.PartyBeacon.PlayerReservation
 * Size: 0x0064
 */
export type FPlayerReservation = {
  Skill: number;  // 0x0048 (0x0004) [int32]
  XpLevel: number;  // 0x004c (0x0004) [int32]
  ElapsedSessionTime: number;  // 0x0060 (0x0004) [float]
};

/**
 * ScriptStruct IpDrv.OnlinePlaylistManager.Playlist
 * Size: 0x0080
 */
export type FPlaylist = {
  PlaylistId: number;  // 0x0010 (0x0004) [int32]
  LoadBalanceId: number;  // 0x0014 (0x0004) [int32]
  LocalizationString: string;  // 0x0018 (0x0010) [FString]
  TeamSize: number;  // 0x0038 (0x0004) [int32]
  TeamCount: number;  // 0x003c (0x0004) [int32]
  MaxPartySize: number;  // 0x0040 (0x0004) [int32]
  Name: string;  // 0x0048 (0x0010) [FString]
  URL: string;  // 0x0058 (0x0010) [FString]
  MatchType: number;  // 0x0068 (0x0004) [int32]
  bDisableDedicatedServerSearches: boolean;  // 0x006c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct IpDrv.OnlinePlaylistManager.PlaylistPopulation
 * Size: 0x000C
 */
export type FPlaylistPopulation = {
  PlaylistId: number;  // 0x0000 (0x0004) [int32]
  WorldwideTotal: number;  // 0x0004 (0x0004) [int32]
  RegionTotal: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct IpDrv.McpIdMappingManager.QueryMappingRequest
 * Size: 0x0018
 */
export type FQueryMappingRequest = {
  ExternalType: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.OnlineSubsystemCommonImpl.SanitizeCallbackData
 * Size: 0x0030
 */
export type FSanitizeCallbackData = {
  Id: number;  // 0x0000 (0x0004) [int32]
  Callback: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
  Comment: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpManagedValueManager.SaveSlotRequestState
 * Size: 0x0028
 */
export type FSaveSlotRequestState = {
  McpId: string;  // 0x0000 (0x0010) [FString]
  SaveSlot: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpUserInventoryManager.SaveSlotRequestState
 * Size: 0x0028
 */
export type FSaveSlotRequestState = {
  McpId: string;  // 0x0000 (0x0010) [FString]
  SaveSlotId: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.TitleFileDownloadCache.TitleFileCacheEntry
 * Size: 0x0058
 * Extends: FTitleFile
 */
export type FTitleFileCacheEntry = FTitleFile & {
  LogicalName: string;  // 0x0028 (0x0010) [FString]
  Hash: string;  // 0x0038 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.OnlineTitleFileDownloadMcp.TitleFileMcp
 * Size: 0x0030
 * Extends: FTitleFile
 */
export type FTitleFileMcp = FTitleFile & {
};

/**
 * ScriptStruct IpDrv.OnlineTitleFileDownloadBase.TitleFileWeb
 * Size: 0x0041
 * Extends: FTitleFile
 */
export type FTitleFileWeb = FTitleFile & {
  StringData: string;  // 0x0028 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpUserManager.UserRequest
 * Size: 0x0018
 */
export type FUserRequest = {
  McpId: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct IpDrv.McpManagedValueManager.ValueRequestState
 * Size: 0x0030
 * Extends: FSaveSlotRequestState
 */
export type FValueRequestState = FSaveSlotRequestState & {
  ValueId: FName;  // 0x0028 (0x0008) [FName]
};
