/**
 * ProjectX Package - Structs
 * Auto-generated by Stev Peifer
 */

import type { FName, FScriptDelegate } from './Core';

/**
 * ScriptStruct ProjectX.EOS_AccountSummaryResponse.AccountSettings
 * Size: 0x0010
 */
export type FAccountSettings = {
};

/**
 * ScriptStruct ProjectX._Types_X.ActiveServerData
 * Size: 0x00A0
 */
export type FActiveServerData = {
  PingURL: string;  // 0x0070 (0x0010) [FString]
  GameURL: string;  // 0x0080 (0x0010) [FString]
  JoinCredentials: string;  // 0x0090 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.ParameterDispenser_X.ActorParamPair
 * Size: 0x0010
 */
export type FActorParamPair = {
  Key: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.AnimateParametersComponent_X.AnimatedFloatParam
 * Size: 0x0020
 * Extends: FAnimatedParam
 */
export type FAnimatedFloatParam = FAnimatedParam & {
};

/**
 * ScriptStruct ProjectX.AnimateParametersComponent_X.AnimatedLinearColorParam
 * Size: 0x0020
 * Extends: FAnimatedParam
 */
export type FAnimatedLinearColorParam = FAnimatedParam & {
};

/**
 * ScriptStruct ProjectX.AnimateParametersComponent_X.AnimatedParam
 * Size: 0x0008
 */
export type FAnimatedParam = {
  ParamName: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.AnimateParametersComponent_X.AnimatedVectorParam
 * Size: 0x0020
 * Extends: FAnimatedParam
 */
export type FAnimatedVectorParam = FAnimatedParam & {
};

/**
 * ScriptStruct ProjectX.FXActor_X.AttachToParameterWithUnlockAxes
 * Size: 0x0009
 */
export type FAttachToParameterWithUnlockAxes = {
  Parameter: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.ReservationBeacon_X.BeaconMessageHandler
 * Size: 0x0018
 */
export type FBeaconMessageHandler = {
};

/**
 * ScriptStruct ProjectX._Types_X.BindingAction
 * Size: 0x0038
 */
export type FBindingAction = {
  Action: FName;  // 0x0000 (0x0008) [FName]
  Category: FName;  // 0x0008 (0x0008) [FName]
  Axis: FName;  // 0x0010 (0x0008) [FName]
  Command: string;  // 0x0020 (0x0010) [FString]
  bDisableRemapping: boolean;  // 0x0030 (0x0004) [bool : 0x1]
  Priority: number;  // 0x0034 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.BumpAngleCheckConfig
 * Size: 0x0014
 */
export type FBumpAngleCheckConfig = {
  bEnabled: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  BumpAngleYaw: number;  // 0x0004 (0x0004) [float]
  BumpAnglePitch: number;  // 0x0008 (0x0004) [float]
  DemolishAngleYaw: number;  // 0x000c (0x0004) [float]
  DemolishAnglePitch: number;  // 0x0010 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX._Types_X.BumpAngleCurveCheckConfig
 * Size: 0x0068
 */
export type FBumpAngleCurveCheckConfig = {
  bEnabled: boolean;  // 0x0000 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.CabinedModeResponse.CabinedModeData
 * Size: 0x0028
 */
export type FCabinedModeData = {
  cabinedMode: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  AccountId: string;  // 0x0008 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.WebCache_X.CachedDataRequest
 * Size: 0x0050
 */
export type FCachedDataRequest = {
  URL: string;  // 0x0000 (0x0010) [FString]
  Path: string;  // 0x0010 (0x0010) [FString]
  Headers: unknown;  // 0x0020 (0x0008) [unknown]
  bZipResponse: boolean;  // 0x0030 (0x0004) [bool : 0x1]
  Callback: FScriptDelegate;  // 0x0038 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.OnlineGameLeaderboards_X.CachedLeaderboardData
 * Size: 0x0020
 */
export type FCachedLeaderboardData = {
  LeaderboardId: FName;  // 0x0000 (0x0008) [FName]
  LastLeaderboardSyncTime: bigint;  // 0x0018 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX._Types_X.CachedRegionPing
 * Size: 0x000C
 */
export type FCachedRegionPing = {
  Name: FName;  // 0x0000 (0x0008) [FName]
  Ping: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.LocalCache_X.CacheExportCallbackData
 * Size: 0x0020
 */
export type FCacheExportCallbackData = {
  Callback: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.LocalCache_X.CacheExportTask
 * Size: 0x0030
 * Extends: FCacheIOTaskBase
 */
export type FCacheExportTask = FCacheIOTaskBase & {
};

/**
 * ScriptStruct ProjectX.LocalCache_X.CacheImportCallbackData
 * Size: 0x0020
 */
export type FCacheImportCallbackData = {
  Callback: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.LocalCache_X.CacheImportTask
 * Size: 0x0030
 * Extends: FCacheIOTaskBase
 */
export type FCacheImportTask = FCacheIOTaskBase & {
};

/**
 * ScriptStruct ProjectX.LocalCache_X.CacheIOTaskBase
 * Size: 0x0030
 */
export type FCacheIOTaskBase = {
  Path: string;  // 0x0018 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.Camera_X.CameraKnockBase
 * Size: 0x0010
 */
export type FCameraKnockBase = {
  BlendInTime: number;  // 0x0000 (0x0004) [float]
  BlendOutTime: number;  // 0x0004 (0x0004) [float]
  Falloff: number;  // 0x0008 (0x0004) [float]
  Time: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.Camera_X.CameraOrientation
 * Size: 0x002C
 */
export type FCameraOrientation = {
  Distance: number;  // 0x0018 (0x0004) [float]
  FOV: number;  // 0x001c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.CameraStateBlender_X.CameraTransition
 * Size: 0x004C
 */
export type FCameraTransition = {
  RemainingTime: number;  // 0x0018 (0x0004) [float]
  bStarted: boolean;  // 0x0048 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX._Types_X.CarInteractionConfig
 * Size: 0x0104
 */
export type FCarInteractionConfig = {
  PushFactor: number;  // 0x0000 (0x0004) [float]
  BumpInterval: number;  // 0x0050 (0x0004) [float]
  bCheckImpactNormal: boolean;  // 0x00f8 (0x0004) [bool : 0x1]
  ImpactNormalDotProductDemo: number;  // 0x00fc (0x0004) [float]
  ImpactNormalDotProductBump: number;  // 0x0100 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.PresetMutators_X.CategorySettingPair
 * Size: 0x0014
 */
export type FCategorySettingPair = {
  Category: FName;  // 0x0000 (0x0008) [FName]
  Setting: FName;  // 0x0008 (0x0008) [FName]
  bLockSetting: boolean;  // 0x0010 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.EpicConfig_X.ChatPermissionPair
 * Size: 0x0011
 */
export type FChatPermissionPair = {
  PermissionLabel: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPC_CheckReplacementDedicatedServer_X.CheckReplacementDedicatedServerData
 * Size: 0x0034
 */
export type FCheckReplacementDedicatedServerData = {
  ServerId: string;  // 0x0000 (0x0010) [FString]
  IP: string;  // 0x0010 (0x0010) [FString]
  Host: string;  // 0x0020 (0x0010) [FString]
  Port: number;  // 0x0030 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.CheckReservationResponse
 * Size: 0x007C
 */
export type FCheckReservationResponse = {
  IP: string;  // 0x0000 (0x0010) [FString]
  ServerName: string;  // 0x0010 (0x0010) [FString]
  Playlist: number;  // 0x0020 (0x0004) [int32]
  Region: string;  // 0x0028 (0x0010) [FString]
  Host: string;  // 0x0038 (0x0010) [FString]
  Port: number;  // 0x0048 (0x0004) [int32]
  ReservationID: string;  // 0x0050 (0x0010) [FString]
  DSConnectToken: string;  // 0x0060 (0x0010) [FString]
  IsServerKey: boolean;  // 0x0078 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.RPC_GetClubStats_X.ClubCareerStats
 * Size: 0x0078
 */
export type FClubCareerStats = {
  MatchPlayed: number;  // 0x0000 (0x0004) [int32]
  Win: number;  // 0x0004 (0x0004) [int32]
  TimePlayed: bigint;  // 0x0008 (0x0008) [uint64]
  Goal: number;  // 0x0010 (0x0004) [int32]
  AerialGoal: number;  // 0x0014 (0x0004) [int32]
  LongGoal: number;  // 0x0018 (0x0004) [int32]
  BackwardsGoal: number;  // 0x001c (0x0004) [int32]
  OvertimeGoal: number;  // 0x0020 (0x0004) [int32]
  TurtleGoal: number;  // 0x0024 (0x0004) [int32]
  Assist: number;  // 0x0028 (0x0004) [int32]
  Playmaker: number;  // 0x002c (0x0004) [int32]
  Save: number;  // 0x0030 (0x0004) [int32]
  EpicSave: number;  // 0x0034 (0x0004) [int32]
  Savior: number;  // 0x0038 (0x0004) [int32]
  Shot: number;  // 0x003c (0x0004) [int32]
  Center: number;  // 0x0040 (0x0004) [int32]
  Clear: number;  // 0x0044 (0x0004) [int32]
  AerialHit: number;  // 0x0048 (0x0004) [int32]
  BicycleHit: number;  // 0x004c (0x0004) [int32]
  JuggleHit: number;  // 0x0050 (0x0004) [int32]
  Demolish: number;  // 0x0054 (0x0004) [int32]
  Demolition: number;  // 0x0058 (0x0004) [int32]
  FirstTouch: number;  // 0x005c (0x0004) [int32]
  PoolShot: number;  // 0x0060 (0x0004) [int32]
  LowFive: number;  // 0x0064 (0x0004) [int32]
  HighFive: number;  // 0x0068 (0x0004) [int32]
  BreakoutDamage: number;  // 0x006c (0x0004) [int32]
  BreakoutDamageLarge: number;  // 0x0070 (0x0004) [int32]
  HoopsSwishGoal: number;  // 0x0074 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.ClubColorSet
 * Size: 0x0008
 */
export type FClubColorSet = {
  bTeamColorSet: boolean;  // 0x0004 (0x0004) [bool : 0x1]
  bCustomColorSet: boolean;  // 0x0004 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX._Types_X.ClubMember
 * Size: 0x00B1
 */
export type FClubMember = {
  PlayerName: string;  // 0x0090 (0x0010) [FString]
  EpicPlayerName: string;  // 0x00a0 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.ClubReplicationInfo
 * Size: 0x0043
 */
export type FClubReplicationInfo = {
  ClubID: bigint;  // 0x0000 (0x0008) [uint64]
  bVerified: boolean;  // 0x0008 (0x0004) [bool : 0x1]
  EquippedTitle: FName;  // 0x000c (0x0008) [FName]
  ClubName: string;  // 0x0018 (0x0010) [FString]
  ClubTag: string;  // 0x0028 (0x0010) [FString]
  PrimaryColor: number;  // 0x0038 (0x0004) [int32]
  AccentColor: number;  // 0x003c (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.RPC_ClubsRecordStats_X.ClubStatRecord
 * Size: 0x0088
 */
export type FClubStatRecord = {
  ClubID: number;  // 0x0000 (0x0004) [int32]
  Win: boolean;  // 0x0004 (0x0004) [bool : 0x1]
  TimePlayed: number;  // 0x0008 (0x0004) [int32]
  Goal: number;  // 0x000c (0x0004) [int32]
  AerialGoal: number;  // 0x0010 (0x0004) [int32]
  LongGoal: number;  // 0x0014 (0x0004) [int32]
  BackwardsGoal: number;  // 0x0018 (0x0004) [int32]
  OvertimeGoal: number;  // 0x001c (0x0004) [int32]
  TurtleGoal: number;  // 0x0020 (0x0004) [int32]
  Assist: number;  // 0x0024 (0x0004) [int32]
  Playmaker: number;  // 0x0028 (0x0004) [int32]
  Save: number;  // 0x002c (0x0004) [int32]
  EpicSave: number;  // 0x0030 (0x0004) [int32]
  Savior: number;  // 0x0034 (0x0004) [int32]
  Shot: number;  // 0x0038 (0x0004) [int32]
  Center: number;  // 0x003c (0x0004) [int32]
  Clear: number;  // 0x0040 (0x0004) [int32]
  AerialHit: number;  // 0x0044 (0x0004) [int32]
  BicycleHit: number;  // 0x0048 (0x0004) [int32]
  JuggleHit: number;  // 0x004c (0x0004) [int32]
  Demolish: number;  // 0x0050 (0x0004) [int32]
  Demolition: number;  // 0x0054 (0x0004) [int32]
  FirstTouch: number;  // 0x0058 (0x0004) [int32]
  PoolShot: number;  // 0x005c (0x0004) [int32]
  LowFive: number;  // 0x0060 (0x0004) [int32]
  HighFive: number;  // 0x0064 (0x0004) [int32]
  BreakoutDamage: number;  // 0x0068 (0x0004) [int32]
  BreakoutDamageLarge: number;  // 0x006c (0x0004) [int32]
  HoopsSwishGoal: number;  // 0x0070 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.ParameterDispenser_X.ColorParamPair
 * Size: 0x0018
 */
export type FColorParamPair = {
  Key: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.ColorPalette_X.ColorPosition
 * Size: 0x0008
 */
export type FColorPosition = {
  Row: number;  // 0x0000 (0x0004) [int32]
  Column: number;  // 0x0004 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.ExplosionHitHandler_X.ContactInformation
 * Size: 0x001C
 */
export type FContactInformation = {
  ContactTime: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.ContentConfig_X.ContentPair
 * Size: 0x0020
 */
export type FContentPair = {
  KeyName: FName;  // 0x0000 (0x0008) [FName]
  Content: string;  // 0x0008 (0x0010) [FString]
  bUnreleased: boolean;  // 0x001c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.SystemMetrics_X.CpuMetrics
 * Size: 0x0040
 */
export type FCpuMetrics = {
  Type: string;  // 0x0000 (0x0010) [FString]
  Desc: string;  // 0x0010 (0x0010) [FString]
  Cores: string;  // 0x0020 (0x0010) [FString]
  Threads: string;  // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.CrossplayGroup
 * Size: 0x0010
 */
export type FCrossplayGroup = {
};

/**
 * ScriptStruct ProjectX._Types_X.CustomMatchSettings
 * Size: 0x0088
 */
export type FCustomMatchSettings = {
  GameTags: string;  // 0x0000 (0x0010) [FString]
  MapName: FName;  // 0x0010 (0x0008) [FName]
  MaxPlayerCount: number;  // 0x001c (0x0004) [int32]
  ServerName: string;  // 0x0020 (0x0010) [FString]
  Password: string;  // 0x0030 (0x0010) [FString]
  bPublic: boolean;  // 0x0040 (0x0004) [bool : 0x1]
  bClubServer: boolean;  // 0x0040 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX._Types_X.CustomMatchTeamSettings
 * Size: 0x001C
 */
export type FCustomMatchTeamSettings = {
  Name: string;  // 0x0000 (0x0010) [FString]
  GameScore: number;  // 0x0018 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.DDoSService_X.DDoSServicePayloadStruct
 * Size: 0x0038
 */
export type FDDoSServicePayloadStruct = {
  Enabled: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  Port: string;  // 0x0008 (0x0010) [FString]
  iid: string;  // 0x0018 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.GFxEngine_X.DirtyObject
 * Size: 0x0014
 */
export type FDirtyObject = {
  Index: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.DownloadedImage
 * Size: 0x0018
 */
export type FDownloadedImage = {
  URL: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.OnlineGameMatchmaking_X.DSRegionInfo
 * Size: 0x0014
 */
export type FDSRegionInfo = {
  Name: string;  // 0x0000 (0x0010) [FString]
  Ping: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.EngineShare_X.DynamicallyLoadedPackage
 * Size: 0x0020
 */
export type FDynamicallyLoadedPackage = {
  Tag: string;  // 0x0000 (0x0010) [FString]
  PackageName: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.EffectsMap_X.EffectsMapping
 * Size: 0x0010
 */
export type FEffectsMapping = {
};

/**
 * ScriptStruct ProjectX.EOS_GetAccountsResponse.EOSAccountInfo
 * Size: 0x0038
 */
export type FEOSAccountInfo = {
  AccountId: string;  // 0x0000 (0x0010) [FString]
  Created: string;  // 0x0010 (0x0010) [FString]
  Favorite: boolean;  // 0x0020 (0x0004) [bool : 0x1]
  NickName: string;  // 0x0028 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.OnlinePlayerFriends_X.EpicSocialTaskData
 * Size: 0x0060
 */
export type FEpicSocialTaskData = {
  OnCompleteCallback: FScriptDelegate;  // 0x0048 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.EpochTimerTick_X.EpochTimer
 * Size: 0x0020
 */
export type FEpochTimer = {
  Callback: FScriptDelegate;  // 0x0000 (0x0018) [FScriptDelegate]
  EpochTime: bigint;  // 0x0018 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX.FakeData_X.FakeData1
 * Size: 0x0035
 */
export type FFakeData1 = {
  string1: string;  // 0x0000 (0x0010) [FString]
  name1: FName;  // 0x0010 (0x0008) [FName]
  bool1: boolean;  // 0x0018 (0x0004) [bool : 0x1]
  qword1: bigint;  // 0x0020 (0x0008) [uint64]
  float1: number;  // 0x0028 (0x0004) [float]
  int1: number;  // 0x0030 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.FakeData_X.FakeData2
 * Size: 0x0090
 */
export type FFakeData2 = {
  string1: string;  // 0x0038 (0x0010) [FString]
  name1: FName;  // 0x0048 (0x0008) [FName]
  bool1: boolean;  // 0x0050 (0x0004) [bool : 0x1]
  qword1: bigint;  // 0x0058 (0x0008) [uint64]
  float1: number;  // 0x0060 (0x0004) [float]
  int1: number;  // 0x0068 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.FakeData_X.FakeData3
 * Size: 0x0130
 */
export type FFakeData3 = {
  string1: string;  // 0x0010 (0x0010) [FString]
  name1: FName;  // 0x0058 (0x0008) [FName]
  bool1: boolean;  // 0x0080 (0x0004) [bool : 0x1]
  qword1: bigint;  // 0x0088 (0x0008) [uint64]
  float1: number;  // 0x0090 (0x0004) [float]
  int1: number;  // 0x0098 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.FakeData_X.FakeData4
 * Size: 0x011D
 */
export type FFakeData4 = {
  string1: string;  // 0x00e8 (0x0010) [FString]
  name1: FName;  // 0x00f8 (0x0008) [FName]
  bool1: boolean;  // 0x0100 (0x0004) [bool : 0x1]
  qword1: bigint;  // 0x0108 (0x0008) [uint64]
  float1: number;  // 0x0110 (0x0004) [float]
  int1: number;  // 0x0118 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.ParameterDispenser_X.FloatParamPair
 * Size: 0x000C
 */
export type FFloatParamPair = {
  Key: FName;  // 0x0000 (0x0008) [FName]
  Value: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.FXActor_X.FXActorEventCheck
 * Size: 0x000C
 */
export type FFXActorEventCheck = {
  bHasTicked: boolean;  // 0x0008 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.FXActor_X.FXAttachment
 * Size: 0x012C
 */
export type FFXAttachment = {
  Name: FName;  // 0x0000 (0x0008) [FName]
  SkeletalMeshAttachName: FName;  // 0x0008 (0x0008) [FName]
  SocketOrBoneName: FName;  // 0x0010 (0x0008) [FName]
  AttachToParameter: FName;  // 0x0018 (0x0008) [FName]
  AttachDelay: number;  // 0x0020 (0x0004) [float]
  DetachDelay: number;  // 0x0024 (0x0004) [float]
  LifeTime: number;  // 0x0028 (0x0004) [float]
  Component: unknown;  // 0x0030 (0x0008) [unknown]
  bCreateDuplicates: boolean;  // 0x00b0 (0x0004) [bool : 0x1]
  bWantsAttachment: boolean;  // 0x00b0 (0x0004) [bool : 0x2]
  bInitializedTraits: boolean;  // 0x00b0 (0x0004) [bool : 0x4]
  bWarnedMissingSocket: boolean;  // 0x00b0 (0x0004) [bool : 0x8]
  bExistingComponent: boolean;  // 0x00b0 (0x0004) [bool : 0x10]
  bExistingAttachment: boolean;  // 0x00b0 (0x0004) [bool : 0x20]
  AttachedTime: number;  // 0x00b4 (0x0004) [float]
  WantsAttachmentChangeTime: number;  // 0x00bc (0x0004) [float]
  AttachedToMesh: unknown;  // 0x00c0 (0x0008) [unknown]
  BoneIndex: number;  // 0x0110 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.FXActor_X.FXEventSubscription
 * Size: 0x0038
 */
export type FFXEventSubscription = {
  OnPushed: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
  OnPopped: FScriptDelegate;  // 0x0020 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.PlayerInput_X.GamepadDeadzoneSettings
 * Size: 0x0010
 */
export type FGamepadDeadzoneSettings = {
  Key: FName;  // 0x0004 (0x0008) [FName]
  Deadzone: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.GameSettingConfig_X.GameSettingHidingOverride
 * Size: 0x000C
 */
export type FGameSettingHidingOverride = {
  SettingName: FName;  // 0x0000 (0x0008) [FName]
  bHidden: boolean;  // 0x0008 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.RPC_GetGameServerPingList2_X.GetGameServerPingListData
 * Size: 0x0058
 */
export type FGetGameServerPingListData = {
  Region: string;  // 0x0000 (0x0010) [FString]
  IP: string;  // 0x0010 (0x0010) [FString]
  Host: string;  // 0x0020 (0x0010) [FString]
  Port: number;  // 0x0030 (0x0004) [int32]
  Address: string;  // 0x0038 (0x0010) [FString]
  SubRegion: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPC_GetGameServerPingList_X.GetGameServerPingListData_Deprecated
 * Size: 0x0048
 */
export type FGetGameServerPingListData_Deprecated = {
  Region: string;  // 0x0000 (0x0010) [FString]
  IP: string;  // 0x0010 (0x0010) [FString]
  Host: string;  // 0x0020 (0x0010) [FString]
  Port: number;  // 0x0030 (0x0004) [int32]
  Address: string;  // 0x0038 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPC_GetGenericDataAll_X.GetGenericDataAllData
 * Size: 0x0018
 */
export type FGetGenericDataAllData = {
  DataKey: FName;  // 0x0000 (0x0008) [FName]
  DataValue: string;  // 0x0008 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPC_GetLeaderboardBase_X.GetLeaderboardBaseData
 * Size: 0x0060
 */
export type FGetLeaderboardBaseData = {
  PlayerName: string;  // 0x0000 (0x0010) [FString]
  Value: number;  // 0x0058 (0x0004) [int32]
  MMR: number;  // 0x005c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.RPC_GetLeaderboardBase_X.GetLeaderboardPlatformBaseData
 * Size: 0x0020
 */
export type FGetLeaderboardPlatformBaseData = {
  Platform: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPC_GetLeaderboardRankForUsersBase_X.GetLeaderboardRankForUserData
 * Size: 0x0060
 */
export type FGetLeaderboardRankForUserData = {
  PlayerName: string;  // 0x0000 (0x0010) [FString]
  Value: number;  // 0x0058 (0x0004) [int32]
  MMR: number;  // 0x005c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.RPC_PlayerStorageGet_X.GetPlayerStorageRequestItem
 * Size: 0x0018
 */
export type FGetPlayerStorageRequestItem = {
  Category: FName;  // 0x0000 (0x0008) [FName]
  Tick: number;  // 0x0008 (0x0004) [int32]
  Checksum: number;  // 0x000c (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.RPC_GetPopulation_X.GetPopulationData
 * Size: 0x0008
 */
export type FGetPopulationData = {
  Playlist: number;  // 0x0000 (0x0004) [int32]
  PlayerCount: number;  // 0x0004 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.GFxBlurRect
 * Size: 0x0020
 */
export type FGFxBlurRect = {
  RectID: string;  // 0x0000 (0x0010) [FString]
  TopLeftX: number;  // 0x0010 (0x0004) [float]
  TopLeftY: number;  // 0x0014 (0x0004) [float]
  BottomRightX: number;  // 0x0018 (0x0004) [float]
  BottomRightY: number;  // 0x001c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.GFxDataStore_X.GFxDataStoreColumn
 * Size: 0x000C
 */
export type FGFxDataStoreColumn = {
  Name: FName;  // 0x0004 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.GFxDataStore_X.GFxDataStoreRow
 * Size: 0x0018
 */
export type FGFxDataStoreRow = {
};

/**
 * ScriptStruct ProjectX.GFxDataStore_X.GFxDataStoreTable
 * Size: 0x0080
 */
export type FGFxDataStoreTable = {
  Name: FName;  // 0x0000 (0x0008) [FName]
  bLevelTransitionPersistent: boolean;  // 0x0028 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.GFxDataStore_X.GFxDirtyRow
 * Size: 0x0018
 */
export type FGFxDirtyRow = {
  RowNum: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.GFxDataStore_X.GFxDirtyTable
 * Size: 0x0018
 */
export type FGFxDirtyTable = {
  Name: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX._Types_X.HonorDuelChallenge
 * Size: 0x0090
 */
export type FHonorDuelChallenge = {
};

/**
 * ScriptStruct ProjectX._Types_X.HTTPRequestCapturedParam
 * Size: 0x0020
 */
export type FHTTPRequestCapturedParam = {
  Name: string;  // 0x0000 (0x0010) [FString]
  Value: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.IntVector3
 * Size: 0x000C
 */
export type FIntVector3 = {
  X: number;  // 0x0000 (0x0004) [int32]
  Y: number;  // 0x0004 (0x0004) [int32]
  Z: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.JoinMatchSettings
 * Size: 0x0020
 */
export type FJoinMatchSettings = {
  PlaylistId: number;  // 0x0004 (0x0004) [int32]
  bFriendJoin: boolean;  // 0x0008 (0x0004) [bool : 0x1]
  bMigration: boolean;  // 0x0008 (0x0004) [bool : 0x2]
  bRankedReconnect: boolean;  // 0x0008 (0x0004) [bool : 0x4]
  Password: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.PlayerInput_X.KeyboardAxisBlendSettings
 * Size: 0x000C
 */
export type FKeyboardAxisBlendSettings = {
  Axis: FName;  // 0x0000 (0x0008) [FName]
  BlendTime: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.OnlineGameLeaderboards_X.LeaderboardData
 * Size: 0x0080
 */
export type FLeaderboardData = {
  UnSanitizedPlayerName: string;  // 0x0048 (0x0010) [FString]
  PlayerName: string;  // 0x0058 (0x0010) [FString]
  bPsyNetUser: boolean;  // 0x0068 (0x0004) [bool : 0x1]
  Rank: number;  // 0x006c (0x0004) [int32]
  Value: number;  // 0x0070 (0x0004) [int32]
  MMR: number;  // 0x0074 (0x0004) [float]
  Division: number;  // 0x0078 (0x0004) [int32]
  bIsPrimaryPlayer: boolean;  // 0x007c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.LensFlareComponent_X.LensFlareFloatParamCurve
 * Size: 0x0038
 */
export type FLensFlareFloatParamCurve = {
  MaterialParamName: FName;  // 0x0000 (0x0008) [FName]
  MaterialParamIndex: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.LinkedAccount
 * Size: 0x0020
 */
export type FLinkedAccount = {
  identityProviderId: string;  // 0x0000 (0x0010) [FString]
  AccountId: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.Camera_X.LocationCameraKnock
 * Size: 0x001C
 * Extends: FCameraKnockBase
 */
export type FLocationCameraKnock = FCameraKnockBase & {
};

/**
 * ScriptStruct ProjectX.LocalizationConfig_X.LocOverride
 * Size: 0x0040
 */
export type FLocOverride = {
  Section: string;  // 0x0000 (0x0010) [FString]
  Key: string;  // 0x0010 (0x0010) [FString]
  Value: string;  // 0x0020 (0x0010) [FString]
  Package: string;  // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.MapPrefs
 * Size: 0x0020
 */
export type FMapPrefs = {
};

/**
 * ScriptStruct ProjectX.ServerExploitManager_X.MatchExploitReportData
 * Size: 0x0058
 */
export type FMatchExploitReportData = {
};

/**
 * ScriptStruct ProjectX.MatchInfoWebService_X.MatchInfoJson
 * Size: 0x0024
 */
export type FMatchInfoJson = {
  Guid: string;  // 0x0000 (0x0010) [FString]
  bIsPlaylistProtected: boolean;  // 0x0020 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.OnlineGameMatchmaking_X.MatchmakingRequestData
 * Size: 0x0060
 */
export type FMatchmakingRequestData = {
  PartyID: string;  // 0x0000 (0x0010) [FString]
  SecondsSearching: number;  // 0x0030 (0x0004) [int32]
  CurrentServerID: string;  // 0x0038 (0x0010) [FString]
  bDisableCrossPlay: boolean;  // 0x0048 (0x0004) [bool : 0x1]
  bIgnoreSkill: boolean;  // 0x0048 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX.MatchPlayerData_X.MatchSkillUpdate
 * Size: 0x0024
 */
export type FMatchSkillUpdate = {
  bValid: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  Mu: number;  // 0x0004 (0x0004) [float]
  Sigma: number;  // 0x0008 (0x0004) [float]
  Tier: number;  // 0x000c (0x0004) [int32]
  Division: number;  // 0x0010 (0x0004) [int32]
  PrevMu: number;  // 0x0014 (0x0004) [float]
  PrevSigma: number;  // 0x0018 (0x0004) [float]
  PrevTier: number;  // 0x001c (0x0004) [int32]
  PrevDivision: number;  // 0x0020 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.SystemMetrics_X.MemoryMetrics
 * Size: 0x0004
 */
export type FMemoryMetrics = {
  Physical: number;  // 0x0000 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX._Types_X.MessagePayload
 * Size: 0x0058
 */
export type FMessagePayload = {
  SenderId: string;  // 0x0000 (0x0010) [FString]
  RoomId: string;  // 0x0010 (0x0010) [FString]
  MessageText: string;  // 0x0020 (0x0010) [FString]
  TimeStamp: bigint;  // 0x0030 (0x0008) [uint64]
  SequenceNumber: number;  // 0x0038 (0x0004) [int32]
  bWantsToRecord: boolean;  // 0x003c (0x0004) [bool : 0x1]
  MessageId: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.EOSMetrics_X.MetricEventJsonStruct
 * Size: 0x0010
 */
export type FMetricEventJsonStruct = {
};

/**
 * ScriptStruct ProjectX._Types_X.MetricsEvent
 * Size: 0x0070
 */
export type FMetricsEvent = {
  TimeSeconds: number;  // 0x0048 (0x0004) [float]
  Version: number;  // 0x004c (0x0004) [int32]
  EventName: string;  // 0x0050 (0x0010) [FString]
  EventData: string;  // 0x0060 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.MigrationReservationData
 * Size: 0x00E8
 */
export type FMigrationReservationData = {
  PlayerName: string;  // 0x0048 (0x0010) [FString]
  ClubID: bigint;  // 0x00a0 (0x0008) [uint64]
  bDisableCrossPlay: boolean;  // 0x00ac (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.RPC_GetClubStats_X.MilestoneTitleData
 * Size: 0x000C
 */
export type FMilestoneTitleData = {
  Title: FName;  // 0x0004 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.OnlineConfig_X.ModifierSubscription
 * Size: 0x0038
 */
export type FModifierSubscription = {
  OnAdd: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
  OnRemove: FScriptDelegate;  // 0x0020 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.ParameterDispenser_X.NameParamPair
 * Size: 0x0010
 */
export type FNameParamPair = {
  Key: FName;  // 0x0000 (0x0008) [FName]
  Value: FName;  // 0x0008 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX._Types_X.NetStats
 * Size: 0x000C
 */
export type FNetStats = {
  PingMin: number;  // 0x0000 (0x0004) [float]
  Jitter: number;  // 0x0004 (0x0004) [float]
  LossPct: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.SystemMetrics_X.NetworkAdapterMetrics
 * Size: 0x0010
 */
export type FNetworkAdapterMetrics = {
};

/**
 * ScriptStruct ProjectX.OnlineMessageComponent_X.OnlineMessageHandler
 * Size: 0x0018
 */
export type FOnlineMessageHandler = {
};

/**
 * ScriptStruct ProjectX.PsyNetService_PersonaInfo_X.OnlinePersonaData
 * Size: 0x0078
 */
export type FOnlinePersonaData = {
  PlayerName: string;  // 0x0048 (0x0010) [FString]
  PresenceInfo: string;  // 0x0058 (0x0010) [FString]
  PresenceState: string;  // 0x0068 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.AddReservationMessagePublic_X.OnlinePlayerMapPrefs
 * Size: 0x0068
 */
export type FOnlinePlayerMapPrefs = {
};

/**
 * ScriptStruct ProjectX.OnlinePlayerStorageSync_X.OnlinePlayerStorageSyncRequest
 * Size: 0x000D
 */
export type FOnlinePlayerStorageSyncRequest = {
  ClientTick: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.OnlinePlayerStorageSync_X.OnlinePlayerStorageSyncResult
 * Size: 0x001D
 */
export type FOnlinePlayerStorageSyncResult = {
  ServerTick: number;  // 0x0010 (0x0004) [int32]
  Checksum: number;  // 0x0014 (0x0004) [int32]
  bChecksumMatch: boolean;  // 0x0018 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX._Types_X.OnlineStatus
 * Size: 0x0059
 */
export type FOnlineStatus = {
  PresenceInfo: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._SharedHelpers.Orientation
 * Size: 0x0018
 */
export type FOrientation = {
};

/**
 * ScriptStruct ProjectX.SystemMetrics_X.OSMetrics
 * Size: 0x0020
 */
export type FOSMetrics = {
  Type: string;  // 0x0000 (0x0010) [FString]
  Bits: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.OnlineGameReservations_AssignTeamsByParty_X.PartyByTeam
 * Size: 0x0050
 */
export type FPartyByTeam = {
  Size: number;  // 0x004c (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.PsyNetService_PartyJoinRequestAccepted_X.PartyData
 * Size: 0x0080
 */
export type FPartyData = {
};

/**
 * ScriptStruct ProjectX.Parties_X.PartyInvite
 * Size: 0x0078
 */
export type FPartyInvite = {
  Username: string;  // 0x0048 (0x0010) [FString]
  PartyID: string;  // 0x0058 (0x0010) [FString]
  InvitedAt: bigint;  // 0x0068 (0x0008) [uint64]
  AcceptedAt: bigint;  // 0x0070 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX._Types_X.PartyJoinMatchSettings
 * Size: 0x0058
 */
export type FPartyJoinMatchSettings = {
  ServerName: string;  // 0x0000 (0x0010) [FString]
  PlaylistId: number;  // 0x0010 (0x0004) [int32]
  bFriendJoin: boolean;  // 0x0014 (0x0004) [bool : 0x1]
  CustomPassword: string;  // 0x0018 (0x0010) [FString]
  ReservationID: string;  // 0x0028 (0x0010) [FString]
  JoinName: string;  // 0x0038 (0x0010) [FString]
  JoinPassword: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.PartyMember
 * Size: 0x017A
 */
export type FPartyMember = {
  MemberName: string;  // 0x0090 (0x0010) [FString]
  MatchmakeRestrictions: number;  // 0x00a0 (0x0004) [int32]
  LocalControllerId: number;  // 0x00a4 (0x0004) [int32]
  bDataLoaded: boolean;  // 0x00a8 (0x0004) [bool : 0x1]
  XpLevel: number;  // 0x00ac (0x0004) [int32]
  bCompletedChallenges: boolean;  // 0x00b0 (0x0004) [bool : 0x1]
  bLegacyPlayer: boolean;  // 0x00b0 (0x0004) [bool : 0x2]
  bGuestAccount: boolean;  // 0x00b0 (0x0004) [bool : 0x4]
  bDisableCrossPlay: boolean;  // 0x00b8 (0x0004) [bool : 0x1]
  bTradingEnabled: boolean;  // 0x00b8 (0x0004) [bool : 0x2]
  bReadyToLockTrade: boolean;  // 0x0118 (0x0004) [bool : 0x1]
  bReadyToConfirmTrade: boolean;  // 0x0118 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX._Types_X.PartyMemberServer
 * Size: 0x0044
 */
export type FPartyMemberServer = {
  ServerName: string;  // 0x0000 (0x0010) [FString]
  CustomPassword: string;  // 0x0010 (0x0010) [FString]
  JoinName: string;  // 0x0020 (0x0010) [FString]
  JoinPassword: string;  // 0x0030 (0x0010) [FString]
  PlaylistId: number;  // 0x0040 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.RPC_GetPartyMemberSkill_X.PartyMemberSkill
 * Size: 0x0058
 */
export type FPartyMemberSkill = {
};

/**
 * ScriptStruct ProjectX.PartyMetrics_X.PartyMetricsData
 * Size: 0x000C
 */
export type FPartyMetricsData = {
  LocalPlayers: number;  // 0x0000 (0x0004) [int32]
  RemotePlayers: number;  // 0x0004 (0x0004) [int32]
  bPartyLeader: boolean;  // 0x0008 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.GameInfo_X.PauserData
 * Size: 0x000C
 */
export type FPauserData = {
  PauseNum: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.PsyNetChannel_X.PendingChannelService
 * Size: 0x001C
 */
export type FPendingChannelService = {
  MessageId: number;  // 0x0008 (0x0004) [int32]
  ReceiveTime: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.PartyMessageQueue_X.PendingMessage
 * Size: 0x0020
 */
export type FPendingMessage = {
};

/**
 * ScriptStruct ProjectX.OnlineGameReservations_X.PendingReservation
 * Size: 0x0018
 */
export type FPendingReservation = {
};

/**
 * ScriptStruct ProjectX.RPCQueue_X.PendingRPC
 * Size: 0x0020
 */
export type FPendingRPC = {
  UniqueId: number;  // 0x0008 (0x0004) [int32]
  CreationTime: number;  // 0x000c (0x0004) [float]
  Failures: number;  // 0x0010 (0x0004) [int32]
  NextSendTime: number;  // 0x0014 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.OnlinePlayerStorageQueue_X.PendingStorage
 * Size: 0x0014
 */
export type FPendingStorage = {
  Tick: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.ClientNetMetrics_X.PingStats
 * Size: 0x0010
 */
export type FPingStats = {
  Min: number;  // 0x0000 (0x0004) [float]
  Max: number;  // 0x0004 (0x0004) [float]
  Average: number;  // 0x0008 (0x0004) [float]
  Median: number;  // 0x000c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerBinding
 * Size: 0x002C
 */
export type FPlayerBinding = {
  Action: FName;  // 0x0000 (0x0008) [FName]
  Key: FName;  // 0x0008 (0x0008) [FName]
  Speed: number;  // 0x0014 (0x0004) [float]
  bRequired: boolean;  // 0x0018 (0x0004) [bool : 0x1]
  PressedTime: number;  // 0x0020 (0x0004) [float]
  ReleasedTime: number;  // 0x0024 (0x0004) [float]
  bTapped: boolean;  // 0x0028 (0x0004) [bool : 0x1]
  bToggled: boolean;  // 0x0028 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX.BlockStatusReporter_X.PlayerBlockListenData
 * Size: 0x0028
 */
export type FPlayerBlockListenData = {
  EpicId: string;  // 0x0000 (0x0010) [FString]
  Callback: FScriptDelegate;  // 0x0010 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.LocalClubData_X.PlayerClubPair
 * Size: 0x0050
 */
export type FPlayerClubPair = {
  ClubID: bigint;  // 0x0048 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX.OnlineClubProvider_X.PlayerClubSyncResult
 * Size: 0x0050
 */
export type FPlayerClubSyncResult = {
};

/**
 * ScriptStruct ProjectX.OnlineGameDLC_X.PlayerDLCInfo
 * Size: 0x0074
 */
export type FPlayerDLCInfo = {
  ValidationReadyDelegate: FScriptDelegate;  // 0x0058 (0x0018) [FScriptDelegate]
  TimeLastOwnershipRequest: number;  // 0x0070 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerPermissions
 * Size: 0x0010
 */
export type FPlayerPermissions = {
  bRequirePinForFriends: boolean;  // 0x0004 (0x0004) [bool : 0x1]
  bItemShopNotificationsAllowed: boolean;  // 0x0004 (0x0004) [bool : 0x2]
  bFilterMatureLanguage: boolean;  // 0x000c (0x0004) [bool : 0x1]
  bEnableCPCCShowRoWModal: boolean;  // 0x000c (0x0004) [bool : 0x2]
  bEnableCPCCShowRealPrice: boolean;  // 0x000c (0x0004) [bool : 0x4]
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerPermissionsList
 * Size: 0x0058
 */
export type FPlayerPermissionsList = {
};

/**
 * ScriptStruct ProjectX.RPC_GetPlayerPermissions_X.PlayerPermissionsReponse
 * Size: 0x0058
 */
export type FPlayerPermissionsReponse = {
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerSeasonRewardProgress
 * Size: 0x0050
 */
export type FPlayerSeasonRewardProgress = {
  SeasonLevel: number;  // 0x0048 (0x0004) [int32]
  SeasonLevelWins: number;  // 0x004c (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerSkillRating
 * Size: 0x0070
 * Extends: FPlaylistSkillRating
 */
export type FPlayerSkillRating = FPlaylistSkillRating & {
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerTitleCategory
 * Size: 0x0028
 */
export type FPlayerTitleCategory = {
  Id: FName;  // 0x0000 (0x0008) [FName]
  Color: string;  // 0x0008 (0x0010) [FString]
  GlowColor: string;  // 0x0018 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.PlayerTitleData
 * Size: 0x002C
 */
export type FPlayerTitleData = {
  Id: FName;  // 0x0000 (0x0008) [FName]
  Text: string;  // 0x0008 (0x0010) [FString]
  Category: FName;  // 0x0018 (0x0008) [FName]
  SortPriority: number;  // 0x0020 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.OnlineGameParty_X.PlaylistRestrictionPlayer
 * Size: 0x004C
 */
export type FPlaylistRestrictionPlayer = {
  Tier: number;  // 0x0048 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.PlaylistSkillRating
 * Size: 0x0024
 * Extends: FTierSkillRating
 */
export type FPlaylistSkillRating = FTierSkillRating & {
  Playlist: number;  // 0x0020 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.PlaylistTierSkillRating
 * Size: 0x0024
 * Extends: FTierSkillRating
 */
export type FPlaylistTierSkillRating = FTierSkillRating & {
  Playlist: number;  // 0x0020 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.PostProcessManager_X.PostProcessOverride
 * Size: 0x0184
 */
export type FPostProcessOverride = {
  Id: FName;  // 0x0170 (0x0008) [FName]
  BlendInTime: number;  // 0x0178 (0x0004) [float]
  BlendOutTime: number;  // 0x017c (0x0004) [float]
  bEnabled: boolean;  // 0x0180 (0x0004) [bool : 0x1]
  bDefaultEnabled: boolean;  // 0x0180 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX.PostProcessManager_X.PPChainInfo
 * Size: 0x0010
 */
export type FPPChainInfo = {
  ChainName: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.PostProcessManager_X.PPEffectDefaults
 * Size: 0x000C
 */
export type FPPEffectDefaults = {
  EffectName: FName;  // 0x0000 (0x0008) [FName]
  bEnabled: boolean;  // 0x0008 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.PostProcessManager_X.PPPersistentEffectDefaults
 * Size: 0x001C
 */
export type FPPPersistentEffectDefaults = {
  EffectName: FName;  // 0x0000 (0x0008) [FName]
  MaterialEffectName: FName;  // 0x0008 (0x0008) [FName]
  MaterialParamName: FName;  // 0x0010 (0x0008) [FName]
  DefaultValue: number;  // 0x0018 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.RenderProfiler_X.PrimitiveComponentProfile
 * Size: 0x0070
 */
export type FPrimitiveComponentProfile = {
  ContentName: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.EOS_AccountSummaryResponse.PrivacySettings
 * Size: 0x0010
 */
export type FPrivacySettings = {
  ReceiveInvites: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.OnlineGamePrivateMatch_X.PrivateMatchmakingRequestData
 * Size: 0x0014
 */
export type FPrivateMatchmakingRequestData = {
  SubRegionToMatchmake: string;  // 0x0000 (0x0010) [FString]
  PlaylistId: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.ClassPropertyConfig_X.PropertyOverride
 * Size: 0x0030
 */
export type FPropertyOverride = {
  Class: string;  // 0x0000 (0x0010) [FString]
  Property: string;  // 0x0010 (0x0010) [FString]
  Value: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.PsyNetBeaconPartyReservation
 * Size: 0x0010
 */
export type FPsyNetBeaconPartyReservation = {
};

/**
 * ScriptStruct ProjectX._Types_X.PsyNetBeaconPlayerReservation
 * Size: 0x0060
 */
export type FPsyNetBeaconPlayerReservation = {
  DSConnectToken: string;  // 0x0050 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.PsyNetBeaconReservation
 * Size: 0x0048
 */
export type FPsyNetBeaconReservation = {
  ReservationID: string;  // 0x0000 (0x0010) [FString]
  Playlist: number;  // 0x0010 (0x0004) [int32]
  IsBackfill: boolean;  // 0x0014 (0x0004) [bool : 0x1]
  IsBotMatch: boolean;  // 0x0014 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX.PsyNet_X.PsyNetKeys
 * Size: 0x0040
 */
export type FPsyNetKeys = {
  Environment: string;  // 0x0000 (0x0010) [FString]
  PsyNetAuth: string;  // 0x0010 (0x0010) [FString]
  PsyConfigAuth: string;  // 0x0020 (0x0010) [FString]
  SteamPublisher: string;  // 0x0030 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.Parties_X.PsyNetPartyInfo
 * Size: 0x0070
 */
export type FPsyNetPartyInfo = {
  PartyID: string;  // 0x0000 (0x0010) [FString]
  CreatedAt: bigint;  // 0x0010 (0x0008) [uint64]
  JoinID: string;  // 0x0060 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.Parties_X.PsyNetPartyMember
 * Size: 0x0080
 */
export type FPsyNetPartyMember = {
  PartyID: string;  // 0x0000 (0x0010) [FString]
  Username: string;  // 0x0058 (0x0010) [FString]
  JoinedAt: bigint;  // 0x0068 (0x0008) [uint64]
  Role: string;  // 0x0070 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.PsyNetPersonaData
 * Size: 0x0078
 */
export type FPsyNetPersonaData = {
  PlayerName: string;  // 0x0048 (0x0010) [FString]
  PresenceInfo: string;  // 0x0058 (0x0010) [FString]
  PresenceState: string;  // 0x0068 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.PsyNetRequestQue_X.PsyNetRequest
 * Size: 0x0018
 */
export type FPsyNetRequest = {
  Id: FName;  // 0x0000 (0x0008) [FName]
  TimeoutTime: number;  // 0x0010 (0x0004) [float]
  SendTime: number;  // 0x0014 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.PsyNetMessengerWebSocket_X.QueuedPsyNetMessage
 * Size: 0x0014
 */
export type FQueuedPsyNetMessage = {
  TimeoutTime: number;  // 0x0010 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.AprilConfig_X.QuickChatOverridePair
 * Size: 0x0020
 */
export type FQuickChatOverridePair = {
  Id: string;  // 0x0000 (0x0010) [FString]
  Override: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RandomStream_X.RandomStream_Mirror
 * Size: 0x0004
 */
export type FRandomStream_Mirror = {
  Seed: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.PlayerInput_X.RawAxisValue
 * Size: 0x0010
 */
export type FRawAxisValue = {
  Value: number;  // 0x0000 (0x0004) [float]
  LastFrameChanged: bigint;  // 0x0008 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX._Types_X.RegionSecret
 * Size: 0x0020
 */
export type FRegionSecret = {
  Region: string;  // 0x0000 (0x0010) [FString]
  Secret: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.RenderProfile
 * Size: 0x0028
 */
export type FRenderProfile = {
  GameThreadTime: number;  // 0x0000 (0x0004) [float]
  RenderThreadTime: number;  // 0x0004 (0x0004) [float]
  GPUTime: number;  // 0x0008 (0x0004) [float]
  FrameTime: number;  // 0x000c (0x0004) [float]
  FPS: number;  // 0x0010 (0x0004) [float]
  AccumGameThreadTime: number;  // 0x0014 (0x0004) [float]
  AccumRenderThreadTime: number;  // 0x0018 (0x0004) [float]
  AccumGPUTime: number;  // 0x001c (0x0004) [float]
  AccumFrameTime: number;  // 0x0020 (0x0004) [float]
  NumSamples: number;  // 0x0024 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.ReplicatedRBState
 * Size: 0x003C
 */
export type FReplicatedRBState = {
  Time: number;  // 0x0034 (0x0004) [float]
  bSleeping: boolean;  // 0x0038 (0x0004) [bool : 0x1]
  bNewData: boolean;  // 0x0038 (0x0004) [bool : 0x2]
};

/**
 * ScriptStruct ProjectX._Types_X.ReplicatedRBStateNoQuat
 * Size: 0x0038
 */
export type FReplicatedRBStateNoQuat = {
  QuatX: number;  // 0x0000 (0x0004) [float]
  QuatY: number;  // 0x0004 (0x0004) [float]
  QuatZ: number;  // 0x0008 (0x0004) [float]
  QuatW: number;  // 0x000c (0x0004) [float]
  bSleeping: boolean;  // 0x0034 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX._Types_X.ReplicatedReservationData
 * Size: 0x0059
 */
export type FReplicatedReservationData = {
  PlayerName: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.ReservationData
 * Size: 0x0110
 */
export type FReservationData = {
  PlayerName: string;  // 0x0048 (0x0010) [FString]
  TimeoutTime: number;  // 0x00a4 (0x0004) [float]
  bDisableCrossPlay: boolean;  // 0x00a8 (0x0004) [bool : 0x1]
  ClubID: bigint;  // 0x00c0 (0x0008) [uint64]
  bIgnoreBeaconDisconnect: boolean;  // 0x00e0 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX._Types_X.ReservationPlayerData
 * Size: 0x00A0
 */
export type FReservationPlayerData = {
  PlayerName: string;  // 0x0048 (0x0010) [FString]
  SkillMu: number;  // 0x0058 (0x0004) [float]
  SkillSigma: number;  // 0x005c (0x0004) [float]
  Tier: number;  // 0x0060 (0x0004) [int32]
  bRemotePlayer: boolean;  // 0x0064 (0x0004) [bool : 0x1]
  ClubID: bigint;  // 0x0098 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX.Camera_X.RotationCameraKnock
 * Size: 0x001C
 * Extends: FCameraKnockBase
 */
export type FRotationCameraKnock = FCameraKnockBase & {
};

/**
 * ScriptStruct ProjectX.RPCQueue_X.RPCError
 * Size: 0x0020
 */
export type FRPCError = {
  Type: string;  // 0x0000 (0x0010) [FString]
  Message: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPCQueue_X.RPCResponse
 * Size: 0x0030
 */
export type FRPCResponse = {
  Id: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.RPC_Test_X.RPCTestItem
 * Size: 0x0078
 */
export type FRPCTestItem = {
  BoolItem: boolean;  // 0x0000 (0x0004) [bool : 0x1]
  IntItem: number;  // 0x0004 (0x0004) [int32]
  FloatItem: number;  // 0x0008 (0x0004) [float]
  StringItem: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.RPC_Test_X.RPCTestParam
 * Size: 0x0088
 */
export type FRPCTestParam = {
};

/**
 * ScriptStruct ProjectX.RPC_GetClubStats_X.SeasonalBadgeTierData
 * Size: 0x0018
 */
export type FSeasonalBadgeTierData = {
  Season: number;  // 0x0000 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.ServerConnectionInfo
 * Size: 0x0030
 */
export type FServerConnectionInfo = {
  ServerAddress: string;  // 0x0000 (0x0010) [FString]
  PingAddress: string;  // 0x0010 (0x0010) [FString]
  ServerName: string;  // 0x0020 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.ServerReservationData
 * Size: 0x0070
 */
export type FServerReservationData = {
  ServerName: string;  // 0x0000 (0x0010) [FString]
  Playlist: number;  // 0x0010 (0x0004) [int32]
  Region: string;  // 0x0018 (0x0010) [FString]
  ReservationID: string;  // 0x0028 (0x0010) [FString]
  DSRToken: string;  // 0x0038 (0x0010) [FString]
  JoinName: string;  // 0x0050 (0x0010) [FString]
  JoinPassword: string;  // 0x0060 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.ServerResult
 * Size: 0x00A8
 */
export type FServerResult = {
  Address: string;  // 0x0000 (0x0010) [FString]
  ServerName: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.PsyNetMetrics_X.ServiceErrorData
 * Size: 0x000C
 */
export type FServiceErrorData = {
  Type: FName;  // 0x0000 (0x0008) [FName]
  Count: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.PsyNetMetrics_X.ServiceMetricsData
 * Size: 0x0024
 */
export type FServiceMetricsData = {
  Service: string;  // 0x0000 (0x0010) [FString]
  Attempts: number;  // 0x0010 (0x0004) [int32]
  Failures: number;  // 0x0014 (0x0004) [int32]
  MinLatency: number;  // 0x0018 (0x0004) [float]
  MaxLatency: number;  // 0x001c (0x0004) [float]
  AvgLatency: number;  // 0x0020 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.PsyNetServiceSubscriptions_X.ServiceSubscription
 * Size: 0x0020
 */
export type FServiceSubscription = {
  Callback: FScriptDelegate;  // 0x0008 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.RPC_PlayerStorageSet_X.SetPlayerStorageRequestItem
 * Size: 0x0021
 */
export type FSetPlayerStorageRequestItem = {
  Category: FName;  // 0x0000 (0x0008) [FName]
  Tick: number;  // 0x0008 (0x0004) [int32]
  Checksum: number;  // 0x000c (0x0004) [int32]
  Data: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.SetPlayerStorageResult_X.SetPlayerStorageResultItem
 * Size: 0x0010
 */
export type FSetPlayerStorageResultItem = {
  Category: FName;  // 0x0000 (0x0008) [FName]
  Tick: number;  // 0x0008 (0x0004) [int32]
  bOutOfSync: boolean;  // 0x000c (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.ShakeComponent_X.ShakeReceiver
 * Size: 0x000C
 */
export type FShakeReceiver = {
  Scale: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX._Types_X.SignedMessagePacket
 * Size: 0x0048
 */
export type FSignedMessagePacket = {
  MessagePayload: string;  // 0x0000 (0x0010) [FString]
  Signature: string;  // 0x0010 (0x0010) [FString]
  ReceivingTimestamp: bigint;  // 0x0020 (0x0008) [uint64]
  SanitizedReceivedTextMessage: string;  // 0x0028 (0x0010) [FString]
  PublicKey: string;  // 0x0038 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.PartyMessage_LocalPlayers_X.SimplePartyMember
 * Size: 0x0058
 */
export type FSimplePartyMember = {
  MemberName: string;  // 0x0048 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.SkillMatchData
 * Size: 0x0024
 */
export type FSkillMatchData = {
  ServerId: string;  // 0x0000 (0x0010) [FString]
  Playlist: number;  // 0x0010 (0x0004) [int32]
  WinningTeam: number;  // 0x0014 (0x0004) [int32]
  Team0Score: number;  // 0x0018 (0x0004) [int32]
  Team1Score: number;  // 0x001c (0x0004) [int32]
  bOverTime: boolean;  // 0x0020 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX._Types_X.SkillMatchParty
 * Size: 0x0020
 */
export type FSkillMatchParty = {
  PartyID: number;  // 0x0000 (0x0004) [int32]
  PctTimePlayed: number;  // 0x0004 (0x0004) [float]
  bQuitter: boolean;  // 0x0008 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX._Types_X.SkillMatchPartyRating
 * Size: 0x0024
 * Extends: FTierSkillRating
 */
export type FSkillMatchPartyRating = FTierSkillRating & {
  PartyID: number;  // 0x0020 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.SkillMatchPlayer
 * Size: 0x0060
 */
export type FSkillMatchPlayer = {
  PctTimePlayed: number;  // 0x0048 (0x0004) [float]
  TimePlayed: number;  // 0x004c (0x0004) [float]
  bQuitter: boolean;  // 0x0050 (0x0004) [bool : 0x1]
  PartyID: number;  // 0x0054 (0x0004) [int32]
  Score: number;  // 0x0058 (0x0004) [int32]
  Team: number;  // 0x005c (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.SkillRating
 * Size: 0x0008
 */
export type FSkillRating = {
  Mu: number;  // 0x0000 (0x0004) [float]
  Sigma: number;  // 0x0004 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.OnlineGameSkill_X.SkillSyncRequest
 * Size: 0x0068
 */
export type FSkillSyncRequest = {
  Callback: FScriptDelegate;  // 0x0050 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.GFxSoundPack_X.SoundPackSoundRef
 * Size: 0x0010
 */
export type FSoundPackSoundRef = {
  Name: FName;  // 0x0008 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.ClubDetails_X.StatBadge
 * Size: 0x0009
 */
export type FStatBadge = {
  Stat: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.RPC_GetClubStats_X.StatMilestoneData
 * Size: 0x001D
 */
export type FStatMilestoneData = {
  Stat: FName;  // 0x0000 (0x0008) [FName]
  Value: number;  // 0x0018 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.OnlineGameDLC_X.SteamJsonResponseGetPublisherAppOwnership
 * Size: 0x0010
 */
export type FSteamJsonResponseGetPublisherAppOwnership = {
};

/**
 * ScriptStruct ProjectX.OnlineGameDLC_X.SteamJsonResponseGetPublisherAppOwnership2
 * Size: 0x0010
 */
export type FSteamJsonResponseGetPublisherAppOwnership2 = {
};

/**
 * ScriptStruct ProjectX.OnlineGameDLC_X.SteamJsonResponseGetPublisherAppOwnership3
 * Size: 0x0028
 */
export type FSteamJsonResponseGetPublisherAppOwnership3 = {
  AppID: bigint;  // 0x0000 (0x0008) [uint64]
  OwnerSteamID: bigint;  // 0x0008 (0x0008) [uint64]
  OwnsApp: boolean;  // 0x0010 (0x0004) [bool : 0x1]
  Permanent: boolean;  // 0x0010 (0x0004) [bool : 0x2]
  TimeStamp: string;  // 0x0018 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX.OnlineGameDLC_X.SteamPlayerDLCOwnershipState
 * Size: 0x0011
 */
export type FSteamPlayerDLCOwnershipState = {
  Name: FName;  // 0x0000 (0x0008) [FName]
  AppID: bigint;  // 0x0008 (0x0008) [uint64]
};

/**
 * ScriptStruct ProjectX.OnlineGameDLC_X.SteamWebRequestData
 * Size: 0x0050
 */
export type FSteamWebRequestData = {
};

/**
 * ScriptStruct ProjectX.OnlinePlayerStorageQueue_X.StorageMaxSize
 * Size: 0x000C
 */
export type FStorageMaxSize = {
  Category: FName;  // 0x0000 (0x0008) [FName]
  MaxSizeBytes: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.OnlinePlayerStorageManifest_X.StorageMetadata
 * Size: 0x000D
 */
export type FStorageMetadata = {
  Category: FName;  // 0x0000 (0x0008) [FName]
  Checksum: number;  // 0x0008 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX._Types_X.SuperRegionData
 * Size: 0x0030
 */
export type FSuperRegionData = {
  Region: string;  // 0x0000 (0x0010) [FString]
  Label: string;  // 0x0010 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.SuperSonicConfig
 * Size: 0x000C
 */
export type FSuperSonicConfig = {
  Speed: number;  // 0x0000 (0x0004) [float]
  TurnoffSpeedBuffer: number;  // 0x0004 (0x0004) [float]
  TurnoffTime: number;  // 0x0008 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.OnlineGameReservations_X.TeamPairHistory
 * Size: 0x0094
 */
export type FTeamPairHistory = {
  Count: number;  // 0x0090 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.CheatManager_X.TestStructEvent
 * Size: 0x0018
 */
export type FTestStructEvent = {
  Callback: FScriptDelegate;  // 0x0000 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX._Types_X.TierSkillRating
 * Size: 0x0020
 * Extends: FSkillRating
 */
export type FTierSkillRating = FSkillRating & {
  Tier: number;  // 0x0008 (0x0004) [int32]
  Division: number;  // 0x000c (0x0004) [int32]
  MatchesPlayed: number;  // 0x0010 (0x0004) [int32]
  PlacementMatchesPlayed: number;  // 0x0014 (0x0004) [int32]
  WinStreak: number;  // 0x0018 (0x0004) [int32]
  MMR: number;  // 0x001c (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.EpicConfig_X.TradePermissionEnabledPair
 * Size: 0x0008
 */
export type FTradePermissionEnabledPair = {
  bEnabled: boolean;  // 0x0004 (0x0004) [bool : 0x1]
};

/**
 * ScriptStruct ProjectX.EpicConfig_X.TradePermissionPair
 * Size: 0x0011
 */
export type FTradePermissionPair = {
  PermissionLabel: string;  // 0x0000 (0x0010) [FString]
};

/**
 * ScriptStruct ProjectX._Types_X.UpdatedPlayerSkillRating
 * Size: 0x0080
 * Extends: FPlayerSkillRating
 */
export type FUpdatedPlayerSkillRating = FPlayerSkillRating & {
  PrevMu: number;  // 0x0070 (0x0004) [float]
  PrevSigma: number;  // 0x0074 (0x0004) [float]
  PrevTier: number;  // 0x0078 (0x0004) [int32]
  PrevDivision: number;  // 0x007c (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.OnlineGameStats_X.UploadStatData
 * Size: 0x004C
 */
export type FUploadStatData = {
  Value: number;  // 0x0048 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.OnlineGameStats_X.UploadStatDataSet
 * Size: 0x0018
 */
export type FUploadStatDataSet = {
  StatId: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.Camera_X.VectorInterpRate
 * Size: 0x0018
 */
export type FVectorInterpRate = {
  MaxDistance: number;  // 0x0000 (0x0004) [float]
  InterpRate: number;  // 0x0004 (0x0004) [float]
  ForwardScale: number;  // 0x0008 (0x0004) [float]
  BackwardScale: number;  // 0x000c (0x0004) [float]
  SideScale: number;  // 0x0010 (0x0004) [float]
  UpDownScale: number;  // 0x0014 (0x0004) [float]
};

/**
 * ScriptStruct ProjectX.ParameterDispenser_X.VectorParamPair
 * Size: 0x0014
 */
export type FVectorParamPair = {
  Key: FName;  // 0x0000 (0x0008) [FName]
};

/**
 * ScriptStruct ProjectX.SystemMetrics_X.VideoCardMetrics
 * Size: 0x0014
 */
export type FVideoCardMetrics = {
  Type: string;  // 0x0000 (0x0010) [FString]
  RAM: number;  // 0x0010 (0x0004) [int32]
};

/**
 * ScriptStruct ProjectX.WordFilterTypes_X.WordFilterPair
 * Size: 0x0078
 */
export type FWordFilterPair = {
  Id: string;  // 0x0000 (0x0010) [FString]
  Key: string;  // 0x0010 (0x0010) [FString]
  Value: string;  // 0x0020 (0x0010) [FString]
  bPending: boolean;  // 0x0034 (0x0004) [bool : 0x1]
  LastRequestTime: number;  // 0x0038 (0x0004) [float]
  Callback: FScriptDelegate;  // 0x0048 (0x0018) [FScriptDelegate]
  ErrorCallback: FScriptDelegate;  // 0x0060 (0x0018) [FScriptDelegate]
};

/**
 * ScriptStruct ProjectX.OnlineGameWordFilterProcessor_X.WordFilterRequest
 * Size: 0x0040
 */
export type FWordFilterRequest = {
  Comment: string;  // 0x0008 (0x0010) [FString]
  Sanitized: string;  // 0x0018 (0x0010) [FString]
  Callback: FScriptDelegate;  // 0x0028 (0x0018) [FScriptDelegate]
};
