/**
 * Core Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { FName, FScriptDelegate } from '../structs/Core';
import type { UScriptGroup_ORS } from './Engine';

/**
 * Class Core.__AsyncTask__All_0x1
 * Size: 0x0070
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Hidden | CLASS_HideDropDown
 */
export type U__AsyncTask__All_0x1 = UObject & {
  DependentsCount: number;  // 0x0060 (0x0004) [int32]
};

// __AsyncTask__All_0x1 Functions
// __AsyncTask__All_0x1(): void

/**
 * Class Core._LoggingDoc
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed
 */
export type U_LoggingDoc = UObject & {
};

// _LoggingDoc Functions
// static TestSpecialLogging(): void

/**
 * Class Core._Types_Core
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type U_Types_Core = UObject & {
};

/**
 * Class Core._Types_Generated
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed
 */
export type U_Types_Generated = UObject & {
};

/**
 * Class Core.ArrayErrors
 * Size: 0x0090
 * Extends: UErrorList
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UArrayErrors = UErrorList & {
};

/**
 * Class Core.ArrayFuncs
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed
 */
export type UArrayFuncs = UObject & {
};

// ArrayFuncs Functions
// static GetRandomElement(): void
// static ShuffleArray(): void

/**
 * Class Core.ArrayProperty
 * Size: 0x00D0
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UArrayProperty = UProperty & {
};

/**
 * Class Core.AsyncResult
 * Size: 0x00D0
 * Extends: UAsyncTask
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UAsyncResult = UAsyncTask & {
};

/**
 * Class Core.AsyncTask
 * Size: 0x00D0
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UAsyncTask = UObject & {
  bComplete: boolean;  // 0x0060 (0x0004) [bool : 0x1]
  bDisposed: boolean;  // 0x0060 (0x0004) [bool : 0x2]
  __EventAsyncTaskSuccess__Delegate: FScriptDelegate;  // 0x0070 (0x0018) [FScriptDelegate]
  __EventAsyncTaskFail__Delegate: FScriptDelegate;  // 0x0088 (0x0018) [FScriptDelegate]
  __EventAsyncTaskComplete__Delegate: FScriptDelegate;  // 0x00a0 (0x0018) [FScriptDelegate]
  __EventDisposed__Delegate: FScriptDelegate;  // 0x00b8 (0x0018) [FScriptDelegate]
};

// AsyncTask Functions
// static All(): void
// ClearCallbacks(): void
// static Create(): void
// static CreateError(): void
// static CreateSuccess(): void
// DependOn(): void
// Dispose(): void
// EventAsyncTaskComplete(): void
// EventAsyncTaskFail(): void
// EventAsyncTaskSuccess(): void
// EventDisposed(): void
// NotifyOnComplete(Callback: FScriptDelegate): void
// NotifyOnDispose(Callback: FScriptDelegate): void
// NotifyOnFail(Callback: FScriptDelegate): void
// NotifyOnSuccess(Callback: FScriptDelegate): void
// QueCallbacks(): void // Native
// SetComplete(): void
// SetError(): void
// Watch(): void

/**
 * Class Core.AutomationTest
 * Size: 0x00A0
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UAutomationTest = UObject & {
};

/**
 * Class Core.Base64
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UBase64 = UObject & {
};

// Base64 Functions
// static Decode(): void // Native
// static DecodeInline(): void // Native
// static DecodeString(Input: string): void // Native
// static DecodeStringInline(Input: string): void // Native
// static Encode(): void // Native
// static EncodeInline(): void // Native
// static EncodeString(): string // Native
// static EncodeStringInline(/* out */ Output: string): void // Native
// static PadAndDecodeString(Input: string): void

/**
 * Class Core.BoolProperty
 * Size: 0x00D0
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UBoolProperty = UProperty & {
};

/**
 * Class Core.Breadcrumbs
 * Size: 0x0068
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UBreadcrumbs = UObject & {
};

// Breadcrumbs Functions
// BreadcrumbFloat(Category: string, Value: number): void // Native
// BreadcrumbString(Category: string, Value: string): void // Native

/**
 * Class Core.ByteProperty
 * Size: 0x00D0
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UByteProperty = UProperty & {
};

/**
 * Class Core.Class
 * Size: 0x03B8
 * Extends: UState
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UClass = UState & {
};

/**
 * Class Core.ClassProperty
 * Size: 0x00E0
 * Extends: UObjectProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UClassProperty = UObjectProperty & {
};

/**
 * Class Core.ClassTuple_ORS
 * Size: 0x00C8
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UClassTuple_ORS = UObject & {
};

/**
 * Class Core.ClassTupleCollection_ORS
 * Size: 0x00C0
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UClassTupleCollection_ORS = UObject & {
};

/**
 * Class Core.Commandlet
 * Size: 0x00B4
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Transient | CLASS_Parsed | CLASS_Localized | CLASS_Native | CLASS_Exported
 */
export type UCommandlet = UObject & {
  HelpDescription: string;  // 0x0060 (0x0010) [FString]
  HelpUsage: string;  // 0x0070 (0x0010) [FString]
  HelpWebLink: string;  // 0x0080 (0x0010) [FString]
  IsServer: boolean;  // 0x00b0 (0x0004) [bool : 0x1]
  IsClient: boolean;  // 0x00b0 (0x0004) [bool : 0x2]
  IsEditor: boolean;  // 0x00b0 (0x0004) [bool : 0x4]
  LogToConsole: boolean;  // 0x00b0 (0x0004) [bool : 0x8]
  ShowErrorCount: boolean;  // 0x00b0 (0x0004) [bool : 0x10]
};

// Commandlet Functions
// Main(Params: string): number

/**
 * Class Core.Component
 * Size: 0x0070
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UComponent = UObject & {
  TemplateName: FName;  // 0x0068 (0x0008) [FName]
};

/**
 * Class Core.ComponentProperty
 * Size: 0x00D8
 * Extends: UObjectProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UComponentProperty = UObjectProperty & {
};

/**
 * Class Core.Compression
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UCompression = UObject & {
};

// Compression Functions
// static ZLibCompress(): boolean // Native

/**
 * Class Core.Config_ORS
 * Size: 0x00C0
 * Extends: UObject
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UConfig_ORS = UObject & {
};

/**
 * Class Core.Const
 * Size: 0x0080
 * Extends: UField
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UConst = UField & {
};

/**
 * Class Core.DebugDrawer
 * Size: 0x00C0
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UDebugDrawer = UObject & {
  bSilent: boolean;  // 0x0064 (0x0004) [bool : 0x1]
  bPrintActorsInline: boolean;  // 0x0064 (0x0004) [bool : 0x2]
  Indentation: number;  // 0x0068 (0x0004) [int32]
  IndentationString: string;  // 0x0070 (0x0010) [FString]
  PrintObjectCount: number;  // 0x00a0 (0x0004) [int32]
  __LogFunc__Delegate: FScriptDelegate;  // 0x00a8 (0x0018) [FScriptDelegate]
};

// DebugDrawer Functions
// DebugArrayObject(Title: string, Index: number): void
// DebugObject(Title: string): void
// EndSection(): void
// LogFunc(Str: string): void
// PrintArrayProperty(PropertyName: string, Index: number, Value: string): void
// PrintObject(Title: string): void
// PrintProperty(PropertyName: string, Value: string): void
// PrintSeperater(): void
// PrintText(Text: string): void
// Reset(): void
// ShouldDisplayDebug(Category: FName): boolean
// StartSection(): void

/**
 * Class Core.Default__Class
 * Size: 0x0000
 */
export type UDefault__Class = {
  readonly address: bigint;
};

/**
 * Class Core.DelegateProperty
 * Size: 0x00D8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UDelegateProperty = UProperty & {
};

/**
 * Class Core.DelegateTracker
 * Size: 0x0088
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UDelegateTracker = UObject & {
  __PlaceholderDelegate__Delegate: FScriptDelegate;  // 0x0070 (0x0018) [FScriptDelegate]
};

// DelegateTracker Functions
// AddDelegate(Callback: FScriptDelegate): number // Native
// PlaceholderDelegate(): void
// RemoveDelegate(CallbackId: number): FScriptDelegate // Native

/**
 * Class Core.DistributionFloat
 * Size: 0x007C
 * Extends: UComponent
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_EditInlineNew | CLASS_CollapseCategories | CLASS_Exported
 */
export type UDistributionFloat = UComponent & {
  VfTable_FCurveEdInterface: unknown;  // 0x0070 (0x0008) [unknown]
  bCanBeBaked: boolean;  // 0x0078 (0x0004) [bool : 0x1]
  bIsDirty: boolean;  // 0x0078 (0x0004) [bool : 0x2]
};

// DistributionFloat Functions
// GetFloatValue(F: number): number // Native

/**
 * Class Core.DistributionVector
 * Size: 0x007C
 * Extends: UComponent
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_EditInlineNew | CLASS_CollapseCategories | CLASS_Exported
 */
export type UDistributionVector = UComponent & {
  VfTable_FCurveEdInterface: unknown;  // 0x0070 (0x0008) [unknown]
  bCanBeBaked: boolean;  // 0x0078 (0x0004) [bool : 0x1]
  bIsDirty: boolean;  // 0x0078 (0x0004) [bool : 0x2]
};

// DistributionVector Functions
// GetVectorValue(F: number, LastExtreme: number): void // Native

/**
 * Class Core.Enum
 * Size: 0x0080
 * Extends: UField
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UEnum = UField & {
};

/**
 * Class Core.Error
 * Size: 0x0084
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UError = UObject & {
  Message: string;  // 0x0068 (0x0010) [FString]
  Code: number;  // 0x0078 (0x0004) [int32]
  RetryKey: FName;  // 0x007c (0x0008) [FName]
};

// Error Functions
// GetDebugMessage(): string
// GetLocalizedMessage(): string // Native

/**
 * Class Core.ErrorList
 * Size: 0x0080
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UErrorList = UObject & {
  LocalizationPackage: string;  // 0x0060 (0x0010) [FString]
  LocalizationSection: string;  // 0x0070 (0x0010) [FString]
};

// ErrorList Functions
// static GetErrorType(Error: FName): void // Native

/**
 * Class Core.ErrorType
 * Size: 0x0070
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UErrorType = UObject & {
  LocalizationKey: string;  // 0x0060 (0x0010) [FString]
};

// ErrorType Functions
// CreateError(InErrorMessage: string, InErrorCode: number): void // Native
// GetLocalizedMessage(): string // Native

/**
 * Class Core.Exporter
 * Size: 0x0098
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UExporter = UObject & {
  FormatExtension: unknown[];  // 0x0068 (0x0010) [TArray<unknown>]
  FormatDescription: unknown[];  // 0x0078 (0x0010) [TArray<unknown>]
};

/**
 * Class Core.Factory
 * Size: 0x00B8
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_NoExport
 */
export type UFactory = UObject & {
  Category: string;  // 0x0060 (0x0010) [FString]
  Description: string;  // 0x0080 (0x0010) [FString]
  bCreateNew: boolean;  // 0x00a0 (0x0004) [bool : 0x1]
  bEditAfterNew: boolean;  // 0x00a0 (0x0004) [bool : 0x2]
  bEditorImport: boolean;  // 0x00a0 (0x0004) [bool : 0x4]
  bText: boolean;  // 0x00a0 (0x0004) [bool : 0x8]
  bAssetNameMatchesPackageName: boolean;  // 0x00a0 (0x0004) [bool : 0x10]
  AutoPriority: number;  // 0x00a4 (0x0004) [int32]
};

/**
 * Class Core.FeatureSystem
 * Size: 0x0080
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UFeatureSystem = UObject & {
  Prime: boolean;  // 0x0068 (0x0004) [bool : 0x2]
  Matchmaking: boolean;  // 0x0068 (0x0004) [bool : 0x8]
  PrivateMatch: boolean;  // 0x0068 (0x0004) [bool : 0x10]
  SplitscreenMatch: boolean;  // 0x0068 (0x0004) [bool : 0x20]
  SplitscreenJoin: boolean;  // 0x0068 (0x0004) [bool : 0x40]
  SeasonMode: boolean;  // 0x0068 (0x0004) [bool : 0x80]
  Tutorial: boolean;  // 0x0068 (0x0004) [bool : 0x100]
  Garage: boolean;  // 0x0068 (0x0004) [bool : 0x200]
  Options: boolean;  // 0x0068 (0x0004) [bool : 0x400]
  ReplaySaves: boolean;  // 0x0068 (0x0004) [bool : 0x800]
  MainMenu: boolean;  // 0x0068 (0x0004) [bool : 0x1000]
  MidgameMenu: boolean;  // 0x0068 (0x0004) [bool : 0x2000]
  Party: boolean;  // 0x0068 (0x0004) [bool : 0x4000]
  PsyNetParty: boolean;  // 0x0068 (0x0004) [bool : 0x8000]
  Achievements: boolean;  // 0x0068 (0x0004) [bool : 0x10000]
  Stats: boolean;  // 0x0068 (0x0004) [bool : 0x20000]
  Leaderboards: boolean;  // 0x0068 (0x0004) [bool : 0x40000]
  XP: boolean;  // 0x0068 (0x0004) [bool : 0x80000]
  Chat: boolean;  // 0x0068 (0x0004) [bool : 0x100000]
  TrainingDifficulties: boolean;  // 0x0068 (0x0004) [bool : 0x200000]
  Spectator: boolean;  // 0x0068 (0x0004) [bool : 0x400000]
  CrossPlatformPrivateMatch: boolean;  // 0x0068 (0x0004) [bool : 0x800000]
  Lan: boolean;  // 0x0068 (0x0004) [bool : 0x1000000]
  PlayerReporting: boolean;  // 0x0068 (0x0004) [bool : 0x2000000]
  OnlineServices: boolean;  // 0x0068 (0x0004) [bool : 0x40000000]
  RemoveCrossPlatformProducts: boolean;  // 0x0068 (0x0004) [bool : 0x-80000000]
  ProductValidation: boolean;  // 0x006c (0x0004) [bool : 0x1]
  MapPrefs: boolean;  // 0x006c (0x0004) [bool : 0x2]
  PreMatchLobby: boolean;  // 0x006c (0x0004) [bool : 0x8]
  Challenges: boolean;  // 0x006c (0x0004) [bool : 0x10]
  AntiAddiction: boolean;  // 0x006c (0x0004) [bool : 0x20]
  TrainingEditor: boolean;  // 0x006c (0x0004) [bool : 0x40]
  VoiceChat: boolean;  // 0x006c (0x0004) [bool : 0x80]
  SplitScreen: boolean;  // 0x006c (0x0004) [bool : 0x100]
  Clubs: boolean;  // 0x006c (0x0004) [bool : 0x200]
  FilterContent: boolean;  // 0x006c (0x0004) [bool : 0x400]
  EncryptContent: boolean;  // 0x006c (0x0004) [bool : 0x800]
  EsportsCamera: boolean;  // 0x006c (0x0004) [bool : 0x4000]
  OnlineXP: boolean;  // 0x006c (0x0004) [bool : 0x8000]
  ClanforgeReservation: boolean;  // 0x006c (0x0004) [bool : 0x20000]
  UserSettingObserver: boolean;  // 0x006c (0x0004) [bool : 0x40000]
  Metrics: boolean;  // 0x006c (0x0004) [bool : 0x80000]
  EOSMetrics: boolean;  // 0x006c (0x0004) [bool : 0x100000]
  MusicPlaylistSelection: boolean;  // 0x006c (0x0004) [bool : 0x200000]
  SpecialEvents: boolean;  // 0x006c (0x0004) [bool : 0x400000]
  PlayerBannerCustomization: boolean;  // 0x006c (0x0004) [bool : 0x800000]
  SecureUDP: boolean;  // 0x006c (0x0004) [bool : 0x1000000]
  PsyNet: boolean;  // 0x006c (0x0004) [bool : 0x2000000]
  OnlinePlayerStorage: boolean;  // 0x006c (0x0004) [bool : 0x4000000]
  LocalSaveData: boolean;  // 0x006c (0x0004) [bool : 0x8000000]
  CrowdV2: boolean;  // 0x006c (0x0004) [bool : 0x10000000]
  ChatBan: boolean;  // 0x006c (0x0004) [bool : 0x20000000]
  BacktraceCrashDumps: boolean;  // 0x006c (0x0004) [bool : 0x40000000]
  SpotifyButton: boolean;  // 0x006c (0x0004) [bool : 0x-80000000]
  SeasonRewards: boolean;  // 0x0070 (0x0004) [bool : 0x2]
  FaceIt: boolean;  // 0x0070 (0x0004) [bool : 0x4]
  KnockOut: boolean;  // 0x0070 (0x0004) [bool : 0x8]
  OnlinePlayerTitles: boolean;  // 0x0070 (0x0004) [bool : 0x10]
  RestrictByRegion: boolean;  // 0x0070 (0x0004) [bool : 0x20]
  FirstTimeExperience: boolean;  // 0x0070 (0x0004) [bool : 0x80]
  RLBot: boolean;  // 0x0070 (0x0004) [bool : 0x100]
  UserBugReport: boolean;  // 0x0070 (0x0004) [bool : 0x200]
  SteamInput: boolean;  // 0x0070 (0x0004) [bool : 0x400]
  ReplayFXControls: boolean;  // 0x0070 (0x0004) [bool : 0x8000]
  ESportsShop: boolean;  // 0x0070 (0x0004) [bool : 0x10000]
  MatchHistory: boolean;  // 0x0070 (0x0004) [bool : 0x20000]
  DynamicRangeAudioSettings: boolean;  // 0x0070 (0x0004) [bool : 0x100000]
  QuickPlay: boolean;  // 0x0070 (0x0004) [bool : 0x200000]
  NewsPanelV2: boolean;  // 0x0070 (0x0004) [bool : 0x400000]
  Blueprints: boolean;  // 0x0070 (0x0004) [bool : 0x800000]
  RocketBucks: boolean;  // 0x0070 (0x0004) [bool : 0x2000000]
  Tritip: boolean;  // 0x0070 (0x0004) [bool : 0x8000000]
  DiscordRichPresence: boolean;  // 0x0070 (0x0004) [bool : 0x20000000]
  SupportACreator: boolean;  // 0x0070 (0x0004) [bool : 0x40000000]
  CinematicIntro: boolean;  // 0x0070 (0x0004) [bool : 0x-80000000]
  TinyCrowd: boolean;  // 0x0074 (0x0004) [bool : 0x1]
  CrumbTrail: boolean;  // 0x0074 (0x0004) [bool : 0x2]
  EpicGameStoreBuild: boolean;  // 0x0074 (0x0004) [bool : 0x4]
  XPGatedPlaylists: boolean;  // 0x0074 (0x0004) [bool : 0x8]
  TradeInV2: boolean;  // 0x0074 (0x0004) [bool : 0x20]
  Football: boolean;  // 0x0074 (0x0004) [bool : 0x40]
  RumbleSelection: boolean;  // 0x0074 (0x0004) [bool : 0x80]
  UndersizedParty: boolean;  // 0x0074 (0x0004) [bool : 0x100]
  StreamerSafeAudio: boolean;  // 0x0074 (0x0004) [bool : 0x200]
  FreeplayCommands: boolean;  // 0x0074 (0x0004) [bool : 0x400]
  Rumble_BM: boolean;  // 0x0074 (0x0004) [bool : 0x800]
  PlayerReportingV2: boolean;  // 0x0074 (0x0004) [bool : 0x1000]
  BlogScheduling: boolean;  // 0x0074 (0x0004) [bool : 0x2000]
  EOSVoice: boolean;  // 0x0074 (0x0004) [bool : 0x4000]
  QuickPostMatchRequeue: boolean;  // 0x0074 (0x0004) [bool : 0x8000]
  TrainingNavigation: boolean;  // 0x0074 (0x0004) [bool : 0x40000]
  TrainingManipulation: boolean;  // 0x0074 (0x0004) [bool : 0x80000]
  FilterByColor: boolean;  // 0x0074 (0x0004) [bool : 0x200000]
  Scoreboard: boolean;  // 0x0074 (0x0004) [bool : 0x400000]
  DynamicMapEvents: boolean;  // 0x0074 (0x0004) [bool : 0x800000]
  NameplateBoost: boolean;  // 0x0074 (0x0004) [bool : 0x2000000]
  EOSGameClips: boolean;  // 0x0074 (0x0004) [bool : 0x4000000]
  DynamicLogos: boolean;  // 0x0074 (0x0004) [bool : 0x8000000]
  XETagging: boolean;  // 0x0074 (0x0004) [bool : 0x10000000]
  PlayMenuV4: boolean;  // 0x0074 (0x0004) [bool : 0x20000000]
  DemoUpgrades: boolean;  // 0x0074 (0x0004) [bool : 0x40000000]
  QuickChatTimeStamp: boolean;  // 0x0074 (0x0004) [bool : 0x-80000000]
  SoccarPong: boolean;  // 0x0078 (0x0004) [bool : 0x1]
  OnlineFreeplay: boolean;  // 0x0078 (0x0004) [bool : 0x2]
  MatchmakingSubRegion: boolean;  // 0x0078 (0x0004) [bool : 0x8]
  CrossbarSFX: boolean;  // 0x0078 (0x0004) [bool : 0x10]
  RugbyIteration: boolean;  // 0x0078 (0x0004) [bool : 0x20]
  ChallengesV2: boolean;  // 0x0078 (0x0004) [bool : 0x80]
  PossessionExpanded: boolean;  // 0x0078 (0x0004) [bool : 0x100]
  KeepUp: boolean;  // 0x0078 (0x0004) [bool : 0x800]
  RocketPassUpgrades: boolean;  // 0x0078 (0x0004) [bool : 0x2000]
  PentathlonTournaments: boolean;  // 0x0078 (0x0004) [bool : 0x4000]
  DemolishUpdates: boolean;  // 0x0078 (0x0004) [bool : 0x8000]
  ViralItem: boolean;  // 0x0078 (0x0004) [bool : 0x10000]
  ThankYouMessage: boolean;  // 0x0078 (0x0004) [bool : 0x20000]
  AttackerDemoFX: boolean;  // 0x0078 (0x0004) [bool : 0x40000]
  NewDriverChallengesV2: boolean;  // 0x0078 (0x0004) [bool : 0x80000]
  TextModeration: boolean;  // 0x0078 (0x0004) [bool : 0x400000]
  FilterToggle: boolean;  // 0x0078 (0x0004) [bool : 0x800000]
  DdosPrevention: boolean;  // 0x0078 (0x0004) [bool : 0x1000000]
  OunceEnhancements: boolean;  // 0x0078 (0x0004) [bool : 0x2000000]
  FastFreeplay: boolean;  // 0x0078 (0x0004) [bool : 0x4000000]
  MatchAdminMutator: boolean;  // 0x0078 (0x0004) [bool : 0x8000000]
  Thistle: boolean;  // 0x0078 (0x0004) [bool : 0x10000000]
};

/**
 * Class Core.Field
 * Size: 0x0070
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Native | CLASS_Intrinsic
 */
export type UField = UObject & {
};

/**
 * Class Core.FileSystem
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UFileSystem = UObject & {
};

// FileSystem Functions
// static AppendStringToFile(Path: string, Text: string): boolean // Native
// static CloseLogFile(): void // Native
// static DeleteDirectoryTree(Path: string): boolean // Native
// static DeleteFile(Path: string): boolean // Native
// static FindFiles(Path: string): void // Native
// static GetFileExtension(Path: string): string // Native
// static GetFileExtensionWithoutDot(Path: string): string // Native
// static GetFilename(Path: string): string // Native
// static GetFileNameWithoutExtension(Path: string): string // Native
// static GetFilePathWithoutExtension(Path: string): string // Native
// static GetFileSize(Path: string): number // Native
// static GetLogFileName(): string // Native
// static IsCookedBuild(): boolean // Native
// static LoadFileToBytes(Path: string, StartOffset: number, Length: number): boolean // Native
// static LoadFileToString(Path: string, /* out */ OutText: string): boolean // Native
// static SaveBytesToFile(Path: string): boolean // Native
// static SaveStringToFile(Path: string, Text: string): boolean // Native

/**
 * Class Core.FloatProperty
 * Size: 0x00C8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UFloatProperty = UProperty & {
};

/**
 * Class Core.Function
 * Size: 0x0160
 * Extends: UStruct
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UFunction = UStruct & {
};

/**
 * Class Core.Global_ORS
 * Size: 0x0078
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UGlobal_ORS = UObject & {
};

/**
 * Class Core.Group_ORS
 * Size: 0x0138
 * Extends: UScriptGroup_ORS
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UGroup_ORS = UScriptGroup_ORS & {
};

/**
 * Class Core.HelpCommandlet
 * Size: 0x00B8
 * Extends: UCommandlet
 * Flags: CLASS_Compiled | CLASS_Transient | CLASS_Parsed | CLASS_Localized | CLASS_Native | CLASS_Exported
 */
export type UHelpCommandlet = UCommandlet & {
};

// HelpCommandlet Functions
// Main(Params: string): number

/**
 * Class Core.IDisposable
 * Size: 0x0060
 * Extends: UInterface
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Interface
 */
export type UIDisposable = UInterface & {
};

// IDisposable Functions
// Dispose(): void

/**
 * Class Core.Instance_ORS
 * Size: 0x0110
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UInstance_ORS = UObject & {
};

/**
 * Class Core.Interface
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Interface | CLASS_Exported
 */
export type UInterface = UObject & {
};

/**
 * Class Core.InterfaceProperty
 * Size: 0x00D8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UInterfaceProperty = UProperty & {
};

/**
 * Class Core.IntProperty
 * Size: 0x00C8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UIntProperty = UProperty & {
};

/**
 * Class Core.Linker
 * Size: 0x01E8
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type ULinker = UObject & {
};

/**
 * Class Core.LinkerLoad
 * Size: 0x0810
 * Extends: ULinker
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type ULinkerLoad = ULinker & {
};

/**
 * Class Core.LinkerSave
 * Size: 0x02A8
 * Extends: ULinker
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type ULinkerSave = ULinker & {
};

/**
 * Class Core.MapProperty
 * Size: 0x00D8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UMapProperty = UProperty & {
};

/**
 * Class Core.MetaData
 * Size: 0x00B0
 * Extends: UObject
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UMetaData = UObject & {
};

/**
 * Class Core.NameProperty
 * Size: 0x00C8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UNameProperty = UProperty & {
};

/**
 * Class Core.Object
 * Size: 0x0060
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_NoExport
 */
export type UObject = {
  readonly address: bigint;
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Name: FName;  // 0x0048 (0x0008) [FName]
};

// Object Functions
// static Abs(A: number): number // Native
// static Acos(A: number): number // Native
// static Add_ColorColor(): void
// static Add_FloatFloat(A: number, B: number): number // Native
// static Add_IntInt(A: number, B: number): number // Native
// static Add_QuatQuat(): void // Native
// static Add_QWordQWord(A: bigint, B: bigint): bigint // Native
// static Add_RotatorRotator(): void // Native
// static Add_Vector2DVector2D(): void // Native
// static Add_VectorVector(): void // Native
// static AddAdd_Byte(): void // Native
// static AddAdd_Int(/* out */ A: number): number // Native
// static AddAdd_PreByte(): void // Native
// static AddAdd_PreInt(/* out */ A: number): number // Native
// static AddEqual_ByteByte(): void // Native
// static AddEqual_FloatFloat(/* out */ A: number, B: number): number // Native
// static AddEqual_IntInt(/* out */ A: number, B: number): number // Native
// static AddEqual_QWordQWord(/* out */ A: bigint, B: bigint): bigint // Native
// static AddEqual_RotatorRotator(): void // Native
// static AddEqual_Vector2DVector2D(): void // Native
// static AddEqual_VectorVector(): void // Native
// static And_IntInt(A: number, B: number): number // Native
// static AndAnd_BoolBool(A: boolean, B: boolean): boolean // Native
// static Asc(S: string): number // Native
// static Asin(A: number): number // Native
// static At_StrStr(A: string, B: string): string // Native
// static Atan(A: number): number // Native
// static Atan2(A: number, B: number): number // Native
// static AtEqual_StrStr(/* out */ A: string, B: string): string // Native
// static AutoSetTangentsFloat(): void // Native
// static AutoSetTangentsVector(): void // Native
// BeginState(PreviousStateName: FName): void
// static CalculateGravityPosition(Gravity: number, Time: number): void
// static Caps(S: string): string // Native
// static Chr(I: number): string // Native
// static Clamp(V: number, A: number, B: number): number // Native
// static ClampLength(MaxLength: number): void // Native
// static ClampRotAxis(ViewAxis: number, /* out */ out_DeltaViewAxis: number, MaxLimit: number, MinLimit: number): void
// static ClampRotAxisFromBase(Current: number, Center: number, MaxDelta: number): number
// static ClampRotAxisFromRange(Current: number, Min: number, Max: number): number
// static ClassIsChildOf(): boolean // Native
// static ClockwiseFrom_IntInt(A: number, B: number): boolean // Native
// static ColorToInt(): number // Native
// static ColorToLinearColor(): void // Native
// static Complement_PreInt(A: number): number // Native
// static ComplementEqual_FloatFloat(A: number, B: number): boolean // Native
// static ComplementEqual_StrStr(A: string, B: string): boolean // Native
// static Concat_StrStr(A: string, B: string): string // Native
// static ConcatEqual_StrStr(/* out */ A: string, B: string): string // Native
// Construct(): void
// static ContainsWhitespace(Text: string): boolean // Native
// ContinuedState(): void
// static ConvertFromSRGB(): void // Native
// static Cos(A: number): number // Native
// static CreateGuid(): void // Native
// static CreateGuidString(): string
// static Cross_VectorVector(): void // Native
// static DebugBreak(UserFlags: number): void // Native
// Disable(ProbeFunc: FName): void // Native
// static Divide_FloatFloat(A: number, B: number): number // Native
// static Divide_IntInt(A: number, B: number): number // Native
// static Divide_QWordQWord(A: bigint, B: bigint): bigint // Native
// static Divide_RotatorFloat(B: number): void // Native
// static Divide_Vector2DFloat(B: number): void // Native
// static Divide_VectorFloat(B: number): void // Native
// static DivideEqual_ByteByte(): void // Native
// static DivideEqual_FloatFloat(/* out */ A: number, B: number): number // Native
// static DivideEqual_IntFloat(/* out */ A: number, B: number): number // Native
// static DivideEqual_RotatorFloat(B: number): void // Native
// static DivideEqual_Vector2DFloat(B: number): void // Native
// static DivideEqual_VectorFloat(B: number): void // Native
// static Dot_Vector2DVector2D(): number // Native
// static Dot_VectorVector(): number // Native
// DumpStateStack(): void // Native
// DuplicateObject(): void // Native
// static DynamicLoadObject(ObjectName: string, MayFail: boolean): void // Native
// Enable(ProbeFunc: FName): void // Native
// EndState(NextStateName: FName): void
// static EnumFromString(ValueName: FName): number // Native
// static EqualEqual_BoolBool(A: boolean, B: boolean): boolean // Native
// static EqualEqual_FloatFloat(A: number, B: number): boolean // Native
// static EqualEqual_InterfaceInterface(): boolean // Native
// static EqualEqual_IntInt(A: number, B: number): boolean // Native
// static EqualEqual_NameName(A: FName, B: FName): boolean // Native
// static EqualEqual_ObjectObject(): boolean // Native
// static EqualEqual_QWordInt(A: bigint, B: number): boolean // Native
// static EqualEqual_QWordQWord(A: bigint, B: bigint): boolean // Native
// static EqualEqual_RotatorRotator(): boolean // Native
// static EqualEqual_StrStr(A: string, B: string): boolean // Native
// static EqualEqual_VectorVector(): boolean // Native
// static EvalInterpCurveFloat(InVal: number): number // Native
// static EvalInterpCurveVector(InVal: number): void // Native
// static EvalInterpCurveVector2D(InVal: number): void // Native
// static Exp(A: number): number // Native
// static FCeil(A: number): number // Native
// static FClamp(V: number, A: number, B: number): number // Native
// static FCubicInterp(P0: number, T0: number, P1: number, T1: number, A: number): number // Native
// static FFloor(A: number): number // Native
// static FindDeltaAngle(A1: number, A2: number): number
// static FindObject(ObjectName: string): void // Native
// FindProperty(PropertyName: FName): void // Native
// FindStructProperty(PropertyName: FName, StructName: FName): void // Native
// static FInterpConstantTo(Current: number, Target: number, DeltaTime: number, InterpSpeed: number): number // Native
// static FInterpEaseIn(A: number, B: number, Alpha: number, Exp: number): number // Native
// static FInterpEaseInOut(A: number, B: number, Alpha: number, Exp: number): number // Native
// static FInterpEaseOut(A: number, B: number, Alpha: number, Exp: number): number // Native
// static FInterpTo(Current: number, Target: number, DeltaTime: number, InterpSpeed: number): number // Native
// static FlattenRotatorOnAxis(): void
// FlattenVector(): void
// FloatToRangeByteSigned(inputFloat: number): void // Native
// FloatToRangeByteUnsigned(inputFloat: number): void // Native
// static FloorLog2(Value: number): number // Native
// static FMax(A: number, B: number): number // Native
// static FMin(A: number, B: number): number // Native
// static FormatTime(Seconds: number): string
// static FPctByRange(Value: number, InMin: number, InMax: number): number
// static FRand(): number // Native
// static FromHex(Hex: string): number // Native
// static FromHexColor(Hex: string): void
// static FSmoothInterpTo(From: number, To: number, Lambda: number, DeltaTime: number): number
// static GetAngularDegreesFromRadians(): void
// static GetAngularDistance(): boolean // Native
// static GetAngularFromDotDist(): void // Native
// GetAppSeconds(): number // Native
// static GetAxes(): void // Native
// GetBuildChangelistNumber(): number // Native
// static GetCurrentTime(): number // Native
// static GetDotDistance(): boolean // Native
// GetEngineVersion(): number // Native
// static GetEnum(I: number): FName // Native
// static GetFrameCounter(): bigint // Native
// static GetFuncName(): FName // Native
// static GetGuidFromString(/* out */ InGuidString: string): void // Native
// static GetHeadingAngle(): number
// static GetLanguage(): string // Native
// static GetMappedRangeValue(Value: number): number // Native
// GetMaxColorBrightness(): void
// GetMaxLinearColorBrightness(): void // Native
// static GetObjectProvider(): unknown // Native
// GetPackageName(): FName
// GetPathName(): string
// static GetPerObjectConfigObjects(MaxResults: number): void // Native
// static GetPerObjectConfigSections(MaxResults: number): boolean // Native
// static GetRadiansBetweenVectors(): number
// GetRandomOptionSumFrequency(): number
// static GetRangePctByValue(Value: number): number
// static GetRangeValueByPct(Pct: number): number
// GetRealArchetypeName(): FName // Native
// static GetRightMost(Text: string): string
// static GetRotatorAxis(Axis: number): void // Native
// static GetScaledAxisValue(Value: number, Sensitivity: number, MaxSensitivity: number): number // Native
// static GetScriptTrace(): string // Native
// static GetSingleton(): void // Native
// static GetSmoothInterpLerpValue(Lambda: number, DeltaTime: number): number
// GetStateName(): FName // Native
// static GetStringFromGuid(): string // Native
// GetSystemTime(/* out */ Year: number, /* out */ Month: number, /* out */ DayOfWeek: number, /* out */ Day: number, /* out */ Hour: number, /* out */ Min: number, /* out */ Sec: number, /* out */ MSec: number): void // Native
// static GetTextArchetype(Path: string): void // Native
// static GetTypedOuter(): void // Native
// static GetUnAxes(): void // Native
// GotoState(NewState: FName, Label: FName, bForceEvents: boolean, bKeepStack: boolean): void // Native
// static Greater_FloatFloat(A: number, B: number): boolean // Native
// static Greater_IntInt(A: number, B: number): boolean // Native
// static Greater_QWordQWord(A: bigint, B: bigint): boolean // Native
// static Greater_StrStr(A: string, B: string): boolean // Native
// static GreaterEqual_FloatFloat(A: number, B: number): boolean // Native
// static GreaterEqual_IntInt(A: number, B: number): boolean // Native
// static GreaterEqual_QWordQWord(A: bigint, B: bigint): boolean // Native
// static GreaterEqual_StrStr(A: string, B: string): boolean // Native
// static GreaterGreater_IntInt(A: number, B: number): number // Native
// static GreaterGreater_VectorRotator(): void // Native
// static GreaterGreaterGreater_IntInt(A: number, B: number): number // Native
// static HSVtoRGB(): void // Native
// static ImportJSON(PropertyName: string, /* out */ JSON: string): void // Native
// InCylinder(Width: number, bIgnoreZ: boolean): boolean
// static InStr(S: string, T: string, bSearchFromRight: boolean, bIgnoreCase: boolean, StartPos: number): number // Native
// static IntToColor(I: number): void // Native
// static IntToLinearColor(I: number): void
// static InvalidateGuid(): void // Native
// static InverseTransformNormal(): void // Native
// static InverseTransformVector(): void // Native
// IsA(ClassName: FName): boolean // Native
// IsArchetype(): boolean // Native
// static IsAutomationTest(): boolean // Native
// IsChildState(TestState: FName, TestParentState: FName): boolean // Native
// static IsGuidValid(): boolean // Native
// IsInState(TestState: FName, bTestStateStack: boolean): boolean // Native
// IsPendingKill(): boolean // Native
// static IsUTracing(): boolean // Native
// static IsZero(): boolean // Native
// static JoinArray(/* out */ out_Result: string, delim: string, bIgnoreBlanks: boolean): void // Native
// static JoinArrayInt(delim: string, bIgnoreBlanks: boolean): string
// static JoinArrayName(delim: string, bIgnoreBlanks: boolean): string
// static JoinArrayQWord(delim: string, bIgnoreBlanks: boolean): string
// static JoinArrayStr(delim: string, bIgnoreBlanks: boolean): string
// static LABtoRGB(): void // Native
// static Left(S: string, I: number): string // Native
// static Len(S: string): number // Native
// static Lerp(A: number, B: number, Alpha: number): number // Native
// static LerpColor(Alpha: number): void // Native
// static Less_FloatFloat(A: number, B: number): boolean // Native
// static Less_IntInt(A: number, B: number): boolean // Native
// static Less_QWordQWord(A: bigint, B: bigint): boolean // Native
// static Less_StrStr(A: string, B: string): boolean // Native
// static LessEqual_FloatFloat(A: number, B: number): boolean // Native
// static LessEqual_IntInt(A: number, B: number): boolean // Native
// static LessEqual_QWordQWord(A: bigint, B: bigint): boolean // Native
// static LessEqual_StrStr(A: string, B: string): boolean // Native
// static LessLess_IntInt(A: number, B: number): number // Native
// static LessLess_VectorRotator(): void // Native
// static LinearColorLerp(Alpha: number): void
// static LinearColorToColor(): void
// static LinearColorToInt(): number
// LinePlaneIntersection(/* out */ Out_T: number, bCheckLineSegment: boolean): boolean
// static LoadSeekFreeObject(Path: string): void // Native
// static Localize(SectionName: string, KeyName: string, PackageName: string, bOptional: boolean): string // Native
// static Locs(S: string): string // Native
// static Loge(A: number): number // Native
// static LogInternal(S: string, Tag: FName, bFileOnly: boolean): void // Native
// static MakeAsciiSafe(InStr: string): string
// static MakeColor(): void
// static MakeLinearColor(R: number, G: number, B: number, A: number): void // Native
// static MakeQuat(X: number, Y: number, Z: number, W: number): void
// static MakeRotationMatrix(): void // Native
// static MakeRotationTranslationMatrix(): void // Native
// static MakeRotator(Pitch: number, Yaw: number, Roll: number): void
// static MakeVector(X: number, Y: number, Z: number): void
// static MakeVector2D(X: number, Y: number): void
// MarkPendingKill(): void // Native
// static MatrixGetAxis(): void // Native
// static MatrixGetOrigin(): void // Native
// static MatrixGetRotator(): void // Native
// static Max(A: number, B: number): number // Native
// static Mid(S: string, I: number, J: number): string // Native
// static Min(A: number, B: number): number // Native
// static MirrorVectorByNormal(): void // Native
// static Multiply_ColorFloat(B: number): void
// static Multiply_FloatColor(A: number): void
// static Multiply_FloatFloat(A: number, B: number): number // Native
// static Multiply_FloatRotator(A: number): void // Native
// static Multiply_FloatVector(A: number): void // Native
// static Multiply_IntInt(A: number, B: number): number // Native
// static Multiply_LinearColorFloat(Mult: number): void
// static Multiply_MatrixMatrix(): void // Native
// static Multiply_QWordQWord(A: bigint, B: bigint): bigint // Native
// static Multiply_RotatorFloat(B: number): void // Native
// static Multiply_Vector2DFloat(B: number): void // Native
// static Multiply_VectorFloat(B: number): void // Native
// static Multiply_VectorVector(): void // Native
// static MultiplyEqual_ByteByte(): void // Native
// static MultiplyEqual_ByteFloat(B: number): void // Native
// static MultiplyEqual_FloatFloat(/* out */ A: number, B: number): number // Native
// static MultiplyEqual_IntFloat(/* out */ A: number, B: number): number // Native
// static MultiplyEqual_RotatorFloat(B: number): void // Native
// static MultiplyEqual_Vector2DFloat(B: number): void // Native
// static MultiplyEqual_VectorFloat(B: number): void // Native
// static MultiplyEqual_VectorVector(): void // Native
// static MultiplyMultiply_FloatFloat(Base: number, Exp: number): number // Native
// NewInstance(ObjName: FName): void // Native
// static Normal(): void // Native
// static Normal2D(): void // Native
// static Normalize(): void // Native
// static NormalizeRotAxis(Angle: number): number // Native
// static Not_PreBool(A: boolean): boolean // Native
// static NotEqual_BoolBool(A: boolean, B: boolean): boolean // Native
// static NotEqual_FloatFloat(A: number, B: number): boolean // Native
// static NotEqual_InterfaceInterface(): boolean // Native
// static NotEqual_IntInt(A: number, B: number): boolean // Native
// static NotEqual_NameName(A: FName, B: FName): boolean // Native
// static NotEqual_ObjectObject(): boolean // Native
// static NotEqual_QWordInt(A: bigint, B: number): boolean // Native
// static NotEqual_QWordQWord(A: bigint, B: bigint): boolean // Native
// static NotEqual_RotatorRotator(): boolean // Native
// static NotEqual_StrStr(A: string, B: string): boolean // Native
// static NotEqual_VectorVector(): boolean // Native
// static NotNone(): boolean
// static NoZDot(): number // Native
// static Or_IntInt(A: number, B: number): number // Native
// static OrOr_BoolBool(A: boolean, B: boolean): boolean // Native
// static OrthoRotation(): void // Native
// static PadRight(S: string, WidthChars: number): string
// static PadString(Str: string, Characters: number): string
// static ParseLocalizedPropertyPath(PathName: string): string
// static ParseStringIntoArray(BaseString: string, delim: string, bCullEmpty: boolean): void // Native
// static PathName(): string // Native
// PausedState(): void
// static Percent_FloatFloat(A: number, B: number): number // Native
// static Percent_IntInt(A: number, B: number): number // Native
// static PointDistToLine(): number // Native
// PointDistToPlane(): number
// PointDistToSegment(): number // Native
// static PointProjectToPlane(): void // Native
// PoppedState(): void
// PopState(bPopAll: boolean): void // Native
// PrintDebugInfo(): void
// static ProfNodeEvent(EventName: string): void // Native
// static ProfNodeSetDepthThreshold(Depth: number): void // Native
// static ProfNodeSetTimeThresholdSeconds(Threshold: number): void // Native
// static ProfNodeStart(TimerName: string): number // Native
// static ProfNodeStop(AssumedTimerIndex: number): void // Native
// static ProjectOnTo(): void // Native
// static ProjectOnToPlane(OverBounce: number): void // Native
// PushedState(): void
// PushState(NewState: FName, NewLabel: FName): void // Native
// static QMax(A: bigint, B: bigint): bigint // Native
// static QMin(A: bigint, B: bigint): bigint // Native
// static QSubtract(A: bigint, B: bigint): bigint // Native
// static QuatDot(): number // Native
// static QuatFindBetween(): void // Native
// static QuatFromAxisAndAngle(Angle: number): void // Native
// static QuatFromRotator(): void // Native
// static QuatInvert(): void // Native
// static QuatProduct(): void // Native
// static QuatRotateVector(): void // Native
// static QuatSlerp(Alpha: number, bShortestPath: boolean): void // Native
// static QuatToRotator(): void // Native
// static Rand(Max: number): number // Native
// static RandRange(InMin: number, InMax: number): number
// static RandSign(Value: number): number
// RangeByteToFloatSigned(): number // Native
// RangeByteToFloatUnsigned(): number // Native
// static RDiff(): number // Native
// static RepeatString(InValue: string, Count: number): string
// static Repl(Src: string, Match: string, With: string, bCaseSensitive: boolean): string // Native
// static RGBtoHSV(): void // Native
// static RGBtoLAB(): void // Native
// static Right(S: string, I: number): string // Native
// static RInterpTo(DeltaTime: number, InterpSpeed: number, bConstantInterpSpeed: boolean): void // Native
// static RLerp(Alpha: number, bShortestPath: boolean): void // Native
// static RotateRotator(Amount: number): void
// static RotatorFromInt(RotationPitchAndYaw: number): void
// static RotatorToInt(): number
// static RotRand(bRoll: boolean): void // Native
// static Round(A: number): number // Native
// static RSize(): number // Native
// static RSmoothInterpTo(Lambda: number, DeltaTime: number): void
// static RTransform(): void // Native
// RunningAverage(OldAverage: number, NewValue: number, NewCount: number): number // Native
// SaveConfig(): void // Native
// static SClampRotAxis(DeltaTime: number, ViewAxis: number, /* out */ out_DeltaViewAxis: number, MaxLimit: number, MinLimit: number, InterpolationSpeed: number): boolean
// static ScriptTrace(): void // Native
// SetRooted(bRooted: boolean): void // Native
// static SetUTracing(bShouldUTrace: boolean): void // Native
// Sign(X: number): number // Native
// static Sin(A: number): number // Native
// SolveVelocityQuadratic(Distance: number, Speed: number, Accel: number, /* out */ Time: number): boolean // Native
// static SortAscendingFloat(A: number, B: number): number
// static SortAscendingInt(A: number, B: number): number
// static SortAscendingQWORD(A: bigint, B: bigint): number
// static SortAscendingString(A: string, B: string): number
// static SortDescendingFloat(A: number, B: number): number
// static SortDescendingInt(A: number, B: number): number
// static SortDescendingQWORD(A: bigint, B: bigint): number
// static SortDescendingString(A: string, B: string): number
// static Split(Text: string, SplitStr: string, bOmitSplitStr: boolean): string
// static SplitString(Source: string, Delimiter: string, bCullEmpty: boolean): void
// static Sqrt(A: number): number // Native
// static Square(A: number): number // Native
// static StartsWith(Src: string, Prefix: string): boolean // Native
// static StaticSaveConfig(): void // Native
// static Subtract_ColorColor(): void
// static Subtract_FloatFloat(A: number, B: number): number // Native
// static Subtract_IntInt(A: number, B: number): number // Native
// static Subtract_LinearColorLinearColor(): void
// static Subtract_PreFloat(A: number): number // Native
// static Subtract_PreInt(A: number): number // Native
// static Subtract_PreVector(): void // Native
// static Subtract_QuatQuat(): void // Native
// static Subtract_QWordQWord(A: bigint, B: bigint): number // Native
// static Subtract_RotatorRotator(): void // Native
// static Subtract_Vector2DVector2D(): void // Native
// static Subtract_VectorVector(): void // Native
// static SubtractEqual_ByteByte(): void // Native
// static SubtractEqual_FloatFloat(/* out */ A: number, B: number): number // Native
// static SubtractEqual_IntInt(/* out */ A: number, B: number): number // Native
// static SubtractEqual_QWordQWord(/* out */ A: bigint, B: bigint): bigint // Native
// static SubtractEqual_RotatorRotator(): void // Native
// static SubtractEqual_StrStr(/* out */ A: string, B: string): string // Native
// static SubtractEqual_Vector2DVector2D(): void // Native
// static SubtractEqual_VectorVector(): void // Native
// static SubtractSubtract_Byte(): void // Native
// static SubtractSubtract_Int(/* out */ A: number): number // Native
// static SubtractSubtract_PreByte(): void // Native
// static SubtractSubtract_PreInt(/* out */ A: number): number // Native
// static SumFloat(Total: number, Value: number): number
// static SumInt(Total: number, Value: number): number
// static Swap(): void
// static SwapArrayItems(): void
// static Tan(A: number): number // Native
// static TCharToUTF8(Src: string): string // Native
// TimeStamp(): string // Native
// static ToHex(A: number): string // Native
// ToJson(): string // Native
// static TransformNormal(): void // Native
// static TransformVector(): void // Native
// TransformVectorByRotation(bInverse: boolean): void // Native
// static Trim(Src: string): string // Native
// UnsubscribeFromAllEvents(): void // Native
// static UnwindHeading(A: number): number
// static UTF8ToTChar(Src: string): string // Native
// static V2DNormal(): void // Native
// static V2DSize(): number // Native
// static V2DSizeSq(): number // Native
// static VAbs(): void
// static VClamp(): void
// static vect2d(InX: number, InY: number): void
// static vect3d(X: number, Y: number, Z: number): void
// static VInterpConstantTo(DeltaTime: number, InterpSpeed: number): void // Native
// static VInterpTo(DeltaTime: number, InterpSpeed: number): void // Native
// static VLerp(Alpha: number): void // Native
// static VRand(): void // Native
// static VRandCone(ConeHalfAngleRadians: number): void // Native
// static VRandCone2(HorizontalConeHalfAngleRadians: number, VerticalConeHalfAngleRadians: number): void // Native
// static VSize(): number // Native
// static VSize2D(): number // Native
// static VSizeSq(): number // Native
// static VSizeSq2D(): number // Native
// static VSmoothInterpTo(Lambda: number, DeltaTime: number): void
// static WarnInternal(S: string): void // Native
// static Xor_IntInt(A: number, B: number): number // Native
// static XorXor_BoolBool(A: boolean, B: boolean): boolean // Native

/**
 * Class Core.ObjectProperty
 * Size: 0x00D8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UObjectProperty = UProperty & {
};

/**
 * Class Core.ObjectProvider
 * Size: 0x01E0
 * Extends: UComponent
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_HasComponents | CLASS_Exported
 */
export type UObjectProvider = UComponent & {
  VfTable_FObjectDestructionSubscriber: unknown;  // 0x0070 (0x0008) [unknown]
  Parent: unknown;  // 0x0160 (0x0008) [unknown]
  __ObjectSubscriptionCallback__Delegate: FScriptDelegate;  // 0x0198 (0x0018) [FScriptDelegate]
  __ObjectListSubscriptionCallback__Delegate: FScriptDelegate;  // 0x01b0 (0x0018) [FScriptDelegate]
  __ObjectChangeCallback__Delegate: FScriptDelegate;  // 0x01c8 (0x0018) [FScriptDelegate]
};

// ObjectProvider Functions
// AddAndRemoveObjects(): void // Native
// AddObject(): void // Native
// AddObjects(): void // Native
// AddProxy(InProxy: unknown): void // Native
// AllObjects(): void // Native
// Get(): void // Native
// GetCount(): number // Native
// GetExact(): void // Native
// GetExactCount(): number // Native
// GetOrCreate(): void // Native
// GetUnsafe(): void // Native
// Inject(): void // Native
// InjectDelayed(): void // Native
// IsRegisteredForInjection(): boolean // Native
// ObjectChangeCallback(): void
// ObjectListSubscriptionCallback(Provider: unknown): void
// ObjectSubscriptionCallback(): void
// RemoveAllObjects(): void // Native
// RemoveObject(): void // Native
// RemoveObjects(): void // Native
// RemoveProxy(InProxy: unknown): void // Native
// Replace(): void // Native
// SetParent(InParent: unknown): void // Native
// SetSingleton(): void // Native
// Subscribe(OnAdd: FScriptDelegate, OnRemove: FScriptDelegate): void // Native
// SubscribeList(Callback: FScriptDelegate): void // Native
// SubscribeOnce(OnAdd: FScriptDelegate, OnRemove: FScriptDelegate): void // Native
// Unsubscribe(Callback: FScriptDelegate, Callback2: FScriptDelegate): void // Native
// UnsubscribeAll(): void // Native

/**
 * Class Core.ObjectRedirector
 * Size: 0x0068
 * Extends: UObject
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UObjectRedirector = UObject & {
};

/**
 * Class Core.ObjectSerializer
 * Size: 0x0070
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UObjectSerializer = UObject & {
};

/**
 * Class Core.ObjectUtil
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UObjectUtil = UObject & {
};

// ObjectUtil Functions
// static AllCDOs(bIncludeAbstract: boolean): void // Native
// static ClearNaNValues(): void // Native
// static FindClass(ClassName: FName): void // Native
// static GetCDO(): void // Native
// static Identical(): boolean // Native
// static IdenticalDeep(): boolean // Native
// static InitProperties(): void // Native

/**
 * Class Core.Package
 * Size: 0x0148
 * Extends: UObject
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UPackage = UObject & {
};

/**
 * Class Core.PackageMap
 * Size: 0x0118
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UPackageMap = UObject & {
};

/**
 * Class Core.Property
 * Size: 0x00C8
 * Extends: UField
 * Flags: CLASS_Abstract | CLASS_Native | CLASS_Intrinsic
 */
export type UProperty = UField & {
};

/**
 * Class Core.PropertyChangeDispatcher
 * Size: 0x0070
 * Extends: UObject
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UPropertyChangeDispatcher = UObject & {
};

/**
 * Class Core.QWordProperty
 * Size: 0x00C8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UQWordProperty = UProperty & {
};

/**
 * Class Core.RotatorConversions
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed
 */
export type URotatorConversions = UObject & {
};

// RotatorConversions Functions
// static GetAsDegrees(): void
// static GetAsRadians(): void

/**
 * Class Core.ScriptStruct
 * Size: 0x0158
 * Extends: UStruct
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UScriptStruct = UStruct & {
};

/**
 * Class Core.State
 * Size: 0x0190
 * Extends: UStruct
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UState = UStruct & {
};

/**
 * Class Core.StringMap
 * Size: 0x00D8
 * Extends: UComponent
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UStringMap = UComponent & {
  __PairCallback__Delegate: FScriptDelegate;  // 0x00c0 (0x0018) [FScriptDelegate]
};

// StringMap Functions
// Append(Other: unknown): void // Native
// Contains(Key: string): boolean // Native
// ForEach(Callback: FScriptDelegate): void // Native
// Get(Key: string): string // Native
// PairCallback(Key: string, Value: string): void
// Remove(Key: string): void // Native
// Set(Key: string, Value: string): void // Native
// TryGet(Key: string, /* out */ OutValue: string): boolean // Native

/**
 * Class Core.StringObjectMap
 * Size: 0x00C0
 * Extends: UComponent
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UStringObjectMap = UComponent & {
};

// StringObjectMap Functions
// Contains(Key: string): boolean // Native
// Get(): void
// GetObject(Key: string): void // Native
// Remove(Key: string): void // Native
// Set(Key: string): void // Native
// TryGet(): void
// TryGetObject(Key: string): boolean // Native

/**
 * Class Core.StrProperty
 * Size: 0x00C8
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UStrProperty = UProperty & {
};

/**
 * Class Core.Struct
 * Size: 0x0130
 * Extends: UField
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UStruct = UField & {
};

/**
 * Class Core.StructProperty
 * Size: 0x00D0
 * Extends: UProperty
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UStructProperty = UProperty & {
};

/**
 * Class Core.Subscription
 * Size: 0x0078
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type USubscription = UObject & {
  __SubscriberCallback__Delegate: FScriptDelegate;  // 0x0060 (0x0018) [FScriptDelegate]
};

// Subscription Functions
// static __Subscription__TriggerAll_0x1(): void
// static Create(InCallback: FScriptDelegate): void
// Dispose(): void
// static GetNone(): void // Native
// SetCallback(InCallback: FScriptDelegate): void
// SubscriberCallback(): void
// static TriggerAll(): void
// TriggerCallback(): void

/**
 * Class Core.SubscriptionCollection_ORS
 * Size: 0x0080
 * Extends: UObject
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type USubscriptionCollection_ORS = UObject & {
};

/**
 * Class Core.Subsystem
 * Size: 0x0068
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Transient | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type USubsystem = UObject & {
  VfTable_FExec: unknown;  // 0x0060 (0x0008) [unknown]
};

/**
 * Class Core.System
 * Size: 0x0160
 * Extends: USubsystem
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type USystem = USubsystem & {
  StaleCacheDays: number;  // 0x0068 (0x0004) [int32]
  MaxStaleCacheSize: number;  // 0x006c (0x0004) [int32]
  MaxOverallCacheSize: number;  // 0x0070 (0x0004) [int32]
  PackageSizeSoftLimit: number;  // 0x0074 (0x0004) [int32]
  AsyncIOBandwidthLimit: number;  // 0x0078 (0x0004) [float]
  SavePath: string;  // 0x0080 (0x0010) [FString]
  CachePath: string;  // 0x0090 (0x0010) [FString]
  CacheExt: string;  // 0x00a0 (0x0010) [FString]
  Paths: unknown[];  // 0x00b0 (0x0010) [TArray<unknown>]
  SeekFreePCPaths: unknown[];  // 0x00c0 (0x0010) [TArray<unknown>]
  ScriptPaths: unknown[];  // 0x00d0 (0x0010) [TArray<unknown>]
  FRScriptPaths: unknown[];  // 0x00e0 (0x0010) [TArray<unknown>]
  CutdownPaths: unknown[];  // 0x00f0 (0x0010) [TArray<unknown>]
  Suppress: unknown[];  // 0x0100 (0x0010) [TArray<unknown>]
  SuppressPublic: unknown[];  // 0x0110 (0x0010) [TArray<unknown>]
  Extensions: unknown[];  // 0x0120 (0x0010) [TArray<unknown>]
  SeekFreePCExtensions: unknown[];  // 0x0130 (0x0010) [TArray<unknown>]
  LocalizationPaths: unknown[];  // 0x0140 (0x0010) [TArray<unknown>]
  TextureFileCacheExtension: string;  // 0x0150 (0x0010) [FString]
};

/**
 * Class Core.TAsyncResult
 * Size: 0x00D0
 * Extends: UAsyncTask
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_NoExport
 */
export type UTAsyncResult = UAsyncTask & {
};

/**
 * Class Core.TextBuffer
 * Size: 0x0090
 * Extends: UObject
 * Flags: CLASS_Native | CLASS_Intrinsic
 */
export type UTextBuffer = UObject & {
};

/**
 * Class Core.TextBufferFactory
 * Size: 0x00B8
 * Extends: UFactory
 * Flags: CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UTextBufferFactory = UFactory & {
};

/**
 * Class Core.UTF8
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UUTF8 = UObject & {
};

// UTF8 Functions
// static Decode(): string // Native
// static DecodeInline(/* out */ Output: string): void // Native
// static Encode(Input: string): void // Native
// static EncodeInline(Input: string): void // Native
