/**
 * GFxUI Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { FScriptDelegate } from '../structs/Core';
import type { UObject } from './Core';
import type { UInteraction, USequenceAction, USequenceEvent } from './Engine';

/**
 * Class GFxUI.FlashMovie
 * Size: 0x0128
 * Extends: USwfMovie
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_EditInlineNew | CLASS_Exported
 */
export type UFlashMovie = USwfMovie & {
};

/**
 * Class GFxUI.GFxAction_CloseMovie
 * Size: 0x016C
 * Extends: USequenceAction
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxAction_CloseMovie = USequenceAction & {
  bUnload: boolean;  // 0x0168 (0x0004) [bool : 0x1]
};

// GFxAction_CloseMovie Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_GetVariable
 * Size: 0x0178
 * Extends: USequenceAction
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxAction_GetVariable = USequenceAction & {
  Variable: string;  // 0x0168 (0x0010) [FString]
};

// GFxAction_GetVariable Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_Invoke
 * Size: 0x0188
 * Extends: USequenceAction
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxAction_Invoke = USequenceAction & {
  MethodName: string;  // 0x0168 (0x0010) [FString]
};

// GFxAction_Invoke Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_OpenMovie
 * Size: 0x01A8
 * Extends: USequenceAction
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxAction_OpenMovie = USequenceAction & {
  bTakeFocus: boolean;  // 0x0178 (0x0004) [bool : 0x1]
  bCaptureInput: boolean;  // 0x0178 (0x0004) [bool : 0x2]
  bStartPaused: boolean;  // 0x0178 (0x0004) [bool : 0x4]
  bEnableGammaCorrection: boolean;  // 0x0178 (0x0004) [bool : 0x8]
  bDisplayWithHudOff: boolean;  // 0x0178 (0x0004) [bool : 0x10]
};

// GFxAction_OpenMovie Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxAction_SetCaptureKeys
 * Size: 0x0178
 * Extends: USequenceAction
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxAction_SetCaptureKeys = USequenceAction & {
};

/**
 * Class GFxUI.GFxAction_SetVariable
 * Size: 0x0178
 * Extends: USequenceAction
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxAction_SetVariable = USequenceAction & {
  Variable: string;  // 0x0168 (0x0010) [FString]
};

// GFxAction_SetVariable Functions
// IsValidLevelSequenceObject(): boolean

/**
 * Class GFxUI.GFxClikWidget
 * Size: 0x00B8
 * Extends: UGFxObject
 * Flags: CLASS_Compiled | CLASS_Parsed
 */
export type UGFxClikWidget = UGFxObject & {
  __EventListener__Delegate: FScriptDelegate;  // 0x00a0 (0x0018) [FScriptDelegate]
};

// GFxClikWidget Functions
// AddEventListener(Type: FName, Listener: FScriptDelegate, useCapture: boolean, listenerPriority: number, useWeakReference: boolean): void
// AS3AddEventListener(Type: string, useCapture: boolean, listenerPriority: number, useWeakReference: boolean): void
// ASAddEventListener(Type: string, func: string): void
// ASRemoveAllEventListeners(Event: string): void
// EventListener(): void
// GetEventStringFromTypename(Typename: FName): string
// RemoveAllEventListeners(Event: string): void
// SetListener(Member: string, Listener: FScriptDelegate): void

/**
 * Class GFxUI.GFxEngine
 * Size: 0x0128
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed | CLASS_Localized | CLASS_Native | CLASS_Exported
 */
export type UGFxEngine = UObject & {
  RefCount: number;  // 0x0070 (0x0004) [int32]
};

// GFxEngine Functions
// Tick(DeltaTime: number): void
// UpdateMovieLoadingInfo(): void // Native

/**
 * Class GFxUI.GFxEvent_FSCommand
 * Size: 0x01A0
 * Extends: USequenceEvent
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxEvent_FSCommand = USequenceEvent & {
  FSCommand: string;  // 0x0188 (0x0010) [FString]
};

/**
 * Class GFxUI.GFxFSCmdHandler
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Abstract | CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxFSCmdHandler = UObject & {
};

// GFxFSCmdHandler Functions
// FSCommand(Cmd: string, Arg: string): boolean

/**
 * Class GFxUI.GFxFSCmdHandler_Kismet
 * Size: 0x0060
 * Extends: UGFxFSCmdHandler
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxFSCmdHandler_Kismet = UGFxFSCmdHandler & {
};

// GFxFSCmdHandler_Kismet Functions
// FSCommand(Cmd: string, Arg: string): boolean // Native

/**
 * Class GFxUI.GFxInteraction
 * Size: 0x00DC
 * Extends: UInteraction
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxInteraction = UInteraction & {
  VfTable_FCallbackEventDevice: unknown;  // 0x00d0 (0x0008) [unknown]
  bFakeMobileTouches: boolean;  // 0x00d8 (0x0004) [bool : 0x1]
};

// GFxInteraction Functions
// CloseAllMoviePlayers(): void // Native
// DebugInputKey(ControllerId: number, Key: FName, AmountDepressed: number, bGamepad: boolean): void // Native
// GetFocusMovie(ControllerId: number): void // Native
// NotifyGameSessionEnded(): void // Native
// NotifyPlayerAdded(PlayerIndex: number): void // Native
// NotifyPlayerRemoved(PlayerIndex: number): void // Native
// NotifySplitscreenLayoutChanged(): void // Native

/**
 * Class GFxUI.GFxMoviePlayer
 * Size: 0x0218
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxMoviePlayer = UObject & {
  ASUClasses: Map<unknown, unknown>;  // 0x0078 (0x0050) [TMap<unknown, unknown>]
  ASUObjects: Map<unknown, unknown>;  // 0x00c8 (0x0050) [TMap<unknown, unknown>]
  NextASUObject: number;  // 0x0118 (0x0004) [int32]
  bMovieIsOpen: boolean;  // 0x0128 (0x0004) [bool : 0x1]
  bDisplayWithHudOff: boolean;  // 0x0128 (0x0004) [bool : 0x2]
  bEnableGammaCorrection: boolean;  // 0x0128 (0x0004) [bool : 0x4]
  bWidgetsInitializedThisFrame: boolean;  // 0x0128 (0x0004) [bool : 0x8]
  bLogUnhandedWidgetInitializations: boolean;  // 0x0128 (0x0004) [bool : 0x10]
  bAllowInput: boolean;  // 0x0128 (0x0004) [bool : 0x20]
  bAllowFocus: boolean;  // 0x0128 (0x0004) [bool : 0x40]
  bAutoPlay: boolean;  // 0x0128 (0x0004) [bool : 0x80]
  bPauseGameWhileActive: boolean;  // 0x0128 (0x0004) [bool : 0x100]
  bDisableWorldRendering: boolean;  // 0x0128 (0x0004) [bool : 0x200]
  bCaptureWorldRendering: boolean;  // 0x0128 (0x0004) [bool : 0x400]
  bCloseOnLevelChange: boolean;  // 0x0128 (0x0004) [bool : 0x800]
  bOnlyOwnerFocusable: boolean;  // 0x0128 (0x0004) [bool : 0x1000]
  bForceFullViewport: boolean;  // 0x0128 (0x0004) [bool : 0x2000]
  bDiscardNonOwnerInput: boolean;  // 0x0128 (0x0004) [bool : 0x4000]
  bCaptureInput: boolean;  // 0x0128 (0x0004) [bool : 0x8000]
  bCaptureMouseInput: boolean;  // 0x0128 (0x0004) [bool : 0x10000]
  bIgnoreMouseInput: boolean;  // 0x0128 (0x0004) [bool : 0x20000]
  bIsSplitscreenLayoutModified: boolean;  // 0x0128 (0x0004) [bool : 0x40000]
  bShowHardwareMouseCursor: boolean;  // 0x0128 (0x0004) [bool : 0x80000]
  bForceFullScreen: boolean;  // 0x0128 (0x0004) [bool : 0x100000]
  bBlurLesserMovies: boolean;  // 0x0128 (0x0004) [bool : 0x200000]
  bHideLesserMovies: boolean;  // 0x0128 (0x0004) [bool : 0x400000]
  bIsPriorityBlurred: boolean;  // 0x0128 (0x0004) [bool : 0x800000]
  bIsPriorityHidden: boolean;  // 0x0128 (0x0004) [bool : 0x1000000]
  bIgnoreVisibilityEffect: boolean;  // 0x0128 (0x0004) [bool : 0x2000000]
  bIgnoreBlurEffect: boolean;  // 0x0128 (0x0004) [bool : 0x4000000]
  LocalPlayerOwnerIndex: number;  // 0x0138 (0x0004) [int32]
  WidgetPathBindings: Map<unknown, unknown>;  // 0x01a0 (0x0050) [TMap<unknown, unknown>]
  SplitscreenLayoutYAdjust: number;  // 0x01f8 (0x0004) [int32]
  __OnPostAdvance__Delegate: FScriptDelegate;  // 0x0200 (0x0018) [FScriptDelegate]
};

// GFxMoviePlayer Functions
// ActionScriptConstructor(ClassName: string): void // Native
// ActionScriptFloat(Path: string): number // Native
// ActionScriptInt(Path: string): number // Native
// ActionScriptObject(Path: string): void // Native
// ActionScriptSetFunction(Member: string): void // Native
// ActionScriptString(Path: string): string // Native
// ActionScriptVoid(Path: string): void // Native
// AddCaptureKey(Key: FName): void // Native
// AddFocusIgnoreKey(Key: FName): void // Native
// Advance(Time: number): void // Native
// ApplyPriorityBlurEffect(bRemoveEffect: boolean): void
// ApplyPriorityEffect(bRequestedBlurState: boolean, bRequestedHiddenState: boolean): void
// ApplyPriorityVisibilityEffect(bRemoveEffect: boolean): void
// ClearCaptureKeys(): void // Native
// ClearFocusIgnoreKeys(): void // Native
// Close(Unload: boolean): void // Native
// ConditionalClearPause(): void
// ConsoleCommand(Command: string): void
// CreateArray(): void // Native
// CreateObject(ASClass: string): void // Native
// FilterButtonInput(ControllerId: number, ButtonName: FName): boolean
// FlushPlayerInput(capturekeysonly: boolean): void // Native
// GetAVMVersion(): number // Native
// GetGameViewportClient(): void // Native
// GetLP(): void
// GetPC(): void
// GetVariable(Path: string): void // Native
// GetVariableArray(Path: string, Index: number): boolean // Native
// GetVariableBool(Path: string): boolean // Native
// GetVariableFloatArray(Path: string, Index: number): boolean // Native
// GetVariableInt(Path: string): number // Native
// GetVariableIntArray(Path: string, Index: number): boolean // Native
// GetVariableNumber(Path: string): number // Native
// GetVariableObject(Path: string): void // Native
// GetVariableString(Path: string): string // Native
// GetVariableStringArray(Path: string, Index: number): boolean // Native
// GetVisibleFrameRect(/* out */ x0: number, /* out */ y0: number, /* out */ X1: number, /* out */ Y1: number): void // Native
// Init(): void
// Invoke(method: string): void // Native
// IsHidden(): boolean // Native
// OnCleanup(): void
// OnClose(): void
// OnFocusGained(LocalPlayerIndex: number): void
// OnFocusLost(LocalPlayerIndex: number): void
// OnPostAdvance(DeltaTime: number): void
// PlaySoundFromTheme(EventName: FName, SoundThemeName: FName): void
// PostAdvance(DeltaTime: number): void // Native
// PostWidgetInit(): void
// RenderOnce(): void // Native
// RequestGarbageCollection(bImmediate: boolean): void // Native
// SetAlignment(): void // Native
// SetExternalInterface(): void
// SetExternalTexture(Resource: string): boolean // Native
// SetFullScreen(bFullScreen: boolean): void // Native
// SetHidden(bHidden: boolean): void // Native
// SetMovieCanReceiveFocus(bCanReceiveFocus: boolean): void // Native
// SetMovieCanReceiveInput(bCanReceiveInput: boolean): void // Native
// SetMovieInfo(): void
// SetPause(bPausePlayback: boolean): void // Native
// SetPerspective3D(): void // Native
// SetPriority(): void // Native
// SetTimingMode(): void // Native
// SetVariable(Path: string): void // Native
// SetVariableArray(Path: string, Index: number): boolean // Native
// SetVariableBool(Path: string, B: boolean): void // Native
// SetVariableFloatArray(Path: string, Index: number): boolean // Native
// SetVariableInt(Path: string, I: number): void // Native
// SetVariableIntArray(Path: string, Index: number): boolean // Native
// SetVariableNumber(Path: string, F: number): void // Native
// SetVariableObject(Path: string): void // Native
// SetVariableString(Path: string, S: string): void // Native
// SetVariableStringArray(Path: string, Index: number): boolean // Native
// SetView3D(): void // Native
// SetViewport(X: number, Y: number, Width: number, Height: number): void // Native
// SetViewScaleMode(): void // Native
// SetWidgetPathBinding(Path: FName): void // Native
// Start(StartPaused: boolean): boolean // Native
// UpdateSplitscreenLayout(): void // Native
// WidgetInitialized(WidgetName: FName, WidgetPath: FName): boolean
// WidgetUnloaded(WidgetName: FName, WidgetPath: FName): boolean

/**
 * Class GFxUI.GFxObject
 * Size: 0x00A0
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UGFxObject = UObject & {
  Value: number;  // 0x0060 (0x0030) [int32]
};

// GFxObject Functions
// ActionScriptArray(Path: string): void // Native
// ActionScriptFloat(method: string): number // Native
// ActionScriptInt(method: string): number // Native
// ActionScriptObject(Path: string): void // Native
// ActionScriptSetFunction(Member: string): void // Native
// ActionScriptSetFunctionOn(Member: string): void // Native
// ActionScriptString(method: string): string // Native
// ActionScriptVoid(method: string): void // Native
// AttachMovie(symbolname: string, instancename: string, Depth: number): void // Native
// CreateEmptyMovieClip(instancename: string, Depth: number): void // Native
// Get(Member: string): void // Native
// GetBool(Member: string): boolean // Native
// GetColorTransform(): void // Native
// GetDisplayInfo(): void // Native
// GetDisplayMatrix(): void // Native
// GetDisplayMatrix3D(): void // Native
// GetElement(Index: number): void // Native
// GetElementBool(Index: number): boolean // Native
// GetElementDisplayInfo(Index: number): void // Native
// GetElementDisplayMatrix(Index: number): void // Native
// GetElementFloat(Index: number): number // Native
// GetElementInt(Index: number): number // Native
// GetElementMember(Index: number, Member: string): void // Native
// GetElementMemberBool(Index: number, Member: string): boolean // Native
// GetElementMemberFloat(Index: number, Member: string): number // Native
// GetElementMemberInt(Index: number, Member: string): number // Native
// GetElementMemberObject(Index: number, Member: string): void // Native
// GetElementMemberString(Index: number, Member: string): string // Native
// GetElementObject(Index: number): void // Native
// GetElementString(Index: number): string // Native
// GetFloat(Member: string): number // Native
// GetInt(Member: string): number // Native
// GetObject(Member: string): void // Native
// GetPosition(/* out */ X: number, /* out */ Y: number): boolean // Native
// GetString(Member: string): string // Native
// GetText(): string // Native
// GotoAndPlay(frame: string): void // Native
// GotoAndPlayI(frame: number): void // Native
// GotoAndStop(frame: string): void // Native
// GotoAndStopI(frame: number): void // Native
// Invoke(Member: string): void // Native
// Set(Member: string): void // Native
// SetBool(Member: string, B: boolean): void // Native
// SetColorTransform(): void // Native
// SetDisplayInfo(): void // Native
// SetDisplayMatrix(): void // Native
// SetDisplayMatrix3D(): void // Native
// SetElement(Index: number): void // Native
// SetElementBool(Index: number, B: boolean): void // Native
// SetElementColorTransform(Index: number): void // Native
// SetElementDisplayInfo(Index: number): void // Native
// SetElementDisplayMatrix(Index: number): void // Native
// SetElementFloat(Index: number, F: number): void // Native
// SetElementInt(Index: number, I: number): void // Native
// SetElementMember(Index: number, Member: string): void // Native
// SetElementMemberBool(Index: number, Member: string, B: boolean): void // Native
// SetElementMemberFloat(Index: number, Member: string, F: number): void // Native
// SetElementMemberInt(Index: number, Member: string, I: number): void // Native
// SetElementMemberObject(Index: number, Member: string): void // Native
// SetElementMemberString(Index: number, Member: string, S: string): void // Native
// SetElementObject(Index: number): void // Native
// SetElementPosition(Index: number, X: number, Y: number): void // Native
// SetElementString(Index: number, S: string): void // Native
// SetElementVisible(Index: number, Visible: boolean): void // Native
// SetFloat(Member: string, F: number): void // Native
// SetFunction(Member: string, fname: FName): void // Native
// SetInt(Member: string, I: number): void // Native
// SetObject(Member: string): void // Native
// SetPosition(X: number, Y: number): void // Native
// SetString(Member: string, S: string): void // Native
// SetText(Text: string): void // Native
// SetVisible(Visible: boolean): void // Native
// static TranslateString(StringToTranslate: string): string // Native
// WidgetInitialized(WidgetName: FName, WidgetPath: FName): boolean
// WidgetUnloaded(WidgetName: FName, WidgetPath: FName): boolean

/**
 * Class GFxUI.GFxRawData
 * Size: 0x00A0
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_EditInlineNew | CLASS_Exported
 */
export type UGFxRawData = UObject & {
};

/**
 * Class GFxUI.SwfMovie
 * Size: 0x0128
 * Extends: UGFxRawData
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_EditInlineNew | CLASS_Exported
 */
export type USwfMovie = UGFxRawData & {
  bUsesFontlib: boolean;  // 0x00a0 (0x0004) [bool : 0x1]
  bSetSRGBOnImportedTextures: boolean;  // 0x00a0 (0x0004) [bool : 0x2]
  bPackTextures: boolean;  // 0x00a0 (0x0004) [bool : 0x4]
  bForceSquarePacking: boolean;  // 0x00a0 (0x0004) [bool : 0x8]
  SourceFile: string;  // 0x00a8 (0x0010) [FString]
  PackTextureSize: number;  // 0x00b8 (0x0004) [int32]
  TextureFormat: string;  // 0x00c0 (0x0010) [FString]
  SourceFileTimestamp: string;  // 0x00d0 (0x0010) [FString]
  SourceFileCRC: number;  // 0x00e0 (0x0004) [int32]
  RTTextures: number;  // 0x0118 (0x0004) [int32]
  RTVideoTextures: number;  // 0x011c (0x0004) [int32]
  ImportTimeStamp: bigint;  // 0x0120 (0x0008) [uint64]
};
