/**
 * OnlineSubsystemEOS Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { FScriptDelegate } from '../structs/Core';
import type { UErrorList, UObject } from './Core';
import type { UOnlineAuthInterfaceImpl, UOnlineFriendsInterfaceImpl, UOnlineGameInterfaceImpl, UOnlinePersistentAuthInterfaceImpl, UOnlineSubsystemCommonImpl } from './IpDrv';

/**
 * Class OnlineSubsystemEOS.__OnlinePlayerInterfaceEOS__LinkedAccount_0x1
 * Size: 0x0064
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Hidden | CLASS_HideDropDown
 */
export type U__OnlinePlayerInterfaceEOS__LinkedAccount_0x1 = UObject & {
  LocalUserNum: number;  // 0x0060 (0x0004) [int32]
};

// __OnlinePlayerInterfaceEOS__LinkedAccount_0x1 Functions
// __OnlinePlayerInterfaceEOS__LinkedAccount_0x1(_: number, PlatformAuthTicket: string): void

/**
 * Class OnlineSubsystemEOS.__OnlinePlayerInterfaceEOS__RequestNativePlatformAuthTicket_0x1
 * Size: 0x0080
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Hidden | CLASS_HideDropDown
 */
export type U__OnlinePlayerInterfaceEOS__RequestNativePlatformAuthTicket_0x1 = UObject & {
  LocalUserNum: number;  // 0x0060 (0x0004) [int32]
  Callback: FScriptDelegate;  // 0x0068 (0x0018) [FScriptDelegate]
};

// __OnlinePlayerInterfaceEOS__RequestNativePlatformAuthTicket_0x1 Functions
// __OnlinePlayerInterfaceEOS__RequestNativePlatformAuthTicket_0x1(bSuccess: boolean, Code: string): void

/**
 * Class OnlineSubsystemEOS.AudioDevicesChangedEvent
 * Size: 0x0060
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UAudioDevicesChangedEvent = UObject & {
};

/**
 * Class OnlineSubsystemEOS.EOSErrors
 * Size: 0x00F8
 * Extends: UErrorList
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UEOSErrors = UErrorList & {
};

/**
 * Class OnlineSubsystemEOS.OnlineAuthInterfaceEOS
 * Size: 0x03D0
 * Extends: UOnlineAuthInterfaceImpl
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineAuthInterfaceEOS = UOnlineAuthInterfaceImpl & {
};

// OnlineAuthInterfaceEOS Functions
// RequestAuthTicket(Callback: FScriptDelegate): boolean // Native
// RequestMtxCode(Callback: FScriptDelegate): boolean // Native
// RequiresAuthTicket(): boolean

/**
 * Class OnlineSubsystemEOS.OnlineFriendsInterfaceEOS
 * Size: 0x0088
 * Extends: UOnlineFriendsInterfaceImpl
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineFriendsInterfaceEOS = UOnlineFriendsInterfaceImpl & {
};

// OnlineFriendsInterfaceEOS Functions
// GetActivePlatformId(): boolean // Native
// RequestLinkedAccounts(Callback: FScriptDelegate): boolean // Native

/**
 * Class OnlineSubsystemEOS.OnlineGameClipsInterfaceEOS
 * Size: 0x0110
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineGameClipsInterfaceEOS = UObject & {
  __EventAvailabilityChanged__Delegate: FScriptDelegate;  // 0x0068 (0x0018) [FScriptDelegate]
  __EventRecordingChanged__Delegate: FScriptDelegate;  // 0x0080 (0x0018) [FScriptDelegate]
  __EventConnectionStatusChanged__Delegate: FScriptDelegate;  // 0x0098 (0x0018) [FScriptDelegate]
  __EventClipStatusChanged__Delegate: FScriptDelegate;  // 0x00b0 (0x0018) [FScriptDelegate]
  __EventMaskStatusChanged__Delegate: FScriptDelegate;  // 0x00c8 (0x0018) [FScriptDelegate]
  __EventGeneralErrorOccurred__Delegate: FScriptDelegate;  // 0x00e0 (0x0018) [FScriptDelegate]
  __EventClipErrorOccurred__Delegate: FScriptDelegate;  // 0x00f8 (0x0018) [FScriptDelegate]
};

// OnlineGameClipsInterfaceEOS Functions
// CreateClip(InEpicAccountId: string, InClipType: string): number // Native
// DisableMaskArea(InMaskAreaHandle: bigint): void // Native
// EnableMaskArea(): bigint // Native
// EventAvailabilityChanged(): void
// EventClipErrorOccurred(InEpicAccountId: string, ClipId: number): void
// EventClipStatusChanged(InEpicAccountId: string, InClipId: number): void
// EventConnectionStatusChanged(InEpicAccountId: string): void
// EventGeneralErrorOccurred(): void
// EventMaskStatusChanged(InMaskAreaHandle: bigint): void
// EventRecordingChanged(): void
// GetTimeUntilUnthrottled(InEpicAccountId: string): number // Native
// IsAccountLinked(InEpicAccountId: string): boolean // Native
// IsAvailable(): boolean // Native
// IsClipUploadingLimitReached(InEpicAccountId: string): boolean // Native
// IsRecording(): boolean // Native
// IsUploading(): boolean // Native
// NotifyEventAvailabilityChanged(InCallback: FScriptDelegate): void
// NotifyEventClipErrorOccurred(InCallback: FScriptDelegate): void
// NotifyEventClipStatusChanged(InCallback: FScriptDelegate): void
// NotifyEventConnectionStatusChanged(InCallback: FScriptDelegate): void
// NotifyEventGeneralErrorOccurred(InCallback: FScriptDelegate): void
// NotifyEventMaskStatusChanged(InCallback: FScriptDelegate): void
// NotifyEventRecordingChanged(InCallback: FScriptDelegate): void
// SetUserMaxClipUploadsPerMinute(InMaxClipUploadsPerMinute: number): void // Native
// StartRecording(InClipDuration: bigint): void // Native
// StopRecording(): void // Native

/**
 * Class OnlineSubsystemEOS.OnlineGameInterfaceEOS
 * Size: 0x0334
 * Extends: UOnlineGameInterfaceImpl
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineGameInterfaceEOS = UOnlineGameInterfaceImpl & {
  bGameSessionUpdateInProgress: boolean;  // 0x0330 (0x0004) [bool : 0x1]
};

// OnlineGameInterfaceEOS Functions
// AcceptGameInvite(SessionName: FName): boolean // Native
// FreeSearchResults(): boolean // Native
// UpdateOnlineGame(SessionName: FName, bShouldRefreshOnlineData: boolean): boolean // Native

/**
 * Class OnlineSubsystemEOS.OnlinePersistentAuthInterfaceEOS
 * Size: 0x00C0
 * Extends: UOnlinePersistentAuthInterfaceImpl
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlinePersistentAuthInterfaceEOS = UOnlinePersistentAuthInterfaceImpl & {
};

// OnlinePersistentAuthInterfaceEOS Functions
// AuthWithNintendoAccountToken(/* out */ NintendoAccountToken: string): boolean // Native
// GetAuthExpirationTimestamp(): void // Native
// GetClientCredentials(): string // Native
// GetClientID(): string // Native
// GetClientSecret(): string // Native
// GetContinuanceToken(): string // Native
// GetRefreshToken(): string // Native
// GetTimeUntilAuthExpiration(): bigint // Native
// LaunchAccountPortal(): boolean // Native
// RequestPinGrantCode(): boolean // Native
// UseRefreshToken(RefreshToken: string): boolean // Native

/**
 * Class OnlineSubsystemEOS.OnlinePlayerInterfaceEOS
 * Size: 0x06B0
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed | CLASS_Localized | CLASS_Native | CLASS_Exported
 */
export type UOnlinePlayerInterfaceEOS = UObject & {
  DefaultLocalUser: number;  // 0x00b8 (0x0004) [int32]
  ProfileDataDirectory: string;  // 0x00c0 (0x0010) [FString]
  ProfileDataExtension: string;  // 0x00d0 (0x0010) [FString]
  DefaultStatus: string;  // 0x0190 (0x0010) [FString]
  __OnBlockListUpdated__Delegate: FScriptDelegate;  // 0x0248 (0x0018) [FScriptDelegate]
  __OnPlayerBlocked__Delegate: FScriptDelegate;  // 0x0260 (0x0018) [FScriptDelegate]
  __OnPlayerUnblocked__Delegate: FScriptDelegate;  // 0x0278 (0x0018) [FScriptDelegate]
  __OnLoginChange__Delegate: FScriptDelegate;  // 0x0290 (0x0018) [FScriptDelegate]
  __OnLoginCancelled__Delegate: FScriptDelegate;  // 0x02a8 (0x0018) [FScriptDelegate]
  __OnMutingChange__Delegate: FScriptDelegate;  // 0x02c0 (0x0018) [FScriptDelegate]
  __OnFriendsChange__Delegate: FScriptDelegate;  // 0x02d8 (0x0018) [FScriptDelegate]
  __OnLoginFailed__Delegate: FScriptDelegate;  // 0x02f0 (0x0018) [FScriptDelegate]
  __OnReceievedPinGrantCode__Delegate: FScriptDelegate;  // 0x0308 (0x0018) [FScriptDelegate]
  __OnLogoutCompleted__Delegate: FScriptDelegate;  // 0x0320 (0x0018) [FScriptDelegate]
  __OnReadProfileSettingsComplete__Delegate: FScriptDelegate;  // 0x0338 (0x0018) [FScriptDelegate]
  __OnWriteProfileSettingsComplete__Delegate: FScriptDelegate;  // 0x0350 (0x0018) [FScriptDelegate]
  __OnReadFriendsComplete__Delegate: FScriptDelegate;  // 0x0368 (0x0018) [FScriptDelegate]
  __OnKeyboardInputComplete__Delegate: FScriptDelegate;  // 0x0380 (0x0018) [FScriptDelegate]
  __OnAddFriendComplete__Delegate: FScriptDelegate;  // 0x0398 (0x0018) [FScriptDelegate]
  __OnQueryUserByDisplayName__Delegate: FScriptDelegate;  // 0x03b0 (0x0018) [FScriptDelegate]
  __OnAddFriendByNameComplete__Delegate: FScriptDelegate;  // 0x03c8 (0x0018) [FScriptDelegate]
  __OnAcceptFriendInviteComplete__Delegate: FScriptDelegate;  // 0x03e0 (0x0018) [FScriptDelegate]
  __OnDenyFriendInviteComplete__Delegate: FScriptDelegate;  // 0x03f8 (0x0018) [FScriptDelegate]
  __OnRemoveFriendComplete__Delegate: FScriptDelegate;  // 0x0410 (0x0018) [FScriptDelegate]
  __OnFriendInviteReceived__Delegate: FScriptDelegate;  // 0x0428 (0x0018) [FScriptDelegate]
  __OnFriendInviteCanceled__Delegate: FScriptDelegate;  // 0x0440 (0x0018) [FScriptDelegate]
  __OnReceivedGameInvite__Delegate: FScriptDelegate;  // 0x0458 (0x0018) [FScriptDelegate]
  __OnJoinFriendGameComplete__Delegate: FScriptDelegate;  // 0x0470 (0x0018) [FScriptDelegate]
  __OnFriendMessageReceived__Delegate: FScriptDelegate;  // 0x0488 (0x0018) [FScriptDelegate]
  __OnRequestNativePlatformAuthTicketComplete__Delegate: FScriptDelegate;  // 0x04a0 (0x0018) [FScriptDelegate]
  __OnReadPlayerStorageComplete__Delegate: FScriptDelegate;  // 0x04b8 (0x0018) [FScriptDelegate]
  __OnReadPlayerStorageForNetIdComplete__Delegate: FScriptDelegate;  // 0x04d0 (0x0018) [FScriptDelegate]
  __OnWritePlayerStorageComplete__Delegate: FScriptDelegate;  // 0x04e8 (0x0018) [FScriptDelegate]
  __OnReadCrossTitleProfileSettingsComplete__Delegate: FScriptDelegate;  // 0x0500 (0x0018) [FScriptDelegate]
  __OnUserSignInComplete__Delegate: FScriptDelegate;  // 0x0518 (0x0018) [FScriptDelegate]
  __CanPlayOnlineChanged__Delegate: FScriptDelegate;  // 0x0530 (0x0018) [FScriptDelegate]
  __OnSaveDataNoSpaceDialogComplete__Delegate: FScriptDelegate;  // 0x0548 (0x0018) [FScriptDelegate]
  __OnRegisteredController__Delegate: FScriptDelegate;  // 0x0560 (0x0018) [FScriptDelegate]
  __OnUnregisteredController__Delegate: FScriptDelegate;  // 0x0578 (0x0018) [FScriptDelegate]
  __OnInputAPIChanged__Delegate: FScriptDelegate;  // 0x0590 (0x0018) [FScriptDelegate]
  __OnLoginStatusChange__Delegate: FScriptDelegate;  // 0x05a8 (0x0018) [FScriptDelegate]
  __OnUserSwitchComplete__Delegate: FScriptDelegate;  // 0x05c0 (0x0018) [FScriptDelegate]
  __OnDeviceSelectionComplete__Delegate: FScriptDelegate;  // 0x05d8 (0x0018) [FScriptDelegate]
  __OnProfileDataChanged__Delegate: FScriptDelegate;  // 0x05f0 (0x0018) [FScriptDelegate]
  __OnUnlockAchievementComplete__Delegate: FScriptDelegate;  // 0x0608 (0x0018) [FScriptDelegate]
  __OnReadAchievementsComplete__Delegate: FScriptDelegate;  // 0x0620 (0x0018) [FScriptDelegate]
  __OnAvatarChange__Delegate: FScriptDelegate;  // 0x0638 (0x0018) [FScriptDelegate]
  __FriendPresenceChange__Delegate: FScriptDelegate;  // 0x0650 (0x0018) [FScriptDelegate]
  __OnSanitizeStringComplete__Delegate: FScriptDelegate;  // 0x0668 (0x0018) [FScriptDelegate]
  __EpicIDToPlatformIDCallback__Delegate: FScriptDelegate;  // 0x0680 (0x0018) [FScriptDelegate]
  __OnFriendInviteAccepted__Delegate: FScriptDelegate;  // 0x0698 (0x0018) [FScriptDelegate]
};

// OnlinePlayerInterfaceEOS Functions
// AcceptFriendInvite(): boolean
// AddAcceptFriendInviteCompleteDelegate(FriendDelegate: FScriptDelegate): void
// AddAddFriendByNameCompleteDelegate(FriendDelegate: FScriptDelegate): void
// AddAddFriendCompleteDelegate(FriendDelegate: FScriptDelegate): void
// AddAvatarChangeDelegate(AvatarDelegate: FScriptDelegate): void
// AddBlockListUpdatedDelegate(InDelegate: FScriptDelegate): void
// AddCanPlayOnlineChangedDelegate(Callback: FScriptDelegate): void
// AddDenyFriendInviteCompleteDelegate(FriendDelegate: FScriptDelegate): void
// AddDeviceSelectionDoneDelegate(DeviceDelegate: FScriptDelegate): void
// AddFriend(Message: string): boolean
// AddFriendByName(FriendName: string, Message: string): boolean
// AddFriendInviteAcceptedDelegate(InviteAccepted: FScriptDelegate): void
// AddFriendInviteCanceledDelegate(InviteDelegate: FScriptDelegate): void
// AddFriendInviteReceivedDelegate(InviteDelegate: FScriptDelegate): void
// AddFriendMessageReceivedDelegate(MessageDelegate: FScriptDelegate): void
// AddFriendPresenceChangeDelegate(PresenceDelegate: FScriptDelegate): void
// AddFriendsChangeDelegate(FriendsDelegate: FScriptDelegate): void
// AddInGamePost(InPostID: string): boolean
// AddInputAPIChangedDelegate(InputAPIChangedDelegate: FScriptDelegate): void
// AddJoinFriendGameCompleteDelegate(JoinFriendGameCompleteDelegate: FScriptDelegate): void
// AddKeyboardInputDoneDelegate(InputDelegate: FScriptDelegate): void
// AddLoginCancelledDelegate(CancelledDelegate: FScriptDelegate): void
// AddLoginChangeDelegate(LoginDelegate: FScriptDelegate): void // Native
// AddLoginFailedDelegate(LoginFailedDelegate: FScriptDelegate): void // Native
// AddLoginStatusChangeDelegate(InDelegate: FScriptDelegate): void
// AddLogoutCompletedDelegate(LogoutDelegate: FScriptDelegate): void
// AddMutingChangeDelegate(MutingDelegate: FScriptDelegate): void
// AddPlayerBlockedDelegate(InDelegate: FScriptDelegate): void
// AddPlayerUnblockedDelegate(InDelegate: FScriptDelegate): void
// AddProfileDataChangedDelegate(ProfileDataChangedDelegate: FScriptDelegate): void
// AddQueryUserByDisplayNameCompleteDelegate(QueryDelegate: FScriptDelegate): void
// AddReadAchievementsCompleteDelegate(InDelegate: FScriptDelegate): void
// AddReadCrossTitleProfileSettingsCompleteDelegate(InDelegate: FScriptDelegate): void
// AddReadFriendsCompleteDelegate(ReadFriendsCompleteDelegate: FScriptDelegate): void
// AddReadPlayerStorageCompleteDelegate(InDelegate: FScriptDelegate): void
// AddReadPlayerStorageForNetIdCompleteDelegate(InDelegate: FScriptDelegate): void
// AddReadProfileSettingsCompleteDelegate(ReadProfileSettingsCompleteDelegate: FScriptDelegate): void
// AddReceivedGameInviteDelegate(ReceivedGameInviteDelegate: FScriptDelegate): void
// AddRegisteredControllerDelegate(RegisteredControllerDelegate: FScriptDelegate): void
// AddRemoveFriendCompleteDelegate(RemoveFriendDelegate: FScriptDelegate): void
// AddSaveDataNoSpaceDialogCompleteDelegate(DeviceDelegate: FScriptDelegate): void
// AddUnlockAchievementCompleteDelegate(InDelegate: FScriptDelegate): void
// AddUnregisteredControllerDelegate(UnregisteredControllerDelegate: FScriptDelegate): void
// AddUserSignInCompleteDelegate(InDelegate: FScriptDelegate): void
// AddUserSwitchCompleteDelegate(UserSwitchCompleteDelegate: FScriptDelegate): void
// AddWritePlayerStorageCompleteDelegate(InDelegate: FScriptDelegate): void
// AddWriteProfileSettingsCompleteDelegate(WriteProfileSettingsCompleteDelegate: FScriptDelegate): void
// AreAnyFriends(): boolean // Native
// AutoLogin(): boolean
// CanAccessPremiumContent(bAttemptToResolve: boolean, Reason: string): boolean
// CanAccessPremiumVideoContent(bAttemptToResolve: boolean, Reason: string): boolean
// CanBrowseInternet(bAttemptToResolve: boolean, Reason: string): boolean
// CanCommunicate(bAttemptToResolve: boolean): void
// CanCommunicateText(bAttemptToResolve: boolean, Reason: string): boolean
// CanCommunicateVideo(bAttemptToResolve: boolean, Reason: string): boolean
// CanCommunicateVoice(bAttemptToResolve: boolean, Reason: string): boolean
// CanDownloadUserContent(bAttemptToResolve: boolean, Reason: string): boolean
// CanPlayOnline(bAttemptToResolve: boolean, Reason: string): boolean
// CanPlayOnlineChanged(): void
// CanPurchaseContent(bAttemptToResolve: boolean, Reason: string): boolean
// CanRecordDVRClips(bAttemptToResolve: boolean, Reason: string): boolean
// CanRegisterController(LocalPlayerNum: number): boolean
// CanShareKinectContent(bAttemptToResolve: boolean, Reason: string): boolean
// CanShareUserCreatedContent(bAttemptToResolve: boolean, Reason: string): boolean
// CanShareWithSocialNetwork(bAttemptToResolve: boolean, Reason: string): boolean
// CanShowPresenceInformation(bAttemptToResolve: boolean, Reason: string): boolean
// CanUploadFitnessData(bAttemptToResolve: boolean, Reason: string): boolean
// CanUseCloudStorage(bAttemptToResolve: boolean, Reason: string): boolean
// CanViewPlayerProfiles(bAttemptToResolve: boolean, Reason: string): boolean
// CheckParentalControlInfo(bShowUi: boolean): boolean
// ClearAcceptFriendInviteCompleteDelegate(FriendDelegate: FScriptDelegate): void
// ClearAddFriendByNameCompleteDelegate(FriendDelegate: FScriptDelegate): void
// ClearAddFriendCompleteDelegate(FriendDelegate: FScriptDelegate): void
// ClearAvatarChangeDelegate(AvatarDelegate: FScriptDelegate): void
// ClearCrossTitleProfileSettings(TitleId: number): void
// ClearDenyFriendInviteCompleteDelegate(FriendDelegate: FScriptDelegate): void
// ClearDeviceSelectionDoneDelegate(DeviceDelegate: FScriptDelegate): void
// ClearFriendInviteCanceledDelegate(InviteDelegate: FScriptDelegate): void
// ClearFriendInviteReceivedDelegate(InviteDelegate: FScriptDelegate): void
// ClearFriendMessageReceivedDelegate(MessageDelegate: FScriptDelegate): void
// ClearFriendPresenceChangeDelegate(PresenceDelegate: FScriptDelegate): void
// ClearFriendsChangeDelegate(FriendsDelegate: FScriptDelegate): void
// ClearInputAPIChangedDelegate(InputAPIChangedDelegate: FScriptDelegate): void
// ClearJoinFriendGameCompleteDelegate(JoinFriendGameCompleteDelegate: FScriptDelegate): void
// ClearKeyboardInputDoneDelegate(InputDelegate: FScriptDelegate): void
// ClearLoginCancelledDelegate(CancelledDelegate: FScriptDelegate): void
// ClearLoginChangeDelegate(LoginDelegate: FScriptDelegate): void // Native
// ClearLoginFailedDelegate(LoginFailedDelegate: FScriptDelegate): void // Native
// ClearLoginStatusChangeDelegate(InDelegate: FScriptDelegate): void
// ClearLogoutCompletedDelegate(LogoutDelegate: FScriptDelegate): void
// ClearMutingChangeDelegate(MutingDelegate: FScriptDelegate): void
// ClearProfileDataChangedDelegate(ProfileDataChangedDelegate: FScriptDelegate): void
// ClearQueryUserByDisplayNameCompleteDelegate(QueryDelegate: FScriptDelegate): void
// ClearReadAchievementsCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearReadCrossTitleProfileSettingsCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearReadFriendsCompleteDelegate(ReadFriendsCompleteDelegate: FScriptDelegate): void
// ClearReadPlayerStorageCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearReadPlayerStorageForNetIdCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearReadProfileSettingsCompleteDelegate(ReadProfileSettingsCompleteDelegate: FScriptDelegate): void
// ClearReceivedGameInviteDelegate(ReceivedGameInviteDelegate: FScriptDelegate): void
// ClearRegisteredControllerDelegate(RegisteredControllerDelegate: FScriptDelegate): void
// ClearRemoveFriendCompleteDelegate(RemoveFriendDelegate: FScriptDelegate): void
// ClearSaveDataNoSpaceDialogCompleteDelegate(DeviceDelegate: FScriptDelegate): void
// ClearUnlockAchievementCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearUnregisteredControllerDelegate(UnregisteredControllerDelegate: FScriptDelegate): void
// ClearUserSignInCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearUserSwitchCompleteDelegate(UserSwitchCompleteDelegate: FScriptDelegate): void
// ClearWritePlayerStorageCompleteDelegate(InDelegate: FScriptDelegate): void
// ClearWriteProfileSettingsCompleteDelegate(WriteProfileSettingsCompleteDelegate: FScriptDelegate): void
// ConnectLogin(LocalUserNum: number): void // Native
// DeleteMessage(MessageIndex: number): boolean
// DenyFriendInvite(): boolean
// EpicIDToPlatformID(Callback: FScriptDelegate): void // Native
// EpicIDToPlatformIDCallback(Error: string): void
// FriendPresenceChange(): void
// GetAchievements(TitleId: number): void // Native
// GetActiveDiscDLC(): void
// GetBlockList(): void // Native
// GetConnectedControllerNames(): void
// GetControllerID(LocalPlayerNum: number): number
// GetCrossTitleProfileSettings(TitleId: number): void
// GetDeviceSelectionResults(/* out */ DeviceName: string): number
// GetEpicAccountId(): void // Native
// GetFriendMessages(): void
// GetFriendPresence(): void // Native
// GetFriendsList(Count: number, StartingAt: number): void // Native
// GetKeyboardInputResults(): string
// GetLoginStatus(): void // Native
// GetPlayerCountry(): string // Native
// GetPlayerLanguage(): string
// GetPlayerNickname(): string // Native
// GetPlayerStorage(): void
// GetPlayHistoryRegistrationKey(): boolean
// GetProfileSettings(): void
// GetSyncedAchievements(): void
// GetUniquePlayerId(): boolean // Native
// HasFriendsFunctionality(): boolean
// HasIncomingFriendInvite(): boolean // Native
// HideKeyboardUI(): boolean
// IsAchievementUnlocked(AchievementId: number): boolean
// IsDeviceValid(DeviceID: number): boolean
// IsFriend(): boolean // Native
// IsGuestLogin(): boolean
// IsMuted(): boolean
// IsUserSwitchActive(): boolean
// JoinFriendGame(): boolean
// LinkedAccount(LocalUserNum: number): void
// Login(LoginName: string, Password: string, bWantsLocalOnly: boolean): boolean // Native
// Logout(): boolean // Native
// OnAcceptFriendInviteComplete(): void
// OnAddFriendByNameComplete(bWasSuccessful: boolean): void
// OnAddFriendComplete(): void
// OnAvatarChange(): void
// OnBlockListUpdated(): void
// OnDenyFriendInviteComplete(): void
// OnDeviceSelectionComplete(bWasSuccessful: boolean): void
// OnFriendInviteAccepted(): void
// OnFriendInviteCanceled(): void
// OnFriendInviteReceived(RequestingNick: string, Message: string): void
// OnFriendMessageReceived(SendingNick: string, Message: string): void
// OnFriendsChange(): void
// OnInputAPIChanged(): void
// OnJoinFriendGameComplete(bWasSuccessful: boolean): void
// OnKeyboardInputComplete(bWasSuccessful: boolean): void
// OnLocalPlayerRemoved(LocalPlayerNum: number): void
// OnLoginCancelled(): void
// OnLoginChange(): void
// OnLoginFailed(): void
// OnLoginStatusChange(): void
// OnLogoutCompleted(bWasSuccessful: boolean): void
// OnMutingChange(): void
// OnPlayerBlocked(): void
// OnPlayerUnblocked(): void
// OnProfileDataChanged(): void
// OnQueryUserByDisplayName(bWasSuccessful: boolean, QueriedDisplayName: string): void
// OnReadAchievementsComplete(TitleId: number): void
// OnReadCrossTitleProfileSettingsComplete(TitleId: number, bWasSuccessful: boolean): void
// OnReadFriendsComplete(bWasSuccessful: boolean): void
// OnReadPlayerStorageComplete(bWasSuccessful: boolean): void
// OnReadPlayerStorageForNetIdComplete(bWasSuccessful: boolean): void
// OnReadProfileSettingsComplete(bWasSuccessful: boolean): void
// OnReceievedPinGrantCode(Code: string, URL: string, SecondsUntilExpiration: number): void
// OnReceivedGameInvite(InviterName: string): void
// OnRegisteredController(LocalPlayerNum: number, ControllerId: number): void
// OnRemoveFriendComplete(bWasSuccessful: boolean): void
// OnRequestNativePlatformAuthTicketComplete(LocalUserNum: number, PlatformAuthTicket: string): void
// OnSanitizeStringComplete(): void
// OnSaveDataNoSpaceDialogComplete(bContinueWithoutSave: boolean): void
// OnUnlockAchievementComplete(bWasSuccessful: boolean): void
// OnUnregisteredController(LocalPlayerNum: number): void
// OnUserSignInComplete(): void
// OnUserSwitchComplete(): void
// OnWritePlayerStorageComplete(bWasSuccessful: boolean): void
// OnWriteProfileSettingsComplete(bWasSuccessful: boolean): void
// QueryUserByDisplayName(DisplayName: string): boolean // Native
// ReadAchievements(TitleId: number, bShouldReadText: boolean, bShouldReadImages: boolean): boolean // Native
// ReadBlockList(): boolean
// ReadCrossTitleProfileSettings(TitleId: number): boolean
// ReadFriendsList(Count: number, StartingAt: number): boolean // Native
// ReadPlayerStorage(DeviceID: number): boolean
// ReadPlayerStorageForNetId(): boolean
// ReadProfileSettings(): boolean // Native
// RecordPlayersRecentlyMet(GameDescription: string): boolean
// RecordPlayersRecentlyMetKeys(): boolean
// RegisterController(LocalPlayerNum: number, ControllerId: number): void
// RemoveCanPlayOnlineChangedDelegate(Callback: FScriptDelegate): void
// RemoveFriend(): boolean
// RequestNativePlatformAuthTicket(LocalUserNum: number, Callback: FScriptDelegate): void
// RequestRestrictedFeatureMessaging(): void
// SendGameInviteToFriend(Text: string): boolean
// SendGameInviteToFriends(Text: string): boolean
// SendMessageToFriend(Message: string): boolean
// SetControllerLayout(ControllerId: number, LayoutName: FName): void
// SetInputAPI(): void
// SetKickPlayerDialogActive(Active: boolean): void
// SetKickPreviousUser(): void
// SetOnlineStatus(StatusId: number): void // Native
// SetOnlineSubscriptionRequirement(bRequiresOnlineSubscription: boolean): void
// SetPrimaryPlayerGamepadToLastInput(): void
// SetRichPresence(PresenceString: string, GameDataString: string): void // Native
// ShowAchievementsUI(): boolean
// ShowBindings(ControllerId: number): boolean
// ShowContentMarketplaceUI(): boolean
// ShowControllerUI(): boolean
// ShowCustomMessageUI(MessageTitle: string, NonEditableMessage: string, EditableMessage: string): boolean
// ShowCustomPlayersUI(Title: string, Description: string): boolean
// ShowDeviceSelectionUI(SizeNeeded: number, bForceShowUI: boolean): boolean
// ShowFeedbackUI(): boolean
// ShowFriendsInviteUI(): boolean
// ShowFriendsUI(): boolean
// ShowGamerCardUI(): boolean
// ShowInviteUI(InviteText: string): boolean
// ShowKeyboardUI(TitleText: string, DescriptionText: string, bIsPassword: boolean, bShouldValidate: boolean, DefaultText: string, MaxResultLength: number): boolean
// ShowLoginUI(bShowOnlineOnly: boolean): boolean
// ShowLoginUIForOrphanedUser(): boolean
// ShowMessagesUI(): boolean
// ShowPlayersUI(): boolean
// SupportInGameLogin(): boolean
// UnlockAchievement(AchievementId: number, PercentComplete: number): boolean // Native
// UnlockGamerPicture(PictureId: number): boolean
// UnregisterController(LocalPlayerNum: number): void
// UpdateStat(StatName: FName, Points: number): boolean
// WordFilterSanitizeString(Comment: string, SanitizeDelegate: FScriptDelegate): boolean
// WritePlayerStorage(DeviceID: number): boolean
// WriteProfileSettings(): boolean // Native

/**
 * Class OnlineSubsystemEOS.OnlineStatsInterfaceEOS
 * Size: 0x00C8
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineStatsInterfaceEOS = UObject & {
  __OnReadOnlineStatsComplete__Delegate: FScriptDelegate;  // 0x0080 (0x0018) [FScriptDelegate]
  __OnFlushOnlineStatsComplete__Delegate: FScriptDelegate;  // 0x0098 (0x0018) [FScriptDelegate]
  __OnRegisterHostStatGuidComplete__Delegate: FScriptDelegate;  // 0x00b0 (0x0018) [FScriptDelegate]
};

// OnlineStatsInterfaceEOS Functions
// AddFlushOnlineStatsCompleteDelegate(FlushOnlineStatsCompleteDelegate: FScriptDelegate): void
// AddReadOnlineStatsCompleteDelegate(ReadOnlineStatsCompleteDelegate: FScriptDelegate): void
// AddRegisterHostStatGuidCompleteDelegate(RegisterHostStatGuidCompleteDelegate: FScriptDelegate): void
// ClearFlushOnlineStatsCompleteDelegate(FlushOnlineStatsCompleteDelegate: FScriptDelegate): void
// ClearReadOnlineStatsCompleteDelegate(ReadOnlineStatsCompleteDelegate: FScriptDelegate): void
// ClearRegisterHostStatGuidCompleteDelegateDelegate(RegisterHostStatGuidCompleteDelegate: FScriptDelegate): void
// FlushOnlineStats(SessionName: FName): boolean
// FreeStats(): void
// GetClientStatGuid(): string
// GetHostStatGuid(): string
// OnFlushOnlineStatsComplete(SessionName: FName, bWasSuccessful: boolean): void
// OnReadOnlineStatsComplete(bWasSuccessful: boolean): void
// OnRegisterHostStatGuidComplete(bWasSuccessful: boolean): void
// ReadOnlineStats(): boolean // Native
// ReadOnlineStatsByRank(StartIndex: number, NumToRead: number): boolean // Native
// ReadOnlineStatsByRankAroundPlayer(NumRows: number): boolean // Native
// ReadOnlineStatsForFriends(): boolean // Native
// RegisterHostStatGuid(/* out */ HostStatGuid: string): boolean
// RegisterStatGuid(/* out */ ClientStatGuid: string): boolean
// WriteOnlinePlayerScores(SessionName: FName, LeaderboardId: number): boolean
// WriteOnlineStats(SessionName: FName): boolean

/**
 * Class OnlineSubsystemEOS.OnlineSubsystemEOS
 * Size: 0x0738
 * Extends: UOnlineSubsystemCommonImpl
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed | CLASS_Native | CLASS_HasComponents | CLASS_Exported
 */
export type UOnlineSubsystemEOS = UOnlineSubsystemCommonImpl & {
  __OnMicroTxnResponse__Delegate: FScriptDelegate;  // 0x04c8 (0x0018) [FScriptDelegate]
  __EventGetAppPriceInfoComplete__Delegate: FScriptDelegate;  // 0x04e0 (0x0018) [FScriptDelegate]
  __OnPlayerTalking__Delegate: FScriptDelegate;  // 0x04f8 (0x0018) [FScriptDelegate]
  __OnRecognitionComplete__Delegate: FScriptDelegate;  // 0x0510 (0x0018) [FScriptDelegate]
  __OnReadOnlineStatsComplete__Delegate: FScriptDelegate;  // 0x0528 (0x0018) [FScriptDelegate]
  __OnRegisterHostStatGuidComplete__Delegate: FScriptDelegate;  // 0x0540 (0x0018) [FScriptDelegate]
  __OnFlushOnlineStatsComplete__Delegate: FScriptDelegate;  // 0x0558 (0x0018) [FScriptDelegate]
  __OnLinkStatusChange__Delegate: FScriptDelegate;  // 0x0570 (0x0018) [FScriptDelegate]
  __OnExternalUIChange__Delegate: FScriptDelegate;  // 0x0588 (0x0018) [FScriptDelegate]
  __OnControllerChange__Delegate: FScriptDelegate;  // 0x05a0 (0x0018) [FScriptDelegate]
  __OnConnectionStatusChange__Delegate: FScriptDelegate;  // 0x05b8 (0x0018) [FScriptDelegate]
  __OnStorageDeviceChange__Delegate: FScriptDelegate;  // 0x05d0 (0x0018) [FScriptDelegate]
  __OnCreateOnlineAccountCompleted__Delegate: FScriptDelegate;  // 0x05e8 (0x0018) [FScriptDelegate]
  __OnPlayerTalkingStateChange__Delegate: FScriptDelegate;  // 0x0600 (0x0018) [FScriptDelegate]
  __OnCloseKickPlayerDialog__Delegate: FScriptDelegate;  // 0x0618 (0x0018) [FScriptDelegate]
  __OnCommerceDialogClosed__Delegate: FScriptDelegate;  // 0x0630 (0x0018) [FScriptDelegate]
  __OnErrorDialogClosed__Delegate: FScriptDelegate;  // 0x0648 (0x0018) [FScriptDelegate]
  __OnUnlockedDLCChange__Delegate: FScriptDelegate;  // 0x0660 (0x0018) [FScriptDelegate]
  __OnStorePurchaseCompleteDelegate__Delegate: FScriptDelegate;  // 0x0678 (0x0018) [FScriptDelegate]
  __OnUserOrphaned__Delegate: FScriptDelegate;  // 0x0690 (0x0018) [FScriptDelegate]
  __OnUserRestored__Delegate: FScriptDelegate;  // 0x06a8 (0x0018) [FScriptDelegate]
  __OnPlayerSigningOut__Delegate: FScriptDelegate;  // 0x06c0 (0x0018) [FScriptDelegate]
  __EventCryptoKeyCreated__Delegate: FScriptDelegate;  // 0x06d8 (0x0018) [FScriptDelegate]
  __EventTextMessageSigned__Delegate: FScriptDelegate;  // 0x06f0 (0x0018) [FScriptDelegate]
  __EventTextMessageValidated__Delegate: FScriptDelegate;  // 0x0708 (0x0018) [FScriptDelegate]
  __OnCaptureAvailabilityChange__Delegate: FScriptDelegate;  // 0x0720 (0x0018) [FScriptDelegate]
};

// OnlineSubsystemEOS Functions
// AddCaptureAvailabilityChangeDelegate(CaptureAvailabilityDelegate: FScriptDelegate): void
// AddCloseKickPlayerDialogDelegate(InDelegate: FScriptDelegate): void
// AddCommerceDialogClosedDelegate(InDelegate: FScriptDelegate): void
// AddConnectionStatusChangeDelegate(ConnectionStatusDelegate: FScriptDelegate): void
// AddControllerChangeDelegate(ControllerChangeDelegate: FScriptDelegate): void
// AddCreateOnlineAccountCompletedDelegate(AccountCreateDelegate: FScriptDelegate): void
// AddErrorDialogClosedDelegate(InDelegate: FScriptDelegate): void
// AddExternalUIChangeDelegate(InDelegate: FScriptDelegate): void
// AddLinkStatusChangeDelegate(LinkStatusDelegate: FScriptDelegate): void
// AddMicroTxnResponseDelegate(ResponseMicroTxnDelegate: FScriptDelegate): void
// AddPlayerSigningOutDelegate(InDelegate: FScriptDelegate): void
// AddPlayerTalkingDelegate(TalkerDelegate: FScriptDelegate): void
// AddReadOnlineStatsCompleteDelegate(ReadOnlineStatsCompleteDelegate: FScriptDelegate): void
// AddRecognitionCompleteDelegate(RecognitionDelegate: FScriptDelegate): void
// AddRegisterHostStatGuidCompleteDelegate(RegisterHostStatGuidCompleteDelegate: FScriptDelegate): void
// AddStorageDeviceChangeDelegate(StorageDeviceChangeDelegate: FScriptDelegate): void
// AddUnlockedDLCChangeDelegate(InDelegate: FScriptDelegate): void
// AddUserOrphanedDelegate(UserOrphanedDelegate: FScriptDelegate): void
// AddUserRestoredDelegate(UserRestoredDelegate: FScriptDelegate): void
// AnyPlayerChatRestricted(): boolean
// ClearCaptureAvailabilityChangeDelegate(CaptureAvailabilityDelegate: FScriptDelegate): void
// ClearCloseKickPlayerDialogDelegate(InDelegate: FScriptDelegate): void
// ClearCommerceDialogClosedDelegate(InDelegate: FScriptDelegate): void
// ClearConnectionStatusChangeDelegate(ConnectionStatusDelegate: FScriptDelegate): void
// ClearControllerChangeDelegate(ControllerChangeDelegate: FScriptDelegate): void
// ClearCreateOnlineAccountCompletedDelegate(AccountCreateDelegate: FScriptDelegate): void
// ClearErrorDialogClosedDelegate(InDelegate: FScriptDelegate): void
// ClearExternalUIChangeDelegate(InDelegate: FScriptDelegate): void
// ClearLinkStatusChangeDelegate(LinkStatusDelegate: FScriptDelegate): void
// ClearMicroTxnResponseDelegate(ResponseMicroTxnDelegate: FScriptDelegate): void
// ClearPlayerSigningOutDelegate(InDelegate: FScriptDelegate): void
// ClearPlayerTalkingDelegate(TalkerDelegate: FScriptDelegate): void
// ClearReadOnlineStatsCompleteDelegate(ReadOnlineStatsCompleteDelegate: FScriptDelegate): void
// ClearRecognitionCompleteDelegate(RecognitionDelegate: FScriptDelegate): void
// ClearRegisterHostStatGuidCompleteDelegateDelegate(RegisterHostStatGuidCompleteDelegate: FScriptDelegate): void
// ClearStorageDeviceChangeDelegate(StorageDeviceChangeDelegate: FScriptDelegate): void
// ClearUnlockedDLCChangeDelegate(InDelegate: FScriptDelegate): void
// ClearUserOrphanedDelegate(UserOrphanedDelegate: FScriptDelegate): void
// ClearUserRestoredDelegate(UserRestoredDelegate: FScriptDelegate): void
// CreateLocalAccount(Username: string, Password: string): boolean
// CreateOnlineAccount(Username: string, Password: string, EmailAddress: string, ProductKey: string): boolean
// DeleteLocalAccount(Username: string, Password: string): boolean
// EventCryptoKeyCreated(EpicAccountId: string, PublicKey: string): void
// EventGetAppPriceInfoComplete(AppName: FName, Price: string, DiscountPrice: string, DiscountPercentage: number): void
// EventTextMessageSigned(Signature: string, RequestID: number): void
// EventTextMessageValidated(bMessageValid: boolean, RequestID: number): void
// FormatCurrency(Currency: string, Price: number): string
// FreeStats(): void
// GenerateCryptoKeyForUser(/* out */ EpicAccountId: string): void // Native
// GetAppPriceInfo(Callback: FScriptDelegate): boolean // Native
// GetClientStatGuid(): string
// GetCurrentConnectionStatus(): void
// GetDLCPurchaseTime(AppName: FName): number
// GetHostStatGuid(): string
// GetLocalAccountNames(): boolean
// GetNATType(): void
// GetNetworkNotificationPosition(): void
// GetOverlayEnabled(): boolean
// GetPlayerNicknameFromIndex(UserIndex: number): string
// GetPlayerUniqueNetIdFromIndex(UserIndex: number): void
// GetRecognitionResults(): boolean
// GetUnlockedDLC(): void
// HandleBootMessage(): boolean // Native
// HasLinkConnection(): boolean
// Init(): boolean // Native
// InitEOS(/* out */ SandboxId: string, /* out */ DeploymentId: string): boolean // Native
// InitializeTrophyAPI(): void
// IsControllerConnected(ControllerId: number): boolean
// IsHeadsetPresent(): boolean
// IsKeyValid(): boolean
// IsLocalPlayerTalking(): boolean
// IsRemotePlayerTalking(): boolean
// ManuallyTickEOSPlatform(): boolean // Native
// MuteAll(bAllowFriends: boolean): boolean
// MuteRemoteTalker(): boolean
// NotifyExternalUIChanged(bIsOpening: boolean): void // Native
// OnCaptureAvailabilityChange(bCaptureAllowed: boolean): void
// OnCloseKickPlayerDialog(): void
// OnCommerceDialogClosed(): void
// OnConnectionStatusChange(): void
// OnControllerChange(ControllerId: number, bIsConnected: boolean): void
// OnCreateOnlineAccountCompleted(): void
// OnErrorDialogClosed(LocalUserNum: number): void
// OnExternalUIChange(bIsOpening: boolean): void
// OnFlushOnlineStatsComplete(SessionName: FName, bWasSuccessful: boolean): void
// OnLinkStatusChange(bIsConnected: boolean): void
// OnMicroTxnResponse(bAuthorized: boolean, OrderId: bigint): void
// OnPlayerSigningOut(): void
// OnPlayerTalking(): void
// OnPlayerTalkingStateChange(bIsTalking: boolean): void
// OnReadOnlineStatsComplete(bWasSuccessful: boolean): void
// OnRecognitionComplete(): void
// OnRegisterHostStatGuidComplete(bWasSuccessful: boolean): void
// OnStorageDeviceChange(): void
// OnStorePurchaseCompleteDelegate(): void
// OnUnlockedDLCChange(): void
// OnUserOrphaned(): void
// OnUserRestored(): void
// OpenErrorDialog(): void
// OpenPS4DisplayMode(ServiceLabel: number): void
// OpenStoreForDLC(DLC: FName): void
// OpenStoreForItems(): void // Native
// OpenStoreForItemsAsync(OnStorePurchaseCompleteDelegate: FScriptDelegate): void
// ReadOnlineStats(): boolean
// ReadOnlineStatsByRank(StartIndex: number, NumToRead: number): boolean
// ReadOnlineStatsByRankAroundPlayer(NumRows: number): boolean
// ReadOnlineStatsForFriends(): boolean
// RefreshNetworkErrorToggle(): boolean
// RegisterHostStatGuid(/* out */ HostStatGuid: string): boolean
// RegisterLocalTalker(): boolean
// RegisterRemoteTalker(): boolean
// RegisterStatGuid(/* out */ ClientStatGuid: string): boolean
// RenameLocalAccount(NewUserName: string, OldUserName: string, Password: string): boolean
// ResetControllerColor(ControllerId: number): void
// SaveKey(ProductKey: string): boolean
// SelectVocabulary(VocabularyId: number): boolean
// SetControllerColor(ControllerId: number): void
// SetNetworkNotificationPosition(): void
// SetRemoteTalkerPriority(Priority: number): boolean
// SetSpeechRecognitionObject(): boolean
// SetVoiceReceiveVolume(VoiceVolume: number): boolean
// ShowEOSOverlay(): void // Native
// ShowEOSOverlayReportVoice(): void // Native
// ShowEOSVoiceAgreement(): void // Native
// SignTextMessage(/* out */ EpicAccountId: string, /* out */ Message: string, RequestID: number): void // Native
// StartNetworkedVoice(): void
// StartSpeechRecognition(): boolean
// StopNetworkedVoice(): void
// StopSpeechRecognition(): boolean
// TickEOSPlatform(DeltaTime: number): void // Native
// UnmuteAll(): boolean
// UnmuteRemoteTalker(): boolean
// UnregisterLocalTalker(): boolean
// UnregisterRemoteTalker(): boolean
// UpdateSessionStatusFromPlayers(CurrentPlayerCount: number, numBotPlayers: number): void
// ValidateTextMessage(/* out */ Message: string, /* out */ PublicKey: string, /* out */ Signature: string, RequestID: number): void // Native
// WriteOnlinePlayerScores(): boolean

/**
 * Class OnlineSubsystemEOS.OnlineUserCloudFileInterfaceEOS
 * Size: 0x0118
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineUserCloudFileInterfaceEOS = UObject & {
  LastReadFileErrorCode: number;  // 0x0068 (0x0004) [int32]
  __OnEnumerateUserFilesComplete__Delegate: FScriptDelegate;  // 0x00b8 (0x0018) [FScriptDelegate]
  __OnReadUserFileComplete__Delegate: FScriptDelegate;  // 0x00d0 (0x0018) [FScriptDelegate]
  __OnWriteUserFileComplete__Delegate: FScriptDelegate;  // 0x00e8 (0x0018) [FScriptDelegate]
  __OnDeleteUserFileComplete__Delegate: FScriptDelegate;  // 0x0100 (0x0018) [FScriptDelegate]
};

// OnlineUserCloudFileInterfaceEOS Functions
// AddDeleteUserFileCompleteDelegate(DeleteUserFileCompleteDelegate: FScriptDelegate): void
// AddEnumerateUserFileCompleteDelegate(EnumerateUserFileCompleteDelegate: FScriptDelegate): void
// AddReadUserFileCompleteDelegate(ReadUserFileCompleteDelegate: FScriptDelegate): void
// AddWriteUserFileCompleteDelegate(WriteUserFileCompleteDelegate: FScriptDelegate): void
// ClearAllDelegates(): void
// ClearDeleteUserFileCompleteDelegate(DeleteUserFileCompleteDelegate: FScriptDelegate): void
// ClearEnumerateUserFileCompleteDelegate(EnumerateUserFileCompleteDelegate: FScriptDelegate): void
// ClearFile(UserId: string, Filename: string): boolean // Native
// ClearFiles(UserId: string): boolean // Native
// ClearReadUserFileCompleteDelegate(ReadUserFileCompleteDelegate: FScriptDelegate): void
// ClearWriteUserFileCompleteDelegate(WriteUserFileCompleteDelegate: FScriptDelegate): void
// DeleteUserFile(UserId: string, Filename: string, bShouldCloudDelete: boolean, bShouldLocallyDelete: boolean): boolean // Native
// EnumerateUserFiles(UserId: string): void // Native
// GetFileContents(UserId: string, Filename: string): boolean // Native
// GetUserFileList(UserId: string): void // Native
// OnDeleteUserFileComplete(bWasSuccessful: boolean, UserId: string, Filename: string): void
// OnEnumerateUserFilesComplete(bWasSuccessful: boolean, UserId: string): void
// OnReadUserFileComplete(bWasSuccessful: boolean, UserId: string, Filename: string): void
// OnWriteUserFileComplete(bWasSuccessful: boolean, UserId: string, Filename: string): void
// ReadUserFile(UserId: string, Filename: string): boolean // Native
// WriteUserFile(UserId: string, Filename: string): boolean // Native

/**
 * Class OnlineSubsystemEOS.OnlineVoiceInterfaceEOS
 * Size: 0x0298
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UOnlineVoiceInterfaceEOS = UObject & {
  __EventLeftVoiceRoom__Delegate: FScriptDelegate;  // 0x01a8 (0x0018) [FScriptDelegate]
  __EventJoinedVoiceRoom__Delegate: FScriptDelegate;  // 0x01c0 (0x0018) [FScriptDelegate]
  __EventRemovedFromVoiceRoom__Delegate: FScriptDelegate;  // 0x01d8 (0x0018) [FScriptDelegate]
  __EventPlayerJoinedVoiceRoom__Delegate: FScriptDelegate;  // 0x01f0 (0x0018) [FScriptDelegate]
  __EventPlayerLeftVoiceRoom__Delegate: FScriptDelegate;  // 0x0208 (0x0018) [FScriptDelegate]
  __EventPlayerStatusChanged__Delegate: FScriptDelegate;  // 0x0220 (0x0018) [FScriptDelegate]
  __EventPlayerVoiceAgreementStatusChanged__Delegate: FScriptDelegate;  // 0x0238 (0x0018) [FScriptDelegate]
  __EventVoiceRecordingStatusChanged__Delegate: FScriptDelegate;  // 0x0250 (0x0018) [FScriptDelegate]
  __OnPlayerTalkingStateChange__Delegate: FScriptDelegate;  // 0x0268 (0x0018) [FScriptDelegate]
  __OnRecognitionComplete__Delegate: FScriptDelegate;  // 0x0280 (0x0018) [FScriptDelegate]
};

// OnlineVoiceInterfaceEOS Functions
// AddPlayerTalkingDelegate(TalkerDelegate: FScriptDelegate): void
// AddRecognitionCompleteDelegate(RecognitionDelegate: FScriptDelegate): void
// CacheInputAudioDevices(): void // Native
// CacheOutputAudioDevices(): void // Native
// CheckAllPlayersAcceptedVoiceModerationAgreement(): boolean // Native
// ClearPlayerTalkingDelegate(TalkerDelegate: FScriptDelegate): void
// ClearRecognitionCompleteDelegate(RecognitionDelegate: FScriptDelegate): void
// EventJoinedVoiceRoom(EpicAccountId: string, RoomName: string): void
// EventLeftVoiceRoom(EpicAccountId: string, RoomName: string): void
// EventPlayerJoinedVoiceRoom(EpicAccountId: string, RoomName: string): void
// EventPlayerLeftVoiceRoom(EpicAccountId: string, RoomName: string): void
// EventPlayerStatusChanged(EpicAccountId: string, RoomName: string): void
// EventPlayerVoiceAgreementStatusChanged(EpicAccountId: string, bAccepted: boolean, bNewAgreement: boolean): void
// EventRemovedFromVoiceRoom(EpicAccountId: string, RoomName: string): void
// EventVoiceRecordingStatusChanged(bRecording: boolean): void
// GetCurrentRoomNameForUser(/* out */ EpicAccountId: string): string // Native
// GetRecognitionResults(): boolean
// GetUserState(/* out */ EpicAccountId: string): void // Native
// GetVoiceAgreementStatusForPlayer(/* out */ LocalEpicAccountId: string): void // Native
// HasPlayerAcceptedVoiceAgreement(/* out */ LocalEpicAccountId: string): boolean // Native
// HasPlayerRespondedToVoiceAgreement(/* out */ LocalEpicAccountId: string): boolean
// Init(): void // Native
// IsHeadsetPresent(): boolean
// IsLocalPlayerTalking(): boolean
// IsRemotePlayerTalking(): boolean
// JoinVoiceRoom(/* out */ EpicAccountId: string, /* out */ RoomName: string, /* out */ ClientBaseUrl: string, /* out */ JoinToken: string): boolean // Native
// LeaveVoiceRoom(/* out */ EpicAccountId: string, /* out */ RoomName: string): boolean // Native
// MuteAll(bAllowFriends: boolean): boolean
// MuteRemoteTalker(bIsSystemWide: boolean): boolean
// OnLoginChange(): void // Native
// OnLogout(/* out */ EpicAccountId: string): void // Native
// OnPlayerTalkingStateChange(bIsTalking: boolean): void
// OnRecognitionComplete(): void
// RegisterLocalTalker(): boolean
// RegisterRemoteTalker(): boolean
// SelectVocabulary(VocabularyId: number): boolean
// SetAudioInputDevice(/* out */ EpicAccountId: string, /* out */ DeviceID: string, InputVolume: number): boolean // Native
// SetAudioOutputDevice(/* out */ EpicAccountId: string, /* out */ DeviceID: string, OutputVolume: number): boolean // Native
// SetLocalPlayerRegisteredStatus(/* out */ PlatformId: string, bRegister: boolean): void // Native
// SetPlayerBlockStatus(/* out */ LocalEpicAccountId: string, /* out */ TargetEpicAccountId: string, /* out */ RoomName: string, bBlocked: boolean): void // Native
// SetPlayerMuteStatus(/* out */ LocalEpicAccountId: string, /* out */ TargetEpicAccountId: string, /* out */ RoomName: string, bMuted: boolean): void // Native
// SetRemoteTalkerPriority(Priority: number): boolean
// SetSpeechRecognitionObject(): boolean
// SetVoiceReceiveVolume(VoiceVolume: number): boolean
// StartNetworkedVoice(): void
// StartRecording(/* out */ EpicAccountId: string, /* out */ RoomName: string): void // Native
// StartSpeechRecognition(): boolean
// StopNetworkedVoice(): void
// StopRecording(/* out */ EpicAccountId: string): void // Native
// StopSpeechRecognition(): boolean
// SubscribeToLoginChanges(): void
// UnmuteAll(): boolean
// UnmuteRemoteTalker(bIsSystemWide: boolean): boolean
// UnregisterLocalTalker(): boolean
// UnregisterRemoteTalker(): boolean

/**
 * Class OnlineSubsystemEOS.VideoRecorderEOS
 * Size: 0x0068
 * Extends: UObject
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UVideoRecorderEOS = UObject & {
  VfTable_FTickableObject: unknown;  // 0x0060 (0x0008) [unknown]
};
