/**
 * WinDrv Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { FPointer } from '../structs/Core';
import type { UClient, UFacebookIntegration, UForceFeedbackManager, UHttpRequestInterface, UHttpResponseInterface } from './Engine';

/**
 * Class WinDrv.FacebookWindows
 * Size: 0x00F8
 * Extends: UFacebookIntegration
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Transient | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UFacebookWindows = UFacebookIntegration & {
  VfTable_FTickableObject: FPointer;  // 0x00e8 (0x0008) [FPointer]
  ChildProcHandle: FPointer;  // 0x00f0 (0x0008) [FPointer]
};

// FacebookWindows Functions
// Authorize(): boolean // Native
// Disconnect(): void // Native
// FacebookRequest(GraphRequest: string, HTTPMethod: string, ParamKeysAndValues: string[]): void
// FacebookRequestCallback(OriginalRequest: UHttpRequestInterface, Response: UHttpResponseInterface, bDidSucceed: boolean): void
// Init(): boolean // Native
// IsAuthorized(): boolean // Native
// OnFacebookFriendsRequestComplete(OriginalRequest: UHttpRequestInterface, Response: UHttpResponseInterface, bDidSucceed: boolean): void
// OnFacebookMeRequestComplete(OriginalRequest: UHttpRequestInterface, Response: UHttpResponseInterface, bDidSucceed: boolean): void
// ProcessFacebookRequest(Payload: string, ResponseCode: number): void // Native
// RequestFacebookFriends(): void
// RequestFacebookMeInfo(): void

/**
 * Class WinDrv.HttpRequestWindows
 * Size: 0x00A8
 * Extends: UHttpRequestInterface
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UHttpRequestWindows = UHttpRequestInterface & {
  Request: FPointer;  // 0x0078 (0x0008) [FPointer]
  RequestVerb: string;  // 0x0080 (0x0010) [FString]
  RequestURL: FPointer;  // 0x0090 (0x0008) [FPointer]
  Payload: number[];  // 0x0098 (0x0010) [TArray<uint8>]
};

// HttpRequestWindows Functions
// GetContent(/* out */ Content: number[]): void // Native
// GetContentLength(): number // Native
// GetContentType(): string // Native
// GetHeader(HeaderName: string): string // Native
// GetHeaders(): string[] // Native
// GetURL(): string // Native
// GetURLParameter(ParameterName: string): string // Native
// GetVerb(): string // Native
// ProcessRequest(): boolean // Native
// SetContent(/* out */ ContentPayload: number[]): UHttpRequestInterface // Native
// SetContentAsString(ContentString: string): UHttpRequestInterface // Native
// SetHeader(HeaderName: string, HeaderValue: string): UHttpRequestInterface // Native
// SetURL(URL: string): UHttpRequestInterface // Native
// SetVerb(Verb: string): UHttpRequestInterface // Native

/**
 * Class WinDrv.HttpRequestWindowsMcp
 * Size: 0x00C8
 * Extends: UHttpRequestWindows
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed
 */
export type UHttpRequestWindowsMcp = UHttpRequestWindows & {
  AppID: string;  // 0x00a8 (0x0010) [FString]
  AppSecret: string;  // 0x00b8 (0x0010) [FString]
};

// HttpRequestWindowsMcp Functions
// ProcessRequest(): boolean

/**
 * Class WinDrv.HttpResponseWindows
 * Size: 0x0078
 * Extends: UHttpResponseInterface
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UHttpResponseWindows = UHttpResponseInterface & {
  Response: FPointer;  // 0x0060 (0x0008) [FPointer]
  Payload: number[];  // 0x0068 (0x0010) [TArray<uint8>]
};

// HttpResponseWindows Functions
// GetContent(/* out */ Content: number[]): void // Native
// GetContentAsString(): string // Native
// GetContentLength(): number // Native
// GetContentType(): string // Native
// GetHeader(HeaderName: string): string // Native
// GetHeaders(): string[] // Native
// GetResponseCode(): number // Native
// GetURL(): string // Native
// GetURLParameter(ParameterName: string): string // Native

/**
 * Class WinDrv.WindowsClient
 * Size: 0x03C0
 * Extends: UClient
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UWindowsClient = UClient & {
  AudioDeviceClass: bigint;  // 0x0278 (0x0008) [UClass*]
  AllowJoystickInput: number;  // 0x02b8 (0x0004) [int32]
};

/**
 * Class WinDrv.XnaForceFeedbackManager
 * Size: 0x00B0
 * Extends: UForceFeedbackManager
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UXnaForceFeedbackManager = UForceFeedbackManager & {
};
