/**
 * WinDrv Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { FName, FPointer, FScriptDelegate } from '../structs/Core';
import type { FDelegateArray, FFacebookFriend } from '../structs/Engine';
import type { UObject } from './Core';
import type { UActor, UClient, UFacebookIntegration, UForceFeedbackManager, UForceFeedbackWaveform, UHttpRequestInterface, UHttpResponseInterface } from './Engine';

/**
 * Class WinDrv.FacebookWindows
 * Size: 0x00F8
 * Extends: UFacebookIntegration
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Transient | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UFacebookWindows = UFacebookIntegration & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  AllDelegates: FDelegateArray[];  // 0x0060 (0x0010) [TArray<FDelegateArray>]
  __PlatformInterfaceDelegate__Delegate: FScriptDelegate;  // 0x0070 (0x0018) [FScriptDelegate]
  AppID: string;  // 0x0088 (0x0010) [FString]
  Permissions: string[];  // 0x0098 (0x0010) [TArray<FString>]
  Username: string;  // 0x00a8 (0x0010) [FString]
  UserId: string;  // 0x00b8 (0x0010) [FString]
  AccessToken: string;  // 0x00c8 (0x0010) [FString]
  FriendsList: FFacebookFriend[];  // 0x00d8 (0x0010) [TArray<FFacebookFriend>]
  VfTable_FTickableObject: FPointer;  // 0x00e8 (0x0008) [FPointer]
  ChildProcHandle: FPointer;  // 0x00f0 (0x0008) [FPointer]
};

// FacebookWindows Functions
// Authorize(): boolean // Native
// Disconnect(): void // Native
// FacebookRequest(GraphRequest: string, HTTPMethod: string, ParamKeysAndValues: string[]): void
// FacebookRequestCallback(OriginalRequest: UHttpRequestInterface, Response: UHttpResponseInterface, bDidSucceed: boolean): void
// Init(): boolean // Native
// IsAuthorized(): boolean // Native
// OnFacebookFriendsRequestComplete(OriginalRequest: UHttpRequestInterface, Response: UHttpResponseInterface, bDidSucceed: boolean): void
// OnFacebookMeRequestComplete(OriginalRequest: UHttpRequestInterface, Response: UHttpResponseInterface, bDidSucceed: boolean): void
// ProcessFacebookRequest(Payload: string, ResponseCode: number): void // Native
// RequestFacebookFriends(): void
// RequestFacebookMeInfo(): void

/**
 * Class WinDrv.HttpRequestWindows
 * Size: 0x00A8
 * Extends: UHttpRequestInterface
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UHttpRequestWindows = UHttpRequestInterface & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  __OnProcessRequestComplete__Delegate: FScriptDelegate;  // 0x0060 (0x0018) [FScriptDelegate]
  Request: FPointer;  // 0x0078 (0x0008) [FPointer]
  RequestVerb: string;  // 0x0080 (0x0010) [FString]
  RequestURL: FPointer;  // 0x0090 (0x0008) [FPointer]
  Payload: number[];  // 0x0098 (0x0010) [TArray<uint8>]
};

// HttpRequestWindows Functions
// GetContent(/* out */ Content: number[]): void // Native
// GetContentLength(): number // Native
// GetContentType(): string // Native
// GetHeader(HeaderName: string): string // Native
// GetHeaders(): string[] // Native
// GetURL(): string // Native
// GetURLParameter(ParameterName: string): string // Native
// GetVerb(): string // Native
// ProcessRequest(): boolean // Native
// SetContent(/* out */ ContentPayload: number[]): UHttpRequestInterface // Native
// SetContentAsString(ContentString: string): UHttpRequestInterface // Native
// SetHeader(HeaderName: string, HeaderValue: string): UHttpRequestInterface // Native
// SetURL(URL: string): UHttpRequestInterface // Native
// SetVerb(Verb: string): UHttpRequestInterface // Native

/**
 * Class WinDrv.HttpRequestWindowsMcp
 * Size: 0x00C8
 * Extends: UHttpRequestWindows
 * Flags: CLASS_Compiled | CLASS_Config | CLASS_Parsed
 */
export type UHttpRequestWindowsMcp = UHttpRequestWindows & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  __OnProcessRequestComplete__Delegate: FScriptDelegate;  // 0x0060 (0x0018) [FScriptDelegate]
  Request: FPointer;  // 0x0078 (0x0008) [FPointer]
  RequestVerb: string;  // 0x0080 (0x0010) [FString]
  RequestURL: FPointer;  // 0x0090 (0x0008) [FPointer]
  Payload: number[];  // 0x0098 (0x0010) [TArray<uint8>]
  AppID: string;  // 0x00a8 (0x0010) [FString]
  AppSecret: string;  // 0x00b8 (0x0010) [FString]
};

// HttpRequestWindowsMcp Functions
// ProcessRequest(): boolean

/**
 * Class WinDrv.HttpResponseWindows
 * Size: 0x0078
 * Extends: UHttpResponseInterface
 * Flags: CLASS_Compiled | CLASS_Parsed | CLASS_Native | CLASS_Exported
 */
export type UHttpResponseWindows = UHttpResponseInterface & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  Response: FPointer;  // 0x0060 (0x0008) [FPointer]
  Payload: number[];  // 0x0068 (0x0010) [TArray<uint8>]
};

// HttpResponseWindows Functions
// GetContent(/* out */ Content: number[]): void // Native
// GetContentAsString(): string // Native
// GetContentLength(): number // Native
// GetContentType(): string // Native
// GetHeader(HeaderName: string): string // Native
// GetHeaders(): string[] // Native
// GetResponseCode(): number // Native
// GetURL(): string // Native
// GetURLParameter(ParameterName: string): string // Native

/**
 * Class WinDrv.WindowsClient
 * Size: 0x03C0
 * Extends: UClient
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UWindowsClient = UClient & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  MinDesiredFrameRate: number;  // 0x0068 (0x0004) [float]
  DisplayGamma: number;  // 0x006c (0x0004) [float]
  InitialButtonRepeatDelay: number;  // 0x0070 (0x0004) [float]
  ButtonRepeatDelay: number;  // 0x0074 (0x0004) [float]
  AudioDeviceClass: bigint;  // 0x0278 (0x0008) [UClass*]
  AllowJoystickInput: number;  // 0x02b8 (0x0004) [int32]
};

/**
 * Class WinDrv.XnaForceFeedbackManager
 * Size: 0x00B0
 * Extends: UForceFeedbackManager
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_Intrinsic
 */
export type UXnaForceFeedbackManager = UForceFeedbackManager & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  bAllowsForceFeedback: boolean;  // 0x0060 (0x0004) [bool : 0x1]
  bIsPaused: boolean;  // 0x0060 (0x0004) [bool : 0x2]
  FFWaveform: UForceFeedbackWaveform;  // 0x0068 (0x0008) [UForceFeedbackWaveform*]
  CurrentSample: number;  // 0x0070 (0x0004) [int32]
  ElapsedTime: number;  // 0x0074 (0x0004) [float]
  ScaleAllWaveformsBy: number;  // 0x0078 (0x0004) [float]
  WaveformInstigator: UActor;  // 0x0080 (0x0008) [UActor*]
  ShakeLeft: number;  // 0x0088 (0x0004) [int32]
  ShakeRight: number;  // 0x008c (0x0004) [int32]
  EnableTime: number;  // 0x0090 (0x0004) [float]
  EnabledTimeRemaining: number;  // 0x0094 (0x0004) [float]
};
