/**
 * XAudio2 Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { FDouble, FName, FPointer } from '../structs/Core';
import type { FInteriorSettings, FListener } from '../structs/Engine';
import type { EDebugState } from '../enums/Engine';
import type { UObject } from './Core';
import type { UAudioDevice, USoundMode, USoundNodeWave } from './Engine';

/**
 * Class XAudio2.XAudio2Device
 * Size: 0x0460
 * Extends: UAudioDevice
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_HasComponents | CLASS_Intrinsic
 */
export type UXAudio2Device = UAudioDevice & {
  VfTableObject: FPointer;  // 0x0000 (0x0008) [FPointer]
  HashNext: FPointer;  // 0x0008 (0x0008) [FPointer]
  ObjectFlags: bigint;  // 0x0010 (0x0008) [uint64]
  HashOuterNext: FPointer;  // 0x0018 (0x0008) [FPointer]
  StateFrame: FPointer;  // 0x0020 (0x0008) [FPointer]
  Linker: UObject;  // 0x0028 (0x0008) [UObject*]
  LinkerIndex: FPointer;  // 0x0030 (0x0008) [FPointer]
  ObjectInternalInteger: number;  // 0x0038 (0x0004) [int32]
  NetIndex: number;  // 0x003c (0x0004) [int32]
  Outer: UObject;  // 0x0040 (0x0008) [UObject*]
  Name: FName;  // 0x0048 (0x0008) [FName]
  Class: bigint;  // 0x0050 (0x0008) [UClass*]
  ObjectArchetype: UObject;  // 0x0058 (0x0008) [UObject*]
  VfTable_FExec: FPointer;  // 0x0060 (0x0008) [FPointer]
  MaxChannels: number;  // 0x0068 (0x0004) [int32]
  CommonAudioPoolSize: number;  // 0x006c (0x0004) [int32]
  LowPassFilterResonance: number;  // 0x0070 (0x0004) [float]
  MinCompressedDurationEditor: number;  // 0x0074 (0x0004) [float]
  MinCompressedDurationGame: number;  // 0x0078 (0x0004) [float]
  ChirpInSoundNodeWaveName: string;  // 0x0080 (0x0010) [FString]
  ChirpInSoundNodeWave: USoundNodeWave;  // 0x0090 (0x0008) [USoundNodeWave*]
  ChirpOutSoundNodeWaveName: string;  // 0x0098 (0x0010) [FString]
  ChirpOutSoundNodeWave: USoundNodeWave;  // 0x00a8 (0x0008) [USoundNodeWave*]
  CommonAudioPool: FPointer;  // 0x00b0 (0x0008) [FPointer]
  CommonAudioPoolFreeBytes: number;  // 0x00b8 (0x0004) [int32]
  AudioComponents: unknown[];  // 0x00c0 (0x0010) [TArray<unknown>]
  Sources: FPointer[];  // 0x00d0 (0x0010) [TArray<FPointer>]
  FreeSources: FPointer[];  // 0x00e0 (0x0010) [TArray<FPointer>]
  WaveInstanceSourceMap: Map<unknown, unknown>;  // 0x00f0 (0x0050) [TMap<unknown, unknown>]
  bGameWasTicking: boolean;  // 0x0140 (0x0004) [bool : 0x1]
  bSoundSpawningEnabled: boolean;  // 0x0140 (0x0004) [bool : 0x2]
  Listeners: FListener[];  // 0x0148 (0x0010) [TArray<FListener>]
  CurrentTick: bigint;  // 0x0158 (0x0008) [uint64]
  SoundClasses: Map<unknown, unknown>;  // 0x0160 (0x0050) [TMap<unknown, unknown>]
  SourceSoundClasses: Map<unknown, unknown>;  // 0x01b0 (0x0050) [TMap<unknown, unknown>]
  CurrentSoundClasses: Map<unknown, unknown>;  // 0x0200 (0x0050) [TMap<unknown, unknown>]
  DestinationSoundClasses: Map<unknown, unknown>;  // 0x0250 (0x0050) [TMap<unknown, unknown>]
  SoundModes: Map<unknown, unknown>;  // 0x02a0 (0x0050) [TMap<unknown, unknown>]
  Effects: FPointer;  // 0x02f0 (0x0008) [FPointer]
  BaseSoundModeName: FName;  // 0x02f8 (0x0008) [FName]
  CurrentMode: USoundMode;  // 0x0300 (0x0008) [USoundMode*]
  SoundModeStartTime: FDouble;  // 0x0308 (0x0008) [FDouble]
  SoundModeFadeInStartTime: FDouble;  // 0x0310 (0x0008) [FDouble]
  SoundModeFadeInEndTime: FDouble;  // 0x0318 (0x0008) [FDouble]
  SoundModeEndTime: FDouble;  // 0x0320 (0x0008) [FDouble]
  ListenerVolumeIndex: number;  // 0x0328 (0x0004) [int32]
  ListenerInteriorSettings: FInteriorSettings;  // 0x032c (0x0024) [FInteriorSettings]
  InteriorStartTime: FDouble;  // 0x0350 (0x0008) [FDouble]
  InteriorEndTime: FDouble;  // 0x0358 (0x0008) [FDouble]
  ExteriorEndTime: FDouble;  // 0x0360 (0x0008) [FDouble]
  InteriorLPFEndTime: FDouble;  // 0x0368 (0x0008) [FDouble]
  ExteriorLPFEndTime: FDouble;  // 0x0370 (0x0008) [FDouble]
  InteriorVolumeInterp: number;  // 0x0378 (0x0004) [float]
  InteriorLPFInterp: number;  // 0x037c (0x0004) [float]
  ExteriorVolumeInterp: number;  // 0x0380 (0x0004) [float]
  ExteriorLPFInterp: number;  // 0x0384 (0x0004) [float]
  TestAudioComponent: unknown;  // 0x0388 (0x0008) [unknown]
  TextToSpeech: FPointer;  // 0x0390 (0x0008) [FPointer]
  DebugState: EDebugState;  // 0x0398 (0x0001) [EDebugState]
  TransientMasterVolume: number;  // 0x039c (0x0004) [float]
  LastUpdateTime: number;  // 0x03a0 (0x0004) [float]
};
