/**
 * XAudio2 Package - Classes
 * Auto-generated by Stev Peifer
 */

import type { UAudioDevice } from './Engine';

/**
 * Class XAudio2.XAudio2Device
 * Size: 0x0460
 * Extends: UAudioDevice
 * Flags: CLASS_Config | CLASS_Transient | CLASS_Native | CLASS_HasComponents | CLASS_Intrinsic
 */
export type UXAudio2Device = UAudioDevice & {
};
