/**
 * AkAudio Package - Function Parameters
 * Auto-generated by Stev Peifer
 */

import type { FName, FScriptDelegate } from '../types/core';

/**
 * Function AkAudio.AkAmbientSoundActor.OnToggle
 */
export type AkAmbientSoundActor_OnToggle_Params = {
};

/**
 * Function AkAudio.AkBusActor.RegisterReflectionEmitter
 */
export type AkBusActor_RegisterReflectionEmitter_Params = {
  BusName: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkBusActor.SetPinnedAxis
 */
export type AkBusActor_SetPinnedAxis_Params = {
};

/**
 * Function AkAudio.AkDevice.GetEnvironments
 */
export type AkDevice_GetEnvironments_Params = {
};

/**
 * Function AkAudio.AkDevice.GetSoundSource
 */
export type AkDevice_GetSoundSource_Params = {
  ReturnValue: unknown;  // 0x0020 (0x0008) [unknown] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkDevice.NotifyWhenInitialized
 */
export type AkDevice_NotifyWhenInitialized_Params = {
  Callback: FScriptDelegate;  // 0x0000 (0x0018) [FScriptDelegate] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.PlayGlobalSound
 */
export type AkDevice_PlayGlobalSound_Params = {
};

/**
 * Function AkAudio.AkDevice.PlaySound
 */
export type AkDevice_PlaySound_Params = {
  ReturnValue: unknown;  // 0x0028 (0x0008) [unknown] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkDevice.SetBusEffect
 */
export type AkDevice_SetBusEffect_Params = {
  BusName: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  EffectSetting: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
  EffectSlot: number;  // 0x0010 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetDynamicRange
 */
export type AkDevice_SetDynamicRange_Params = {
};

/**
 * Function AkAudio.AkDevice.SetGlobalRTCP
 */
export type AkDevice_SetGlobalRTCP_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetListenerSpatialization
 */
export type AkDevice_SetListenerSpatialization_Params = {
};

/**
 * Function AkAudio.AkDevice.SetOutputType
 */
export type AkDevice_SetOutputType_Params = {
};

/**
 * Function AkAudio.AkDevice.SetRTCP
 */
export type AkDevice_SetRTCP_Params = {
  Key: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0010 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSoundEnvironment
 */
export type AkDevice_SetSoundEnvironment_Params = {
};

/**
 * Function AkAudio.AkDevice.SetSplitScreenListenerEnabled
 */
export type AkDevice_SetSplitScreenListenerEnabled_Params = {
  bEnable: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSplitScreenListenerPosition
 */
export type AkDevice_SetSplitScreenListenerPosition_Params = {
};

/**
 * Function AkAudio.AkDevice.SetState
 */
export type AkDevice_SetState_Params = {
  InStateGroup: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  InState: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.SetSwitch
 */
export type AkDevice_SetSwitch_Params = {
  Key: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
  Value: FName;  // 0x0010 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkDevice.StopAllSounds
 */
export type AkDevice_StopAllSounds_Params = {
};

/**
 * Function AkAudio.AkDevice.StopGlobalSound
 */
export type AkDevice_StopGlobalSound_Params = {
};

/**
 * Function AkAudio.AkDevice.StopSound
 */
export type AkDevice_StopSound_Params = {
};

/**
 * Function AkAudio.AkEnvironments.AddActorEnvironment
 */
export type AkEnvironments_AddActorEnvironment_Params = {
};

/**
 * Function AkAudio.AkEnvironments.AddLevelDefault
 */
export type AkEnvironments_AddLevelDefault_Params = {
};

/**
 * Function AkAudio.AkEnvironments.RemoveActorEnvironment
 */
export type AkEnvironments_RemoveActorEnvironment_Params = {
  EnvironmentID: string;  // 0x0008 (0x0010) [FString] [CPF_Parm | CPF_OutParm]
};

/**
 * Function AkAudio.AkMusicAnalysis.EventNewMusicTrack
 */
export type AkMusicAnalysis_EventNewMusicTrack_Params = {
  PlayingID: number;  // 0x0000 (0x0004) [int32] [CPF_Parm]
  NewBPM: number;  // 0x0004 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicAnalysis.GetInstance
 */
export type AkMusicAnalysis_GetInstance_Params = {
};

/**
 * Function AkAudio.AkMusicAnalysis.OnNewTrack
 */
export type AkMusicAnalysis_OnNewTrack_Params = {
  NewBPM: number;  // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicAnalysis.UpdateMusicInfo
 */
export type AkMusicAnalysis_UpdateMusicInfo_Params = {
};

/**
 * Function AkAudio.AkMusicAnalysis.UpdateSmoothedMusicInfo
 */
export type AkMusicAnalysis_UpdateSmoothedMusicInfo_Params = {
  DeltaTime: number;  // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.EventTrackEnd
 */
export type AkMusicDevice_EventTrackEnd_Params = {
  PlayingID: number;  // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.EventTrackStart
 */
export type AkMusicDevice_EventTrackStart_Params = {
  PlayingID: number;  // 0x0000 (0x0004) [int32] [CPF_Parm]
  FileMarker: string;  // 0x0008 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.Play
 */
export type AkMusicDevice_Play_Params = {
  ReturnValue: number;  // 0x0008 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkMusicDevice.Seek
 */
export type AkMusicDevice_Seek_Params = {
  PositionSeconds: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.SetRTCP
 */
export type AkMusicDevice_SetRTCP_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkMusicDevice.Stop
 */
export type AkMusicDevice_Stop_Params = {
};

/**
 * Function AkAudio.AkMusicDevice.StopPlayingID
 */
export type AkMusicDevice_StopPlayingID_Params = {
  PlayingID: number;  // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.GetDebugData
 */
export type AkParamGroup_GetDebugData_Params = {
};

/**
 * Function AkAudio.AkParamGroup.PlaySound
 */
export type AkParamGroup_PlaySound_Params = {
  ReturnValue: unknown;  // 0x0020 (0x0008) [unknown] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkParamGroup.PrintDebugInfo
 */
export type AkParamGroup_PrintDebugInfo_Params = {
  Idx: number;  // 0x0048 (0x0004) [int32]
};

/**
 * Function AkAudio.AkParamGroup.SetActorParameter
 */
export type AkParamGroup_SetActorParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetControllerId
 */
export type AkParamGroup_SetControllerId_Params = {
  InID: number;  // 0x0000 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetFloatParameter
 */
export type AkParamGroup_SetFloatParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetLinearColorParameter
 */
export type AkParamGroup_SetLinearColorParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetNameParameter
 */
export type AkParamGroup_SetNameParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetRTCP
 */
export type AkParamGroup_SetRTCP_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetSendToSlapbacks
 */
export type AkParamGroup_SetSendToSlapbacks_Params = {
  bSend: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetSwitch
 */
export type AkParamGroup_SetSwitch_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.SetVectorParameter
 */
export type AkParamGroup_SetVectorParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkParamGroup.StopSound
 */
export type AkParamGroup_StopSound_Params = {
};

/**
 * Function AkAudio.AkPlaySoundComponent.IsPlaying
 */
export type AkPlaySoundComponent_IsPlaying_Params = {
  ReturnValue: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetActorParameter
 */
export type AkPlaySoundComponent_SetActorParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetFloatParameter
 */
export type AkPlaySoundComponent_SetFloatParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetLinearColorParameter
 */
export type AkPlaySoundComponent_SetLinearColorParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetNameParameter
 */
export type AkPlaySoundComponent_SetNameParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetRTCP
 */
export type AkPlaySoundComponent_SetRTCP_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetSwitch
 */
export type AkPlaySoundComponent_SetSwitch_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
  Value: FName;  // 0x0008 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkPlaySoundComponent.SetVectorParameter
 */
export type AkPlaySoundComponent_SetVectorParameter_Params = {
  Key: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.CalcRPM
 */
export type AkRevPhysicsSimulation_CalcRPM_Params = {
  GearRatio: number;  // 0x0000 (0x0004) [float] [CPF_Parm]
  Velocity: number;  // 0x0004 (0x0004) [float] [CPF_Parm]
  ReturnValue: number;  // 0x0008 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.CalcVelocity
 */
export type AkRevPhysicsSimulation_CalcVelocity_Params = {
  GearRatio: number;  // 0x0000 (0x0004) [float] [CPF_Parm]
  RPM: number;  // 0x0004 (0x0004) [float] [CPF_Parm]
  ReturnValue: number;  // 0x0008 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.EventGearChange
 */
export type AkRevPhysicsSimulation_EventGearChange_Params = {
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.GetGearRatio
 */
export type AkRevPhysicsSimulation_GetGearRatio_Params = {
  ReturnValue: number;  // 0x0048 (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.InterpGearRatio
 */
export type AkRevPhysicsSimulation_InterpGearRatio_Params = {
  Gear: number;  // 0x0048 (0x0004) [int32] [CPF_Parm]
  ReturnValue: number;  // 0x004c (0x0004) [float] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.PrintDebugInfo
 */
export type AkRevPhysicsSimulation_PrintDebugInfo_Params = {
};

/**
 * Function AkAudio.AkRevPhysicsSimulation.Step
 */
export type AkRevPhysicsSimulation_Step_Params = {
  DeltaTime: number;  // 0x0000 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundBanksInfo.LoadForNativePlatform
 */
export type AkSoundBanksInfo_LoadForNativePlatform_Params = {
};

/**
 * Function AkAudio.AkSoundBanksInfo.Parse
 */
export type AkSoundBanksInfo_Parse_Params = {
  Text: string;  // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.EventDuration
 */
export type AkSoundSource_EventDuration_Params = {
  Source: unknown;  // 0x0000 (0x0008) [unknown] [CPF_Parm]
  PlayingID: number;  // 0x0008 (0x0004) [int32] [CPF_Parm]
  DurationMS: number;  // 0x000c (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.EventFinished
 */
export type AkSoundSource_EventFinished_Params = {
  Source: unknown;  // 0x0000 (0x0008) [unknown] [CPF_Parm]
  PlayingID: number;  // 0x0008 (0x0004) [int32] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.EventMarker
 */
export type AkSoundSource_EventMarker_Params = {
  Source: unknown;  // 0x0000 (0x0008) [unknown] [CPF_Parm]
  PlayingID: number;  // 0x0008 (0x0004) [int32] [CPF_Parm]
  Marker: string;  // 0x0010 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.IsPlaying
 */
export type AkSoundSource_IsPlaying_Params = {
  ReturnValue: boolean;  // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.IsPlayingAny
 */
export type AkSoundSource_IsPlayingAny_Params = {
  ReturnValue: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.Play
 */
export type AkSoundSource_Play_Params = {
  ReturnValue: number;  // 0x0008 (0x0004) [int32] [CPF_Parm | CPF_OutParm | CPF_ReturnParm]
};

/**
 * Function AkAudio.AkSoundSource.RegisterReflectionEmitter
 */
export type AkSoundSource_RegisterReflectionEmitter_Params = {
  BusName: FName;  // 0x0000 (0x0008) [FName] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.Seek
 */
export type AkSoundSource_Seek_Params = {
  SeekSeconds: number;  // 0x0008 (0x0004) [float] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.SetAttenuationScaling
 */
export type AkSoundSource_SetAttenuationScaling_Params = {
};

/**
 * Function AkAudio.AkSoundSource.SetSubtitlesEnabled
 */
export type AkSoundSource_SetSubtitlesEnabled_Params = {
  bValue: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.AkSoundSource.Stop
 */
export type AkSoundSource_Stop_Params = {
};

/**
 * Function AkAudio.SeqAct_AkPlayMusicWithCues.TriggerEvents
 */
export type SeqAct_AkPlayMusicWithCues_TriggerEvents_Params = {
  CueName: string;  // 0x0000 (0x0010) [FString] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPlaySound.ToggleSound
 */
export type SeqAct_AkPlaySound_ToggleSound_Params = {
  bPlay: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPlaySound.ToggleSoundFor
 */
export type SeqAct_AkPlaySound_ToggleSoundFor_Params = {
  bPlay: boolean;  // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPlaySoundAndSeek.ToggleSound
 */
export type SeqAct_AkPlaySoundAndSeek_ToggleSound_Params = {
  bPlay: boolean;  // 0x0000 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPlaySoundAndSeek.ToggleSoundFor
 */
export type SeqAct_AkPlaySoundAndSeek_ToggleSoundFor_Params = {
  bPlay: boolean;  // 0x0008 (0x0004) [bool : 0x1] [CPF_Parm]
};

/**
 * Function AkAudio.SeqAct_AkPostEvent.HandleSoundCueFinished
 */
export type SeqAct_AkPostEvent_HandleSoundCueFinished_Params = {
  Source: unknown;  // 0x0000 (0x0008) [unknown] [CPF_Parm]
  PlayingID: number;  // 0x0008 (0x0004) [int32] [CPF_Parm]
};
