/**
 * AkAudio Package - Offsets
 * Auto-generated by Stev Peifer
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

import { Object_, Subsystem } from './Core';
import { Actor, ActorComponent, ActorFactory, InterpTrack, InterpTrackFloatBase, InterpTrackInst, Keypoint, SeqAct_Latent, SequenceAction, SequenceEvent, Volume } from './Engine';

/**
 * AkAudio.ActorFactoryAkAmbientSound Offsets
 * Size: 0x00a8
 * Extends: ActorFactory
 */
export const ActorFactoryAkAmbientSound = {
  AmbientEvent: 0x00a0n,  // 0x00a0 (0x0008) [UAkEvent*]
  ...ActorFactory,
} as const;

/**
 * AkAudio.AkAmbientSound Offsets
 * Size: 0x0280
 * Extends: Keypoint
 */
export const AkAmbientSound = {
  bAutoPlay: 0x0270n,  // 0x0270 (0x0004) [bool : 0x1]
  StopWhenOwnerIsDestroyed: 0x0270n,  // 0x0270 (0x0004) [bool : 0x2]
  bIsPlaying: 0x0270n,  // 0x0270 (0x0004) [bool : 0x4]
  PlayEvent: 0x0278n,  // 0x0278 (0x0008) [UAkEvent*]
  ...Keypoint,
} as const;

/**
 * AkAudio.AkAmbientSoundActor Offsets
 * Size: 0x0278
 * Extends: Keypoint
 */
export const AkAmbientSoundActor = {
  PlaySoundComponent: 0x0270n,  // 0x0270 (0x0008) [unknown]
  ...Keypoint,
} as const;

/**
 * AkAudio.AkAudioDevice Offsets
 * Size: 0x01b0
 * Extends: Subsystem
 */
export const AkAudioDevice = {
  MaxNumMemoryPools: 0x0078n,  // 0x0078 (0x0004) [int32]
  DefaultMemoryPoolKB: 0x007cn,  // 0x007c (0x0004) [int32]
  DefaultEngineMemoryPoolKB: 0x0080n,  // 0x0080 (0x0004) [int32]
  WwiseBusSendBufferSamples: 0x0084n,  // 0x0084 (0x0004) [int32]
  DebugRecordWwiseBusSends: 0x0088n,  // 0x0088 (0x0004) [bool : 0x1]
  LowMemoryThreshold: 0x008cn,  // 0x008c (0x0004) [float]
  ...Subsystem,
} as const;

/**
 * AkAudio.AkBusActor Offsets
 * Size: 0x0279
 * Extends: Actor
 */
export const AkBusActor = {
  SoundSource: 0x0268n,  // 0x0268 (0x0008) [unknown]
  TargetBusName: 0x0270n,  // 0x0270 (0x0008) [FName]
  PinnedAxis: 0x0278n,  // 0x0278 (0x0001) [EPinnedAxisType]
  ...Actor,
} as const;

/**
 * AkAudio.AkComponent Offsets
 * Size: 0x00b4
 * Extends: ActorComponent
 */
export const AkComponent = {
  BoneName: 0x00a0n,  // 0x00a0 (0x0008) [FName]
  AutoPlayEvent: 0x00a8n,  // 0x00a8 (0x0008) [UAkEvent*]
  bStopWhenOwnerDestroyed: 0x00b0n,  // 0x00b0 (0x0004) [bool : 0x1]
  ...ActorComponent,
} as const;

/**
 * AkAudio.AkDevice Offsets
 * Size: 0x00b8
 * Extends: Object
 */
export const AkDevice = {
  DynamicRangeSetting_Low_Master: 0x0060n,  // 0x0060 (0x0008) [FName]
  DynamicRangeSetting_Medium_Master: 0x0068n,  // 0x0068 (0x0008) [FName]
  DynamicRangeSetting_High_Master: 0x0070n,  // 0x0070 (0x0008) [FName]
  DynamicRangeSetting_Low_Gameplay: 0x0078n,  // 0x0078 (0x0008) [FName]
  DynamicRangeSetting_Medium_Gameplay: 0x0080n,  // 0x0080 (0x0008) [FName]
  DynamicRangeSetting_High_Gameplay: 0x0088n,  // 0x0088 (0x0008) [FName]
  MasterAudioBusName: 0x0090n,  // 0x0090 (0x0008) [FName]
  GameplayAudioBusName: 0x0098n,  // 0x0098 (0x0008) [FName]
  __EventInitialized__Delegate: 0x00a0n,  // 0x00a0 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * AkAudio.AkDialogueEvent Offsets
 * Size: 0x0070
 * Extends: Object
 */
export const AkDialogueEvent = {
  Arguments: 0x0060n,  // 0x0060 (0x0010) [TArray<UAkSwitch*>]
  ...Object_,
} as const;

/**
 * AkAudio.AkEnvironmentVolume Offsets
 * Size: 0x02c8
 * Extends: Volume
 */
export const AkEnvironmentVolume = {
  Environment: 0x02a8n,  // 0x02a8 (0x0020) [FAkEnvironment]
  ...Volume,
} as const;

/**
 * AkAudio.AkEnvironments Offsets
 * Size: 0x008c
 * Extends: Object
 */
export const AkEnvironments = {
  VfTable_FObjectDestructionSubscriber: 0x0060n,  // 0x0060 (0x0008) [FPointer]
  LevelEnvironments: 0x0068n,  // 0x0068 (0x0010) [TArray<FAkEnvironment>]
  ActorEnvironments: 0x0078n,  // 0x0078 (0x0010) [TArray<FAkActorEnvironment>]
  bLevelDirty: 0x0088n,  // 0x0088 (0x0004) [bool : 0x1]
  bActorEnvironmentDirty: 0x0088n,  // 0x0088 (0x0004) [bool : 0x2]
  ...Object_,
} as const;

/**
 * AkAudio.AkMusicAnalysis Offsets
 * Size: 0x0110
 * Extends: Object
 */
export const AkMusicAnalysis = {
  VfTable_FTickableObject: 0x0060n,  // 0x0060 (0x0008) [FPointer]
  BPM: 0x0068n,  // 0x0068 (0x0004) [int32]
  MusicInfo: 0x0070n,  // 0x0070 (0x0020) [FMusicAnalysisInfo]
  MusicInfoSmoothed: 0x0090n,  // 0x0090 (0x0020) [FMusicAnalysisInfo]
  AttackSpeed: 0x00b0n,  // 0x00b0 (0x0004) [float]
  ReleaseSpeed: 0x00b4n,  // 0x00b4 (0x0004) [float]
  bDebugPrintMusicAnalysisValues: 0x00b8n,  // 0x00b8 (0x0004) [bool : 0x1]
  MusicAnalysisSilentLoop: 0x00c0n,  // 0x00c0 (0x0008) [UAkSoundCue*]
  __EventNewMusicTrack__Delegate: 0x00c8n,  // 0x00c8 (0x0018) [FScriptDelegate]
  __EventMusicBeat__Delegate: 0x00e0n,  // 0x00e0 (0x0018) [FScriptDelegate]
  __EventMusicBar__Delegate: 0x00f8n,  // 0x00f8 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * AkAudio.AkMusicDevice Offsets
 * Size: 0x0090
 * Extends: Object
 */
export const AkMusicDevice = {
  __EventTrackStart__Delegate: 0x0060n,  // 0x0060 (0x0018) [FScriptDelegate]
  __EventTrackEnd__Delegate: 0x0078n,  // 0x0078 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * AkAudio.AkParamGroup Offsets
 * Size: 0x015e
 * Extends: ActorComponent
 */
export const AkParamGroup = {
  VfTable_IISetParameter: 0x00a0n,  // 0x00a0 (0x0008) [FPointer]
  StoredParameters: 0x00a8n,  // 0x00a8 (0x00a0) [FAkParamSet]
  SoundSources: 0x0148n,  // 0x0148 (0x0010) [TArray<unknown>]
  ControllerId: 0x0158n,  // 0x0158 (0x0004) [int32]
  SendType: 0x015cn,  // 0x015c (0x0001) [EReflectionSendType]
  AttenuationType: 0x015dn,  // 0x015d (0x0001) [EAttenuationType]
  ...ActorComponent,
} as const;

/**
 * AkAudio.AkPlaySoundComponent Offsets
 * Size: 0x0198
 * Extends: ActorComponent
 */
export const AkPlaySoundComponent = {
  VfTable_IISetParameter: 0x00a0n,  // 0x00a0 (0x0008) [FPointer]
  SoundCue: 0x00a8n,  // 0x00a8 (0x0008) [UAkSoundCue*]
  bAutoPlay: 0x00b0n,  // 0x00b0 (0x0004) [bool : 0x1]
  bKillSoundOnDetach: 0x00b0n,  // 0x00b0 (0x0004) [bool : 0x2]
  bWasAttached: 0x00b0n,  // 0x00b0 (0x0004) [bool : 0x4]
  Translation: 0x00b4n,  // 0x00b4 (0x000c) [FVector]
  Rotation: 0x00c0n,  // 0x00c0 (0x000c) [FRotator]
  ReFireDelay: 0x00ccn,  // 0x00cc (0x0004) [float]
  Receiver: 0x00d0n,  // 0x00d0 (0x0001) [EAkPlaySoundReceiver]
  RestartSwitches: 0x00d8n,  // 0x00d8 (0x0010) [TArray<FName>]
  SoundSource: 0x00e8n,  // 0x00e8 (0x0008) [unknown]
  LastPlayTime: 0x00f0n,  // 0x00f0 (0x0004) [float]
  StoredParameters: 0x00f8n,  // 0x00f8 (0x00a0) [FAkParamSet]
  ...ActorComponent,
} as const;

/**
 * AkAudio.AkRTPCDecayComponent Offsets
 * Size: 0x00dc
 * Extends: ActorComponent
 */
export const AkRTPCDecayComponent = {
  RTPC: 0x00a0n,  // 0x00a0 (0x0008) [FName]
  GrowValue: 0x00a8n,  // 0x00a8 (0x0004) [float]
  MaxValue: 0x00acn,  // 0x00ac (0x0004) [float]
  DecayPerSecond: 0x00b0n,  // 0x00b0 (0x0018) [FInterpCurveFloat]
  SoundSource: 0x00c8n,  // 0x00c8 (0x0008) [unknown]
  CurrentValue: 0x00d0n,  // 0x00d0 (0x0004) [float]
  LastAttachTime: 0x00d4n,  // 0x00d4 (0x0004) [float]
  bWasAttached: 0x00d8n,  // 0x00d8 (0x0004) [bool : 0x1]
  ...ActorComponent,
} as const;

/**
 * AkAudio.AkRevPhysicsSimulation Offsets
 * Size: 0x00b0
 * Extends: Object
 */
export const AkRevPhysicsSimulation = {
  EngineGearRatio: 0x0060n,  // 0x0060 (0x0004) [float]
  EngineFriction: 0x0064n,  // 0x0064 (0x0004) [float]
  GroundFriction: 0x0068n,  // 0x0068 (0x0004) [float]
  WindResistancePerVelocity: 0x006cn,  // 0x006c (0x0004) [float]
  UpShiftingRPM: 0x0070n,  // 0x0070 (0x0004) [float]
  DownShiftRPM: 0x0074n,  // 0x0074 (0x0004) [float]
  InfiniteGearRatioDecreaseAmount: 0x0078n,  // 0x0078 (0x0004) [float]
  ThrottleInterpolationTime: 0x007cn,  // 0x007c (0x0004) [float]
  EngineTorque: 0x0080n,  // 0x0080 (0x0004) [float]
  BrakingForce: 0x0084n,  // 0x0084 (0x0004) [float]
  WindResistance: 0x0088n,  // 0x0088 (0x0004) [float]
  FrictionResistance: 0x008cn,  // 0x008c (0x0004) [float]
  EngineResistance: 0x0090n,  // 0x0090 (0x0004) [float]
  NetForce: 0x0094n,  // 0x0094 (0x0004) [float]
  __EventGearChange__Delegate: 0x0098n,  // 0x0098 (0x0018) [FScriptDelegate]
  ...Object_,
} as const;

/**
 * AkAudio.AkSoundBanksInfo Offsets
 * Size: 0x0088
 * Extends: Object
 */
export const AkSoundBanksInfo = {
  StreamedFileNames: 0x0060n,  // 0x0060 (0x0010) [TArray<FString>]
  SoundBanks: 0x0070n,  // 0x0070 (0x0010) [TArray<FSoundBankInfo>]
  EventToBankMap: 0x0080n,  // 0x0080 (0x0008) [unknown]
  ...Object_,
} as const;

/**
 * AkAudio.AkSoundCue Offsets
 * Size: 0x0088
 * Extends: Object
 */
export const AkSoundCue = {
  RequiredBank: 0x0060n,  // 0x0060 (0x0008) [UAkBank*]
  StartEvent: 0x0068n,  // 0x0068 (0x0010) [FString]
  StopEvent: 0x0078n,  // 0x0078 (0x0010) [FString]
  ...Object_,
} as const;

/**
 * AkAudio.AkSoundSource Offsets
 * Size: 0x0198
 * Extends: ActorComponent
 */
export const AkSoundSource = {
  Translation: 0x00a0n,  // 0x00a0 (0x000c) [FVector]
  Rotation: 0x00acn,  // 0x00ac (0x000c) [FRotator]
  bDetachOnComplete: 0x00b8n,  // 0x00b8 (0x0004) [bool : 0x1]
  bRegistered: 0x00b8n,  // 0x00b8 (0x0004) [bool : 0x2]
  bUpdateOrientation: 0x00b8n,  // 0x00b8 (0x0004) [bool : 0x4]
  CachedParentToWorld: 0x00c0n,  // 0x00c0 (0x0040) [FMatrix]
  WorldLocation: 0x0100n,  // 0x0100 (0x000c) [FVector]
  WorldRotation: 0x010cn,  // 0x010c (0x000c) [FRotator]
  Params: 0x0118n,  // 0x0118 (0x0008) [unknown]
  ActiveSounds: 0x0120n,  // 0x0120 (0x0010) [TArray<FActiveSound>]
  EnvironmentType: 0x0130n,  // 0x0130 (0x0001) [EAkEnvironmentType]
  CallbackTypes: 0x0138n,  // 0x0138 (0x0010) [TArray<EAkCallbackType>]
  SoundSourceId: 0x0148n,  // 0x0148 (0x0008) [FPointer]
  __EventFinished__Delegate: 0x0150n,  // 0x0150 (0x0018) [FScriptDelegate]
  __EventMarker__Delegate: 0x0168n,  // 0x0168 (0x0018) [FScriptDelegate]
  __EventDuration__Delegate: 0x0180n,  // 0x0180 (0x0018) [FScriptDelegate]
  ...ActorComponent,
} as const;

/**
 * AkAudio.AkSwitch Offsets
 * Size: 0x0060
 * Extends: Object
 */
export const AkSwitch = {
  ...Object_,
} as const;

/**
 * AkAudio.InterpTrackAkEvent Offsets
 * Size: 0x00dc
 * Extends: InterpTrack
 */
export const InterpTrackAkEvent = {
  AkEvents: 0x00c8n,  // 0x00c8 (0x0010) [TArray<FAkEventTrackKey>]
  SeekTimeSeconds: 0x00d8n,  // 0x00d8 (0x0004) [float]
  ...InterpTrack,
} as const;

/**
 * AkAudio.InterpTrackAkRTPC Offsets
 * Size: 0x00f8
 * Extends: InterpTrackFloatBase
 */
export const InterpTrackAkRTPC = {
  Param: 0x00e8n,  // 0x00e8 (0x0010) [FString]
  ...InterpTrackFloatBase,
} as const;

/**
 * AkAudio.InterpTrackInstAkEvent Offsets
 * Size: 0x0064
 * Extends: InterpTrackInst
 */
export const InterpTrackInstAkEvent = {
  LastUpdatePosition: 0x0060n,  // 0x0060 (0x0004) [float]
  ...InterpTrackInst,
} as const;

/**
 * AkAudio.InterpTrackInstAkRTPC Offsets
 * Size: 0x0060
 * Extends: InterpTrackInst
 */
export const InterpTrackInstAkRTPC = {
  ...InterpTrackInst,
} as const;

/**
 * AkAudio.SeqAct_AkClearBanks Offsets
 * Size: 0x0160
 * Extends: SequenceAction
 */
export const SeqAct_AkClearBanks = {
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkEnvironment Offsets
 * Size: 0x0181
 * Extends: SequenceAction
 */
export const SeqAct_AkEnvironment = {
  Environment: 0x0160n,  // 0x0160 (0x0020) [FAkEnvironment]
  Target: 0x0180n,  // 0x0180 (0x0001) [EAkEnvironmentTarget]
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkLoadBank Offsets
 * Size: 0x018c
 * Extends: SeqAct_Latent
 */
export const SeqAct_AkLoadBank = {
  Async: 0x0178n,  // 0x0178 (0x0004) [bool : 0x1]
  bWaitingCallback: 0x0178n,  // 0x0178 (0x0004) [bool : 0x2]
  Bank: 0x0180n,  // 0x0180 (0x0008) [UAkBank*]
  Signal: 0x0188n,  // 0x0188 (0x0004) [int32]
  ...SeqAct_Latent,
} as const;

/**
 * AkAudio.SeqAct_AkPlayMusicWithCues Offsets
 * Size: 0x0190
 * Extends: SeqAct_Latent
 */
export const SeqAct_AkPlayMusicWithCues = {
  SoundCue: 0x0178n,  // 0x0178 (0x0008) [UAkSoundCue*]
  MusicSyncEvents: 0x0180n,  // 0x0180 (0x0010) [TArray<FMusicSyncEvent>]
  ...SeqAct_Latent,
} as const;

/**
 * AkAudio.SeqAct_AkPlaySound Offsets
 * Size: 0x016c
 * Extends: SequenceAction
 */
export const SeqAct_AkPlaySound = {
  SoundCue: 0x0160n,  // 0x0160 (0x0008) [UAkSoundCue*]
  bBGMusic: 0x0168n,  // 0x0168 (0x0004) [bool : 0x1]
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkPlaySoundAndSeek Offsets
 * Size: 0x0178
 * Extends: SequenceAction
 */
export const SeqAct_AkPlaySoundAndSeek = {
  SoundCue: 0x0160n,  // 0x0160 (0x0008) [UAkSoundCue*]
  StartLocationSeconds: 0x0168n,  // 0x0168 (0x0004) [float]
  SoundSource: 0x0170n,  // 0x0170 (0x0008) [unknown]
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkPostEvent Offsets
 * Size: 0x0194
 * Extends: SeqAct_Latent
 */
export const SeqAct_AkPostEvent = {
  PlayingIDs: 0x0178n,  // 0x0178 (0x0010) [TArray<int32>]
  SoundCue: 0x0188n,  // 0x0188 (0x0008) [UAkSoundCue*]
  bHasSubtitles: 0x0190n,  // 0x0190 (0x0004) [bool : 0x1]
  ...SeqAct_Latent,
} as const;

/**
 * AkAudio.SeqAct_AkPostTrigger Offsets
 * Size: 0x0170
 * Extends: SequenceAction
 */
export const SeqAct_AkPostTrigger = {
  Trigger: 0x0160n,  // 0x0160 (0x0010) [FString]
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkSetRTPCValue Offsets
 * Size: 0x0190
 * Extends: SeqAct_Latent
 */
export const SeqAct_AkSetRTPCValue = {
  Param: 0x0178n,  // 0x0178 (0x0010) [FString]
  Value: 0x0188n,  // 0x0188 (0x0004) [float]
  Running: 0x018cn,  // 0x018c (0x0004) [bool : 0x1]
  ...SeqAct_Latent,
} as const;

/**
 * AkAudio.SeqAct_AkSetState Offsets
 * Size: 0x0180
 * Extends: SequenceAction
 */
export const SeqAct_AkSetState = {
  StateGroup: 0x0160n,  // 0x0160 (0x0010) [FString]
  State: 0x0170n,  // 0x0170 (0x0010) [FString]
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkSetSwitch Offsets
 * Size: 0x0180
 * Extends: SequenceAction
 */
export const SeqAct_AkSetSwitch = {
  SwitchGroup: 0x0160n,  // 0x0160 (0x0010) [FString]
  Switch: 0x0170n,  // 0x0170 (0x0010) [FString]
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkStartAmbientSound Offsets
 * Size: 0x0160
 * Extends: SequenceAction
 */
export const SeqAct_AkStartAmbientSound = {
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqAct_AkStopAll Offsets
 * Size: 0x0160
 * Extends: SequenceAction
 */
export const SeqAct_AkStopAll = {
  ...SequenceAction,
} as const;

/**
 * AkAudio.SeqEvent_AkMusicCue Offsets
 * Size: 0x0190
 * Extends: SequenceEvent
 */
export const SeqEvent_AkMusicCue = {
  CueName: 0x0180n,  // 0x0180 (0x0010) [FString]
  ...SequenceEvent,
} as const;

/**
 * ScriptStruct AkAudio.AkSoundSource.ActiveSound Offsets
 * Size: 0x0010
 */
export const ActiveSound = {
  Sound: 0x0000n,  // 0x0000 (0x0008) [UAkSoundCue*]
  PlayId: 0x0008n,  // 0x0008 (0x0004) [int32]
  StopId: 0x000cn,  // 0x000c (0x0004) [int32]
} as const;

/**
 * ScriptStruct AkAudio.AkEnvironments.AkActorEnvironment Offsets
 * Size: 0x0018
 */
export const AkActorEnvironment = {
  Environments: 0x0000n,  // 0x0000 (0x0010) [TArray<FAkEnvironment>]
  TargetActor: 0x0010n,  // 0x0010 (0x0008) [UActor*]
} as const;

/**
 * ScriptStruct AkAudio.AkEnvironments.AkEnvironment Offsets
 * Size: 0x0020
 */
export const AkEnvironment = {
  Id: 0x0000n,  // 0x0000 (0x0010) [FString]
  Priority: 0x0010n,  // 0x0010 (0x0004) [int32]
  WetValue: 0x0014n,  // 0x0014 (0x0004) [float]
  DryValue: 0x0018n,  // 0x0018 (0x0004) [float]
  HashedEnvID: 0x001cn,  // 0x001c (0x0004) [Fuint]
} as const;

/**
 * ScriptStruct AkAudio.InterpTrackAkEvent.AkEventTrackKey Offsets
 * Size: 0x0010
 */
export const AkEventTrackKey = {
  Time: 0x0000n,  // 0x0000 (0x0004) [float]
  Event: 0x0008n,  // 0x0008 (0x0008) [UAkSoundCue*]
} as const;

/**
 * ScriptStruct AkAudio.AkParamGroup.AkParamSet Offsets
 * Size: 0x00a0
 */
export const AkParamSet = {
  RTCPs: 0x0000n,  // 0x0000 (0x0050) [FMap_Mirror]
  Switches: 0x0050n,  // 0x0050 (0x0050) [FMap_Mirror]
} as const;

/**
 * ScriptStruct AkAudio.AkRevPhysicsSimulation.AkRevSimFrame Offsets
 * Size: 0x0010
 */
export const AkRevSimFrame = {
  RPM: 0x0000n,  // 0x0000 (0x0004) [float]
  Gear: 0x0004n,  // 0x0004 (0x0004) [int32]
  RevGear: 0x0008n,  // 0x0008 (0x0004) [int32]
  Velocity: 0x000cn,  // 0x000c (0x0004) [float]
} as const;

/**
 * ScriptStruct AkAudio.AkRevPhysicsSimulation.AkRevSimPhysicsControls Offsets
 * Size: 0x0020
 */
export const AkRevSimPhysicsControls = {
  Weight: 0x0000n,  // 0x0000 (0x0004) [float]
  EngineTorque: 0x0004n,  // 0x0004 (0x0004) [float]
  BreakingHorsePower: 0x0008n,  // 0x0008 (0x0004) [float]
  GearRatios: 0x0010n,  // 0x0010 (0x0010) [TArray<float>]
} as const;

/**
 * ScriptStruct AkAudio.AkRevPhysicsSimulation.AkRevSimUpdateParams Offsets
 * Size: 0x0048
 */
export const AkRevSimUpdateParams = {
  Throttle: 0x0000n,  // 0x0000 (0x0004) [float]
  Brake: 0x0004n,  // 0x0004 (0x0004) [float]
  EngineFrictionScale: 0x0008n,  // 0x0008 (0x0004) [float]
  GroundFrictionScale: 0x000cn,  // 0x000c (0x0004) [float]
  ClutchedGearRatio: 0x0010n,  // 0x0010 (0x0004) [float]
  bEnableUpShifting: 0x0014n,  // 0x0014 (0x0004) [bool : 0x1]
  Controls: 0x0018n,  // 0x0018 (0x0020) [FAkRevSimPhysicsControls]
  frame: 0x0038n,  // 0x0038 (0x0010) [FAkRevSimFrame]
} as const;

/**
 * ScriptStruct AkAudio.AkMusicAnalysis.MusicAnalysisInfo Offsets
 * Size: 0x001c
 */
export const MusicAnalysisInfo = {
  LowEnergy: 0x0000n,  // 0x0000 (0x0004) [float]
  Frequencies: 0x0008n,  // 0x0008 (0x0010) [TArray<float>]
  HighEnergy: 0x0018n,  // 0x0018 (0x0004) [float]
} as const;

/**
 * ScriptStruct AkAudio.SeqAct_AkPlayMusicWithCues.MusicSyncEvent Offsets
 * Size: 0x0011
 */
export const MusicSyncEvent = {
  CueName: 0x0000n,  // 0x0000 (0x0010) [FString]
  CueType: 0x0010n,  // 0x0010 (0x0001) [EMusicSyncType]
} as const;

/**
 * ScriptStruct AkAudio.AkSoundBanksInfo.SoundBankInfo Offsets
 * Size: 0x0030
 */
export const SoundBankInfo = {
  ShortName: 0x0000n,  // 0x0000 (0x0010) [FString]
  RelativePath: 0x0010n,  // 0x0010 (0x0010) [FString]
  Language: 0x0020n,  // 0x0020 (0x0010) [FString]
} as const;

/**
 * ScriptStruct AkAudio.AkEnvironments.uint Offsets
 * Size: 0x0004
 */
export const uint = {
  dummyint: 0x0000n,  // 0x0000 (0x0004) [int32]
} as const;
