/**
 * WinDrv Package - Offsets
 * Auto-generated by Stev Peifer
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

import { Client, FacebookIntegration, ForceFeedbackManager, HttpRequestInterface, HttpResponseInterface } from './Engine';

/**
 * WinDrv.FacebookWindows Offsets
 * Size: 0x00f8
 * Extends: FacebookIntegration
 */
export const FacebookWindows = {
  VfTable_FTickableObject: 0x00e8n,  // 0x00e8 (0x0008) [FPointer]
  ChildProcHandle: 0x00f0n,  // 0x00f0 (0x0008) [FPointer]
  ...FacebookIntegration,
} as const;

/**
 * WinDrv.HttpRequestWindows Offsets
 * Size: 0x00a8
 * Extends: HttpRequestInterface
 */
export const HttpRequestWindows = {
  Request: 0x0078n,  // 0x0078 (0x0008) [FPointer]
  RequestVerb: 0x0080n,  // 0x0080 (0x0010) [FString]
  RequestURL: 0x0090n,  // 0x0090 (0x0008) [FPointer]
  Payload: 0x0098n,  // 0x0098 (0x0010) [TArray<uint8>]
  ...HttpRequestInterface,
} as const;

/**
 * WinDrv.HttpRequestWindowsMcp Offsets
 * Size: 0x00c8
 * Extends: HttpRequestWindows
 */
export const HttpRequestWindowsMcp = {
  AppID: 0x00a8n,  // 0x00a8 (0x0010) [FString]
  AppSecret: 0x00b8n,  // 0x00b8 (0x0010) [FString]
  ...HttpRequestWindows,
} as const;

/**
 * WinDrv.HttpResponseWindows Offsets
 * Size: 0x0078
 * Extends: HttpResponseInterface
 */
export const HttpResponseWindows = {
  Response: 0x0060n,  // 0x0060 (0x0008) [FPointer]
  Payload: 0x0068n,  // 0x0068 (0x0010) [TArray<uint8>]
  ...HttpResponseInterface,
} as const;

/**
 * WinDrv.WindowsClient Offsets
 * Size: 0x03c0
 * Extends: Client
 */
export const WindowsClient = {
  AudioDeviceClass: 0x0278n,  // 0x0278 (0x0008) [UClass*]
  AllowJoystickInput: 0x02b8n,  // 0x02b8 (0x0004) [int32]
  ...Client,
} as const;

/**
 * WinDrv.XnaForceFeedbackManager Offsets
 * Size: 0x00b0
 * Extends: ForceFeedbackManager
 */
export const XnaForceFeedbackManager = {
  ...ForceFeedbackManager,
} as const;
