/**
 * XAudio2 Package - Offsets
 * Auto-generated by Stev Peifer
 *
 * Contains runtime offset constants for classes and structs.
 * Import these to read/write memory at the correct locations.
 */

import { AudioDevice } from './Engine';

/**
 * XAudio2.XAudio2Device Offsets
 * Size: 0x0460
 * Extends: AudioDevice
 */
export const XAudio2Device = {
  ...AudioDevice,
} as const;
